### ISSUE TITLE
Contains() Filter for Substring searching

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#100]
So, I noticed the .Contains() only seems to work for lists / array properties.

How would one search for a substring of a string property values?

```cs
// string Key = "WildcardCheck"
var partialKeyEnd = "Check";
var partialKeyStart = "Wildcard";
await collection.Where(c => c.Key.Contains(partialKeyStart)).ToListAsync();                <----- returns empty
await collection.Where(c => c.Key.Contains(partialKeyEnd)).ToListAsync();                  <----- returns empty
await collection.Where(c => c.Key == $"{partialKeyStart}{partialKeyEnd}").ToListAsync();   <-----  returns the results
```

**Comment by VagyokC4** [comment]
Hi @slorello89, 

I was hoping to hear back from you regarding some of these tickets.  I tried to keep them all separate issues.

So I think this ticket is more for bringing parity with the Redis-OM for Node example:

![image](https://user-images.githubusercontent.com/253250/165419483-e6d24a47-c3d3-4faa-9994-b06cb3eeee03.png)

I would think the dotNet version of .matches() would be the .Contains().

Any movement on this, or workarounds?  How do I search within a string field for a partial match?

**Comment by slorello89** [comment]
Hey @VagyokC4, sorry I've been pretty busy the last few weeks so I haven't had much time to look over these tickets.

So the `matches` syntax DOES match with `Contains` on a string field, however, it will not work on a string field marked as `Indexed` the string field must be `Searchable` for it to try to do a full-text match against it.

**Comment by VagyokC4** [comment]
> Hey @VagyokC4, sorry I've been pretty busy the last few weeks so I haven't had much time to look over these tickets.
> 
> So the `matches` syntax DOES match with `Contains` on a string field, however, it will not work on a string field marked as `Indexed` the string field must be `Searchable` for it to try to do a full-text match against it.

Good to know.  Do I need both Indexed and Searchable, or just Searchable is is enough for both types of searched?

**Comment by slorello89** [comment]
You can only use one or the other. Searchable will be more permissive of what it matches (it's going to be a full text search rather than an exact match)

**Comment by VagyokC4** [comment]
That worked!  Thank-you :)

**Comment by diogonborges** [comment]
Is there anyway of matching the start of the string?
i.e. I want to check strings that StartsWith("whatever")
Thanks!
