### ISSUE TITLE
"Fields arguments are missing" when creating an index.

### ISSUE THREAD

**Issue by jvyden** [redis/redis-om-dotnet#105]
Hello~, I've got a weird one for y'all. 

I'm aware support requests should go in the Discord, but I'm unsure if this is a bug or a mistake but I'm personally leaning towards bug so I'm writing this here. 

Today I tried to implement Redis support for my [project I'm attempting to heavily refactor](https://github.com/LBPUnion/ProjectLighthouse) using this library. The changes are now in master, but Redis functionality is abstracted away until this is working. I tested on my production server (don't question it :wink:) and I ended up getting the same error described below.

I got pretty far using the `redis-stack` docker image to host Redis locally, but as soon as I tried to add multiple indexes it went to hell with this exception:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Fields arguments are missing)
 ---> StackExchange.Redis.RedisServerException: Fields arguments are missing
   at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args)
   at Redis.OM.RediSearchCommands.CreateIndexAsync(IRedisConnection connection, Type type)
   at LBPUnion.ProjectLighthouse.Extensions.RedisConnectionExtensions.RecreateIndexAsync(IRedisConnection connection, Type type) in /home/jvyden/Documents/ProjectLighthouse/ProjectLighthouse/Extensions/RedisConnectionExtensions.cs:line 20
   at LBPUnion.ProjectLighthouse.Redis.Initialize() in /home/jvyden/Documents/ProjectLighthouse/ProjectLighthouse/Redis.cs:line 42
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at LBPUnion.ProjectLighthouse.StartupTasks.Run(String[] args, ServerType serverType) in /home/jvyden/Documents/ProjectLighthouse/ProjectLighthouse/StartupTasks.cs:line 80
   at LBPUnion.ProjectLighthouse.Servers.Website.Program.Main(String[] args) in /home/jvyden/Documents/ProjectLighthouse/ProjectLighthouse.Servers.Website/Program.cs:line 14
```

I traced the error to [this line in RediSearch's source code](https://github.com/RediSearch/RediSearch/blob/f03a543f6017268516bac397b6f9310e208e9006/src/spec.c#L733), but I'm still unsure as to what the actual problem is.

One interesting thing to note is that I completely reverted my changes with the new index, wiped multiple caches including my `$HOME/.cache` and JetBrains Rider's caches, updated my Arch Linux machine, and even ran a `git clean -xdf` yet I haven't been able to get the error to disappear; whatever happened appears to be permanent.

I've also wiped the docker container and tried a couple variations of the image but to no avail.

Told you it was a weird one, haha.

I'm happy to answer any questions and provide source code.

**Comment by slorello89** [comment]
Hi @jvyden - `Fields arguments are missing` sounds like redis OM is producing something for the aggregation it ought not to. Can you share with me the models you are using to perform these aggregations as well as the actual offending lines of code? If you have a working branch that you are using that could help me as well.

thanks!

**Comment by slorello89** [comment]
Hi @jvyden - I see why this is happening, it has to do with a limitation in RediSearch. RediSearch can only handle indexing arrays on strings, so:

```csharp
[Indexed]
public List<int> FriendIds { get; set; }
```

Produces nothing in the command serialization:

```text
"FT.CREATE" "userfrienddata-idx" "ON" "Json" "PREFIX" "1" "TestRedisOm.UserFriendData:" "SCHEMA"
``` 

So when it executes that against Redis, Redis barfs because the command is invalid,

I suppose the better way to handle this would be rather than passing over the erroneously marked field to propagate an argument exception because this is a bit confusing,

Anyway, in your case using a `List<string>` for these instances as well as `Room.PlayerIds` which fails silently above, is the way to mitigate it.

**Comment by jvyden** [comment]
Hmm, that's a little problematic given how my system works, but it will work for now I suppose. 

Is there a way I can have it explicitly ignore a property? 

It would be better for me to be able to have a property that automatically converts everything from integers back and forth and just hide the list with integers from this library.

**Comment by jvyden** [comment]
I'm also still confused about everything; it was actually working with a `List<int>` for at least an hour...

**Comment by slorello89** [comment]
The JsonIgnore for system.text.json should ignore it (we use system.text.json to serialize)

**Comment by slorello89** [comment]
> I'm also still confused about everything; it was actually working with a `List<int>` for at least an hour...

Yeah it was "working" because there were other fields that DID work - if your tried to query anything in there though, the queries would break

**Comment by jvyden** [comment]
> The JsonIgnore for system.text.json should ignore it (we use system.text.json to serialize)

Oh my god, that explains why it was working!

I had the list ignored before; this also interacts with an API and I guess I decided I wanted to expose that information and nonchalantly removed it, completely unaware of the disaster about to unfold.

Okay, I have a plan to implement everything now. Thank you so much for your help!

P.S: It should probably be mentioned on the README or some documentation that `[JsonIgnore]` can be used to hide things from serialization; I had no idea and was looking everywhere.
