### ISSUE TITLE
How to set TTL (expiration) for json record in Redis OM dotnet

### ISSUE THREAD

**Issue by shankar369** [redis/redis-om-dotnet#107]
How can we set expiry for a record in dotnet  ? I did go through documentation of Redis OM dotnet but could not find any method that we can use to set expiry for a record. But for the same package using python (Redis OM Python), there is a method to set expiry.

```
person_to_expire = Person.get(id)
Person.db().expire(person_to_expire.key(), seconds)
```
Can someone help me to understand how we can do the similar thing using Redis OM dotnet ?

**Comment by slorello89** [comment]
Hi @shankar369, you can drop directly down to the connection:

```
provider.Connection.Execute("EXPIRE", key, seconds);
```

**Comment by shankar369** [comment]
Hi @slorello89,  this is exactly what I want, and its working. Thank you :)

**Comment by VagyokC4** [comment]
> Hi @shankar369, you can drop directly down to the connection:
> 
> ```
> provider.Connection.Execute("EXPIRE", key, seconds);
> ```

Question?  Are you able to set the expire when saving the record?  I'm wondering if an overload for expiration would/could reduce a server call?
