### ISSUE TITLE
How to delete all documents on a index

### ISSUE THREAD

**Issue by giangcoi48k** [redis/redis-om-dotnet#109]
In the document, the way to delete a document is calls `Unlink` api
```
[HttpDelete("{id}")]
public IActionResult DeletePerson([FromRoute] string id)
{
    _provider.Connection.Unlink($"Person:{id}");
    return NoContent();
}
```
But, how to delete all documents, or delete a list of documents by the condition? I think if I need to loop for all the documents to delete, I will be slow

**Comment by slorello89** [comment]
Use IRedisConnection.DropIndexAndAsscoiatedRecords 

That will delete the index and everything it indexes

**Comment by giangcoi48k** [comment]
@slorello89 thank you very much. But is there any way to delete all the documents without drop the index?

**Comment by slorello89** [comment]
Not without enumerating the entire index. You can drop it and then recreate it back-to-back, since there's not indexed documents in the index the recreation will be nearly instantaneous
