### ISSUE TITLE
Increment value on a key

### ISSUE THREAD

**Issue by giangcoi48k** [redis/redis-om-dotnet#110]
How to increment a number stored at a field, something like `HashIncrement` api?
For example, I created an index, insert a list of items into that index, and then I want to increase a value of a field.
If I need to get the item by id, and increase the value by += operator, it will be slow?

**Comment by slorello89** [comment]
There isn't a way to search and update simultaneously yet, so if you don't know the key of the thing you want to increment you would need to search, update, save the update with the RedisCollection. This won't be super slow per-say, it just means that you would have to make 2 round trips to Redis, which isn't ideal.

If you have the key on the other hand you can either use the HINCR or JSON.INCR command depending on how your model is set up, if your model's storage type is hash (the default) it would be HINCR, if it's JSON then it would be JSON.INCR.

You can run `provider.Connection.Execute("CommandName", args. . .);` to do this.

**Comment by slorello89** [comment]
Goingto close this issue as I think I've answered it :)
