### ISSUE TITLE
Multi-level sorting with Aggregations

### ISSUE THREAD

**Issue by diogonborges** [redis/redis-om-dotnet#113]
This doesn't look to be documented. So i'm really not sure.

How would I be able to perform multiple level sortby with FT.Aggregate?

Example Model:
```
[Document(IndexName = "employees_idx", StorageType = StorageType.Hash)]
public class Employee
{
    [Searchable(Sortable = true)] public string Name { get; set; }

    [Indexed(Aggregatable = true, Sortable = true)]
    public int Age { get; set; }

    [Indexed(Aggregatable = true)] public double Sales { get; set; }

    [Searchable(Aggregatable = true)] public string Location { get; set; }

    [Indexed(CascadeDepth = 1)] public Department Department { get; set; }
}

public class Department
{
    [Searchable(Aggregatable = true)] public string Name { get; set; }

    [Indexed(Aggregatable = true)] public int Counter { get; set; }
}

```
Example: 
```
FT.AGGREGATE "employees_idx" "*" LOAD * SORTBY 4 @Age ASC @Name ASC
```

This would be roughly equivalent to:
```
FT.SEARCH "employees_idx" "*" SORTBY Age ASC
```

The only way I managed to get something going is by using the Execute method:

```
var reply = provider.Connection.Execute("FT.AGGREGATE", "employees_idx", "*", "LOAD", "*", "SORTBY", "4", "@Age", "ASC", "@Name", "DESC");
```

My main concern is how to do multi-level sorting with this library, particularly without having to use raw commands.
As a side note, from what I'm reading would _have_ to be done with FT.AGGREGATE because of a current limitation of Redis.Search that dropped the support for multi sort on FT.SEARCH. 

Thanks

**Comment by slorello89** [comment]
@diogonborges if I'm being honest I didn't realize we supported mult-level searches in anyway, I've opened a PR in #115 to add them. There is no LOAD predicate support atm, I keep seeing cases though where it would be useful (even though it does add a lot of overhead), so let me poke a bit at it today and see about adding it.

**Comment by slorello89** [comment]
Coming in #122

**Comment by slorello89** [comment]
Closing as #115 and #122 should address all the issues raised here.
