### ISSUE TITLE
No Results from Query on Indexed Ulid Property

### ISSUE THREAD

**Issue by rpf3** [redis/redis-om-dotnet#118]
I have a model with a secondary index on another Ulid:

``` c#
[Document(StorageType = StorageType.Json)]
public class Song
{
    [RedisIdField]
    public Ulid Id { get; set; }

    [Indexed]
    public Ulid AlbumId { get; set; }
}
```

When I try and query all songs matching an album the response comes back empty.

``` c#
var result = _collection.Where(x => x.AlbumId == albumId);
```

However if I first enumerate the collection and then filter, I get the data as expected.

``` c#
var result = _collection.ToList().Where(x => x.AlbumId == albumId);
```

In my main `Program.cs` I am calling `await redisConnectionProvider.Connection.CreateIndexAsync` on my models to build the indexes.

I feel like I'm missing something obvious here but have been debugging this for a while to no avail.

**Comment by slorello89** [comment]
@rpf3 - As it stands now, Redis OM is only set up to index/search numerics, strings, and GeoLocs. When you ask it to index a ULID, it doesn't know how to interpret the ULID for index creation so it ignores it. Try changing AlbumId -> a string and you'll see it work as expected. 

A broader effort to index/search other value types (enums, ULIDs, GUIDs, etc. . .) is something that is probably worth adding at some point down the lin.

**Comment by rpf3** [comment]
@slorello89 thank you, converting the property to a string worked as you described.  I agree that indexing `Ulid` would be especially useful given that Redis OM generates them as IDs by default.

**Comment by slorello89** [comment]
Going to roll this into #128
