### ISSUE TITLE
OFFSET exceeds maximum of 10000

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#119]
```
   at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args)
   at Redis.OM.RediSearchCommands.SearchAsync[T](IRedisConnection connection, RedisQuery query)
   at Redis.OM.Searching.RedisCollectionEnumerator`1.GetNextChunkAsync()
   at Redis.OM.Searching.RedisCollectionEnumerator`1.MoveNextAsync()
   at Redis.OM.Searching.RedisCollection`1.ToListAsync()
   at Redis.OM.Searching.RedisCollection`1.ToListAsync()
```

So I' m not sure what's going on as I'm using paging elsewhere and not having this issue.  (Maybe my paging is not triggering these levels)

I'm using the following code:
```csharp
var results = await RedisDb.TransactionRecord.Where(x => x.TransactionTimeSearch > 0)
   .AsQueryable()
   .OrderBy(x => x.TransactionTimeSearch)
   .Skip(30000)
   .Take(100)
   .AsRedisCollection()
   .ToListAsync();
```

Does this mean the ability tp page through collections are limited to 10000 records and you can't skip through larger collections?

**Comment by slorello89** [comment]
@VagyokC4 - RediSearch queries have a default cap on the number of results that are allowed to be in the result set. You can configure this either at startup of RediSearch, or you should be able to configure it with the FT.CONFIG command. See https://redis.io/docs/stack/search/configuring/#maxsearchresults

**Comment by VagyokC4** [comment]
> @VagyokC4 - RediSearch queries have a default cap on the number of results that are allowed to be in the result set. You can configure this either at startup of RediSearch, or you should be able to configure it with the FT.CONFIG command. See https://redis.io/docs/stack/search/configuring/#maxsearchresults

And if I wanted to just enumerate through the whole collection, what does that look like?  Is there a way to enumerate or page through them?

**Comment by VagyokC4** [comment]
@slorello89 Update: I set the maxsearchresutls, now I just timeout trying to get anything above 10k.

**Comment by slorello89** [comment]
I think this might be an issue in RediSearch - it looks like it hangs (regardless of the client you use) if you try to go past the initial set MAXSEARCHRESULTS. I opened RediSearch/RediSearch#2803 - Which should hopefully address the issue. I don't think I ever noticed this with RediSearch before because the default in that image was 1 Million documents rather than 10k.

**Comment by VagyokC4** [comment]
Hi @slorello89,

So I'm still trying to wrap my head around what is happening under the covers.  I have a collection with 900K records.  This particular collection I am able to search / page through a slice (of a particular user) of 123986 records with no issues. (this is without adjusting the 10k limit).  Paging, searching all seem to work.  I can go from the front of the collection to the back of the collection.

It's only when I started working with another collection where I wanted to page through all the records (not just a particular user) and that's when I started experiencing issues.  I'm not sure what the difference is between the two, and why I can correctly page through 120k records in one collection, but can't go over 10k in another.

Any ideas?

**Comment by slorello89** [comment]
@VagyokC4 - are you perhaps using a different version of RediSearch in the former case? The default used to be 1 million records so it would have taken a lot more to get to that point. As you can see there was a bug in RediSearch where it would lock-up when paginating past the limit

**Comment by slorello89** [comment]
@VagyokC4 - This ought to be resolved with the fix mentioned above - might take a bit to finally make it into redis stack, going to close this issue for now.

**Comment by VagyokC4** [comment]
@slorello89 Not sure if you have a way to contact or report an issue, however the latest redis/redis-stack-server:7.0.0-RC6, which includes the above fix, is broken.  It does not accept ARGS.  The 7.0.0-RC5 works, but RC6 no longer works [as seen here.](https://hub.docker.com/r/redis/redis-stack-server/tags)

For example, this will fail to start
`docker run -d --name Redis-Stack --restart=unless-stopped -e REDIS_ARGS="--save --appendonly yes" -e REDISEARCH_ARGS="MAXSEARCHRESULTS -1" -p 6379:6379 redis/redis-stack-server:7.0.0-RC6`

where as this will work just fine
`docker run -d --name Redis-Stack --restart=unless-stopped -e REDIS_ARGS="--save --appendonly yes" -e REDISEARCH_ARGS="MAXSEARCHRESULTS -1" -p 6379:6379 redis/redis-stack-server:7.0.0-RC5`

I'm not sure how to even report this.  Maybe you can alert the powers that be, that something broke in RC6?

**Comment by slorello89** [comment]
Hey Charles, I'd say open an issue in the [redis-stack](https://github.com/redis-stack/redis-stack) repo?

**Comment by slorello89** [comment]
cc'ing @chayim, but I'd still open the issue in that repo so it get's in front of them :)
