### ISSUE TITLE
Escaping special characters in JSON

### ISSUE THREAD

**Issue by diogonborges** [redis/redis-om-dotnet#121]
When i changed from JSON to Hash I started getting errors like:
System.Text.Json.JsonException: '0x0A' is invalid within a JSON string. The string should be correctly escaped.
System.Text.Json.JsonException: '0x0D' is invalid within a JSON string. The string should be correctly escaped.

Is this a bug?
Any recommendation?

**Comment by slorello89** [comment]
Hmm, what is the model you were using? What is an example of what one of these objects looked like? were there lingering JSON objects in your database when you switched to Hashes?

**Comment by diogonborges** [comment]
I can actually reproduce from greenfield.

```
[Document(IndexName = "employees_idx", StorageType = StorageType.Hash)]
public class Employee
{
    [Searchable(Sortable = true)] public string Name { get; set; }
}
```

```
var  provider = new RedisConnectionProvider(RedisConnectionString);
var employees = provider.RedisCollection<Employee>();
provider.Connection.DropIndexAndAssociatedRecords(typeof(Employee));
provider.Connection.CreateIndex(typeof(Employee));
employees.Insert(new Employee { Name = "Bob\\2"}); // notice this string property is stored as: Bob\2
employees.FirstOrDefault();
```

**Comment by diogonborges** [comment]
I just saw that interface, it's actually interesting approach to not rely on json serialization / deserialization.
I'll explore that, thanks!
