### ISSUE TITLE
How to write lambda to sql where in syntax？

### ISSUE THREAD

**Issue by liujiyuan** [redis/redis-om-dotnet#155]
How to write lambda to sql where in syntax？
look like "where xxx in( 1, 2, 3)" for get multi result once request.

**Comment by shacharPash** [comment]
Do you want to do somthing like this?:
 `var idList = new[] { 1, 2, 3, 4 };
  var result = customers.Where(x => idList.Contains(x.Id));`

**Comment by slorello89** [comment]
You would need to drop down to the raw Query API syntax:

```
var query = new RedisQuery("indexName");
query.QueryText = $"{{{string.Join('|', ids)}}}";
var res = await provider.Connection.SearchAsync<Type>(query);
```

if your ids are numeric, it would be more like `[1 1] | [2 2] | [3 3]`

**Comment by VagyokC4** [comment]
> Do you want to do somthing like this?:
> 
> ```cs
> var idList = new[] { 1, 2, 3, 4 };
> var result = customers.Where(x => idList.Contains(x.Id));
> ```

I would love something exactly like this :)

**Comment by liujiyuan** [comment]
> Do you want to do somthing like this?:
> 
> ```cs
> var idList = new[] { 1, 2, 3, 4 };
> var result = customers.Where(x => idList.Contains(x.Id));
> ```

Not this. Just like select * from table where id in (1, 2, 3, 4)

**Comment by liujiyuan** [comment]
Thank you all reply! I code to lambda convertor. like this:
`public Expression<Func<T, bool>> RedisOMIn<T>(Expression<Func<T, object>> expression, string[] ids)
        where T : notnull
        {
            if (ids == null || ids.Length == 0)
                throw new ArgumentException("ids length is not equal zero");
            var leftExp = expression.Body;
            Expression binexp = Expression.MakeBinary(
                            ExpressionType.Equal,
                            leftExp,
                            Expression.Constant(ids[0]));
            for (int i = 0; i < ids.Length; i++)
            {
                if (i == 0) continue;
                var innerbinexp = Expression.MakeBinary(
                            ExpressionType.Equal,
                            leftExp,
                            Expression.Constant(ids[i]));
                binexp = Expression.OrElse(binexp, innerbinexp);
            }

            var whereInExp = Expression.Lambda<Func<T, bool>>(binexp, expression.Parameters);
            return whereInExp;

        }`

**Comment by Misiu** [comment]
@liujiyuan please format your code.
Now the code you provided is hard to read.
