### ISSUE TITLE
how to batch insert model?

### ISSUE THREAD

**Issue by liujiyuan** [redis/redis-om-dotnet#156]
how to batch insert model?

**Comment by chayim** [comment]
@shacharPash Can you provide a sample - maybe taken from the doc we started on?

**Comment by slorello89** [comment]
At the moment, the best way to do this is to create a bunch of tasks with `IRedisCollection.InsertAsync` or `IRedisConneciton.SetAsync`, and await them all at the end.

e.g.

```cs
var tasks = new List<Task>(100_000);
for (var i = 0; i < 100_000; i++)
{
    tasks.Add(collection.InsertAsync(aPersonWeInsertManyTimes));
}

await Task.WhenAll(tasks);
```

If we awaited each task individually or used the sync version of Insert/Set, you would incur a round trip for each insert, which would be very expensive, by inserting asynchronously with a bunch of tasks and awaiting them all, the library will automatically pipeline everything for you, and will minimize the number of round-trips to Redis.

**Comment by liujiyuan** [comment]
> There is currently no way to do this, you can use foreach any other way that exists in the language, in combination with the Insert (using RedisCollection instance) or Set (using IRedisConnection instance) methods.

Thank you very much! I

**Comment by liujiyuan** [comment]
> 



> At the moment, the best way to do this is to create a bunch of tasks with `IRedisCollection.InsertAsync` or `IRedisConneciton.SetAsync`, and await them all at the end.
> 
> e.g.
> 
> ```cs
> var tasks = new List<Task>(100_000);
> for (var i = 0; i < 100_000; i++)
> {
>     tasks.Add(collection.InsertAsync(aPersonWeInsertManyTimes));
> }
> 
> await Task.WhenAll(tasks);
> ```
> 
> If we awaited each task individually or used the sync version of Insert/Set, you would incur a round trip for each insert, which would be very expensive, by inserting asynchronously with a bunch of tasks and awaiting them all, the library will automatically pipeline everything for you, and will minimize the number of round-trips to Redis.

Thank you very much!
