### ISSUE TITLE
Support `ReplaceById` and `ReplaceByIdAsync`

### ISSUE THREAD

**Issue by HazyFish** [redis/redis-om-dotnet#160]
### Current State

Currently, to update an object, we need to first retrieve the object using `GetByIdAsync` and then call `UpdateAsync`, even if in many use cases, we just want to replace the whole object in the database atomically.

Directly calling `UpdateAsync` with an object of the same ID won't work because the `UpdateAsync` internally does change detection based on the object reference. 

### Desired State

Provide `ReplaceById` and `ReplaceByIdAsync` that replace an object atomically.

**Comment by VagyokC4** [comment]
> ### Current State
> Currently, to update an object, we need to first retrieve the object using `GetByIdAsync` and then call `UpdateAsync`, even if in many use cases, we just want to replace the whole object in the database atomically.
> 
> Directly calling `UpdateAsync` with an object of the same ID won't work because the `UpdateAsync` internally does change detection based on the object reference.
> 
> ### Desired State
> Provide `ReplaceById` and `ReplaceByIdAsync` that replace an object atomically.

This is probably functionally the same as InsertAsync, as it will replace the document if it already exists, without any change checking etc.

**Comment by HazyFish** [comment]
I see. Could you change the name to be `SetAsync` or `InsertOrReplaceAsync` or improve the doc comments? The method name "insert" and its doc comment "Inserts an item into redis." do not seem to imply that it could replace an existing item.

**Comment by VagyokC4** [comment]
> I see. Could you change the name to be `SetAsync` or `InsertOrReplaceAsync` or improve the doc comments? The method name "insert" and its doc comment "Inserts an item into redis." do not seem to imply that it could replace an existing item.

Keep in mind this library is just a wrapper for Redis.  So all the principals of redis apply.  It's still a key/value dictionary at heart, so if you insert into a key a document, then insert into the same key a new document, redis is by nature going to replace.  All this library really does is abstract away the search capabilities of redis so that you can use linq to query redis instead of writing redisSearch commands yourself.
