### ISSUE TITLE
Async Query Support

### ISSUE THREAD

**Issue by HazyFish** [redis/redis-om-dotnet#161]
Currently, using `Where` to query is not asynchronous.

**Comment by slorello89** [comment]
The RedisCollection is an async enumerable, so when you enumerate it you can do so asynchronously, making `Where` async doesn't make any sense because it's not doing anything blocking (it's just creating a composite IQueryable with a more complicated expression). You can Asynchronously enumerate either through using `ToListAsync`, or by using the async enumerator directly:

```cs
await foreach(var element in collection)
{
   //do stuff
}
```

**Comment by HazyFish** [comment]
If I enumerate asynchronously, I think we're pulling items one by one from a collection and then filter them locally. I want to the database to return only the items that satisfies my `.Where` predicate. However, after I call `.Where`, the type becomes `IQueryable`, which does not have asynchronous methods like `.ToListAsync` anymore.

**Comment by slorello89** [comment]
If you pass an Expression<Func<T,bool>> into the Where method, it will invoke the IRedisCollection.Where extension method, which will return an IRedisCollection<T>, which you should be able to call ToListAsync against.

**Comment by HazyFish** [comment]
Can you give an example?

Looks like I can only invoke `IQueryable.Where`. There is no overload for `IRedisCollection.Where`.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/28922700/180562813-2aa50c9c-5655-473d-b35d-6aa215c33c89.png">

**Comment by HazyFish** [comment]
I checked the source code and found out that the code for the extension methods is in `Redis.OM` namespace instead of `Redis.OM.Searching` namespace where `IRedisCollection` is defined. As a result, we need to manually add `using Redis.OM` in additional to `using Redis.OM.Searching` in order to invoke `IRedisCollection<T>.Where`. 

I think we should move it into `Redis.OM.Searching` namespace or improve the documentation so others can easily find it without looking into the source code.

**Comment by VagyokC4** [comment]
> Can you give an example?


```csharp
var fooEmployees = await new RedisConnectionProvider("redis://localhost:6379")
.RedisCollection<Employee>()
.Where(x => x.Department == "foo")
.ToListAsync();
```
