### ISSUE TITLE
Support `DeleteById` and `DeleteByIdAsync` in `RedisCollection`

### ISSUE THREAD

**Issue by HazyFish** [redis/redis-om-dotnet#164]
I could use `IRedisConnection.Unlink` to achieve this but it would not delete the item from state manager.

**Comment by slorello89** [comment]
Delete and DeleteAsync should do this, you would just pass in the object you are deleting, if you had not materialized it, it would not be in the StateManager

**Comment by HazyFish** [comment]
The problem is that I don't have the object I'm deleting but I have the id of the object I am going to delete. 

The item could be materialized in an earlier call to another RedisCollection API that is independent to the delete request.

**Comment by VagyokC4** [comment]
> The problem is that I don't have the object I'm deleting but I have the id of the object I am going to delete.
> 
> The item could be materialized in an earlier call to another RedisCollection API that is independent to the delete request.

If you have the key, then you can use the [StackExchange.Redis](https://stackexchange.github.io/StackExchange.Redis) library to just remove the key.  It's geared to communicate and work with redis.  This library here is more for strongly typed models, and facilitating the redis search capabilities.

**Comment by HazyFish** [comment]
I want to use Redis to expose a Web API that allows our front-end to delete resources stored in Redis. When the client makes the DELETE request, it makes sense just to send the id. So I think the Redis Collection should provide such an API because otherwise we cannot use this library to build a very basic, standard CRUD API.

**Comment by VagyokC4** [comment]
> I want to use Redis to expose a Web API that allows our front-end to delete resources stored in Redis. When the client makes the DELETE request, it makes sense just to send the id. So I think the Redis Collection should provide such an API because otherwise we cannot use this library to build a very basic, standard CRUD API.

If all you have is a hammer, everything looks like a nail.  Each tool has it's advantages, and with the right set, you can do almost anything you want to do.  Look at the  StackExchange.Redis library if this library doesn't do what you want it to do.  It's a lower level way of working with redis.  This library is a higher level tool that sits on top of StackExcahnge.Redis.  The combination of the two should give you all you need to accomplish what you want.
