### ISSUE TITLE
FindById not being added to StateManager

### ISSUE THREAD

**Issue by slorello89** [redis/redis-om-dotnet#170]
If you `FindById` on the RedisCollection, the returned objects are not being added to the state manager, hence if you try to Save them the state manager does not see them and does not do anything with those objects.

**Comment by rebelf** [comment]
Facing the same issue

> If you `FindById` on the RedisCollection, the returned objects are not being added to the state manager, hence if you try to Save them the state manager does not see them and does not do anything with those objects.

**Comment by berviantoleo** [comment]
I've sent PR about this. Maybe needs some review if I'm doing it correctly.
