### ISSUE TITLE
Correct way of connecting to redis cluster

### ISSUE THREAD

**Issue by shankar369** [redis/redis-om-dotnet#172]
I have a redis cluster with sentinel flow with one master and 2 slaves running on kubernetes 
Pods
rediscluster-node-0           2/2     Running   0          14d
rediscluster-node-1           2/2     Running   0          14d
rediscluster-node-2           2/2     Running   0          14d

Service

rediscluster            ClusterIP   --.--.--.---    <none>        6379/TCP,26379/TCP   14d
rediscluster-headless   ClusterIP   None             <none>        6379/TCP,26379/TCP   14d

when I connect to the cluster using service "rediscluster",  and when I try writing some json data to redis cluster, the flow is not going in the correct way. Basically whenever there are any write operations to cluster those should be done from master node and read operations through any of the master/slave nodes. But in my case the write operations are also happening through slave nodes.

Here is how I was connecting to cluster and inserting data using this library.

```
var provider = new RedisConnectionProvider("rediscluster");
var data= provider.RedisCollection<Data>();
 data.Insert(new Data{name: "name1"});
```

My question here is, is there any parameter to pass to specify master node, so that the write operations should only be done from master node ?

**Comment by shankar369** [comment]
Found the solution for my issue.

If we are using sentinel flow then we need to specify the master service name in the connection string in order to connect to master for write operations. In my case the service name is my-master. Once I add that every thing is working expected. Thanks.

```
var connection = ConnectionMultiplexer.Connect("localhost:6379,serviceName=my-master,AllowAdmin=true");
provider = new RedisConnectionProvider(connection);
```

**Comment by slorello89** [comment]
Just a heads a heads-up @shankar369, if this is redis sentinel (which is different from Redis Cluster), you need to connect to a sentinel rather than a primary, those sentinels are typically on port 26379, that will allow the client to understand the topography of the sentinel deployment, and handle failovers when they happen

**Comment by shankar369** [comment]
@slorello89, that makes sense. Thanks :)
