### ISSUE TITLE
Best practice for updating index after C# ORM class is updated

### ISSUE THREAD

**Issue by frostshoxx** [redis/redis-om-dotnet#176]
Hello there,

I just realized that if I add new fields that needs to be indexed on the C# class, it won't automatically update the schema of redis stack index. Is the best practice is to delete the existing index and adding a new one? If I do that, do I need to call something to "reindexing" the existing documents?

Thank you,

**Comment by slorello89** [comment]
Index creation/deletion at the moment is an active process (you need to specifically instruct Redis OM to do it). I intentionally did not make it automatic as I did not want to introduce variability into what's indexed in Redis vs not based on a change to one of what might be several apps interacting with your data model. Perhaps some day we'll have enough demand to warrant the creation of a proper index migrator, but in the interim, to apply the updates, delete the index and re-create it. Just understand that index creation is an async process, you tell redis to build the index, and in the background, redis builds it, until that's finished you can get incomplete results. To check the progress just run `FT.INFO` on your index and check the `indexing` field - 0 means that the background indexing is complete, and all future documents will be indexed at insertion.

**Comment by frostshoxx** [comment]
@slorello89 

Thank you for the detail explanation. Can we accomplish the equivalent of `FT.INFO` within the .NET wrapper to wait if `indexing` field is not `0`?

**Comment by frostshoxx** [comment]
Would it be worthwhile to pursue the work similar to the abandoned PR `https://github.com/redis/redis-om-dotnet/pull/40`?
If these fields on `https://redis.io/commands/ft.info/` don't change that often, we may be able to put pull off the strong type mapping. Some of the metadata fields that could be helpful for maintenance stuff (e.g., `indexing`).

**Comment by frostshoxx** [comment]
@slorello89 

Here is a quick prototype that will return `RedisIndexInfo`. I haven't mapped all the fields yet because this could take some time to get them all in, so I would to run it by you first before I go further into this. 

Here's a quick code compare:
https://github.com/redis/redis-om-dotnet/compare/main...frostshoxx:redis-om-dotnet:frostshoxx/introduce-get-redis-index-info

![image](https://user-images.githubusercontent.com/567851/185259432-3d40fe6e-e68b-4f3c-a2e1-baedff0d5f5b.png)

Shall I go ahead and keep working on this, then open a PR when done?

Thank you,

**Comment by slorello89** [comment]
Think this is probably also closeable now that there's access to the FT.INFO command.
