### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bnayae** [redis/redis-om-dotnet#18]
Can the license be switch to MIT?
BSD-3-Clause License is less likely to be adopt by the open source community.

**Comment by slorello89** [comment]
Hi @bnayae - bit above my paygrade :) - @banker @gkorland - thoughts?

**Comment by banker** [comment]
Are you still able to use the library, or is this a deal breaker? @bnayae ?

**Comment by slorello89** [comment]
@bnayae - FYI I received direction to change the license to MIT. It will be effective in the NuGet package the next time it's published

**Comment by bnayae** [comment]
TNX, I believe it's the right license for this type of product.
