### ISSUE TITLE
Lambda expression query of version 0.2.1 is invalid

### ISSUE THREAD

**Issue by FlowerSea1** [redis/redis-om-dotnet#180]
![image](https://user-images.githubusercontent.com/111562421/185570041-0de9000f-efe1-4961-9d22-235603accf45.png)
![image](https://user-images.githubusercontent.com/111562421/185570120-918e8d71-2b41-4e73-8d85-71cd7d0b82ec.png)

**Comment by slorello89** [comment]
@FlowerSea1  - could you please share what your model looks like, if I had to guess, HTEId isn't deocrated with anything, or is a weird type, but I can't say for sure with what you've provided here.

**Comment by FlowerSea1** [comment]
@slorello89 Version 0.1.9 lambda queries are fine.
![image](https://user-images.githubusercontent.com/111562421/186299164-d977d72d-8356-4400-acc3-5d79f3afd7a8.png)

**Comment by FlowerSea1** [comment]
@slorello89 The reason is that the redis.om namespace is not referenced
![b634d9a636a3d00b84c8c1cc584ed78](https://user-images.githubusercontent.com/111562421/186619719-c0972439-5c5b-4a96-8931-f46abc2eb6a7.jpg)
