### ISSUE TITLE
FirstOrDefault Async not Updating on SaveAsync or Save

### ISSUE THREAD

**Issue by newburner** [redis/redis-om-dotnet#183]
```c#
 [HttpGet("/{shortName}")]

    public async Task<IActionResult> GetUrls(string shortName)
    {

        var newUrl = await _url.FirstOrDefaultAsync(a => a.shortName == shortName);

        if (newUrl == null) return NotFound("Url Not Found");
        newUrl.totalHits += 1;
        newUrl.updatedAt = DateTime.Now;

        await _url.SaveAsync();

        return Redirect(newUrl.originalUrl);
    }
```

Here I've used the first or default method to get an item from the redis db. I get the item , change some values and use the SaveAsync (or Save) Method to save changes, but it doesn't update the changed values, on the other hand the values are updated when i replace the firstordefaultasync method with non async firstordefault method and save changes.

**Comment by berviantoleo** [comment]
I think because the Async method didn't insert the result data into the snapshot. Maybe will need to add the result of the Async method to the snapshot.

![compare](https://user-images.githubusercontent.com/15927349/187112084-0060cb55-c7de-4441-9010-8149dc1c9a03.png)
