### ISSUE TITLE
Or operator not working on collection

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#191]
if you execute this, it will fail with a syntax error:

`customer.Where(x=>x.NickNames.Contains("Jim") || x.NickNames.Contains("john"));`

**Comment by slorello89** [comment]
Hey @zulander1 - this will be fixed by #193 - the method call expressions weren't adding paratheses around the generated query expressions, hence the query parser in RediSearch was choking when it would see queries like `(@NickNames:{Jim} | @NickNames:{john})` - which was what this was producing

**Comment by zulander1** [comment]
@slorello89 thank you

**Comment by VagyokC4** [comment]
@slorello89 Will this fix make it into 0.2.2 release?

**Comment by slorello89** [comment]
Can hold off on cutting the release until after it's merged.
