### ISSUE TITLE
'Cursor does not exist' exception

### ISSUE THREAD

**Issue by iozcelik** [redis/redis-om-dotnet#195]
I try to test aggregation but getting 'Cursor does not exist' exception. All code is here. What's wrong?

<img width="355" alt="image" src="https://user-images.githubusercontent.com/10682780/189081424-b8011128-9c46-41f0-90d5-e62655c42b1b.png">

```csharp
using Redis.OM;
using Redis.OM.Aggregation;
using Redis.OM.Aggregation.AggregationPredicates;
using Redis.OM.Modeling;
using System;
using System.Data.Common;
using System.Net;

var provider = new RedisConnectionProvider("redis://localhost:6379");
var connection = provider.Connection;
var people = provider.RedisCollection<Person>();

connection.DropIndex(typeof(Person));
connection.CreateIndex(typeof(Person));

people.Insert(new Person {
    Name = "Beaker",
    Age = 23,
    Sales = 500000,
    SalesAdjustment = .6,
    Height = 15,
    DepartmentNumber = 3
});

people.Insert(new Person {
    Name = "Dr Bunsen Honeydew",
    Age = 63,
    Sales = 500000,
    SalesAdjustment = .6,
    Height = 15,
    DepartmentNumber = 3
});

people.Insert(new Person {
    Name = "Fozzie Bear",
    Age = 45,
    Sales = 350000,
    SalesAdjustment = .7,
    Height = 14,
    DepartmentNumber = 2
});

var collection = provider.AggregationSet<Person>();
var departments = collection
    .Apply(x => x.RecordShell.Sales * x.RecordShell.SalesAdjustment, "AdjustedSales")
    .GroupBy(x => x.RecordShell.DepartmentNumber)
    .Sum(x => x["AdjustedSales"])
    .OrderByDescending(x => x["AdjustedSales_SUM"])
    .ToArray();

[Document(StorageType = StorageType.Json, IndexName = "person-idx")]
public partial class Person {
    [RedisIdField]
    [Indexed]
    public string Id { get; set; }
    [Searchable]
    public string Name { get; set; }

    [Indexed(Sortable = true)]
    public int? Age { get; set; }

    [Indexed(Sortable = true)]
    public double? Height { get; set; }

    [Indexed(Sortable = true)]
    public int? DepartmentNumber { get; set; }

    [Indexed(Sortable = true)]
    public double? Sales { get; set; }

    [Indexed(Sortable = true)]
    public double? SalesAdjustment { get; set; }
}
```

**Comment by slorello89** [comment]
Hi @iozcelik 

Under the hood, Redis OM is making use of the [cursor api](https://redis.io/docs/stack/search/reference/aggregations/#cursor-api) in RediSearch, the enumerator grabs chunks of data out of redis, enumerates them all, and then goes back to Redis for more data until the cursor is extinguished. There are a few things this could be:

1. You've left a breakpoint on and have stepped through the enumeration, and those steps through have taken long enough that the allowable idle time of the cursor has been exceeded
2. This exception is being thrown by the classes finalizer as it goes to delete the cursor - in which case the server exception is something that is being handled, you might just have an overly zealous debugger.
3. Your data is so big that the time to process a single page of the data in the client exceeds the idle time allowed for the cursor.

**Comment by iozcelik** [comment]
Hi @slorello89 ,

Actually, this is test code and all code. There are only 3 items in map. I start redis-stack with docker example on website. I use .net 6 and the lastest client. I also have not a breakpoint. If you want, I could share mini clip.

**Comment by slorello89** [comment]
try running without your debugger - do you see the exception get logged? your debugger is probably overly sensitive - the exception is very likely getting thrown by the finalizer of the AggregationEnumeroator - and would be suppressed under normal operation.

**Comment by iozcelik** [comment]
When I start without debuging, nothing happened.

I dont see logged exception but also I cannot see result. 

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/10682780/189155426-cb6184cb-dcc8-4ffb-9d55-de582c4fc468.png">

**Comment by slorello89** [comment]
@iozcelik - yeah that sounds like an overzealous debugger :) you can adjusted exception settings in your IDE. WRT getting results out, how are you trying to print your results? Adding:

```cs
foreach (var department in departments)
{
    Console.WriteLine($"{department["AdjustedSales_SUM"]}");
}
```

After the aggregation you provided seems to work fine for me.

**Comment by iozcelik** [comment]
@slorello89 It is my mistake, I write wrong string keyword :) It is works fine. Thanks... However in debug mode, the exception is not nice :)

**Comment by slorello89** [comment]
@iozcelik - yeah the exception is being handled so this is outside our purview - you just need to adjust the exception settings in your debugger :).

**Comment by iozcelik** [comment]
@slorello89 thanks :)
