### ISSUE TITLE
Is it possible to expire an element in an array or sorted set in redis ?

### ISSUE THREAD

**Issue by Jeevananthan-23** [redis/redis-om-dotnet#198]
Hi, 
So far Redis expiration is only set for the key, not for an element in an array or sorted set. But if possible for sorted set range by score and limit the set of values within that range. 
`  ZRANGEBYSCORE `
@slorello89 recently implemented `PEXPIRE` for `JSON` & `HSET` with #166 

Please add your comments

**Comment by shacharPash** [comment]
Hi, in Redis it is not possible to expire an element in an array or sorted set.
