### ISSUE TITLE
The collections state is no longer correct. even when saveState = false when using FirstOrDefaultAsync

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#205]
Hi @slorello89, 

Would you expect to still receive this error even when saveState is set to false?

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. 
A concurrent update was performed on this collection and corrupted its state. The collections state is no longer correct.   
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Redis.OM.Modeling.RedisCollectionStateManager.InsertIntoSnapshot(String key, Object value)
   at Redis.OM.Searching.RedisCollection`1.FirstOrDefaultAsync(Expression`1 expression)
```

**Comment by slorello89** [comment]
That's odd, can you share the whole chain for all possible shared instances of this collection? I wonder if somewhere it's not correctly propagating the saveState forward.

**Comment by VagyokC4** [comment]
> That's odd, can you share the whole chain for all possible shared instances of this collection? I wonder if somewhere it's not correctly propagating the saveState forward.

I'm not following.  What would you like me to share?

**Comment by rpf3** [comment]
I'm seeing both of these issues intermittently as well.  I think I have a similar setup to @VagyokC4 where I have a wrapper "Repository" class that creates an instance of the `RedisCollection` in its constructor.  This wrapper class is registered in my app with `AddScoped` however I did not see any change making it a transient service.

**Comment by rpf3** [comment]
Does [these internal](https://github.com/redis/redis-om-dotnet/blob/3eeb031484d5a345ab647926d94dcae888a4a1d0/src/Redis.OM/Modeling/RedisCollectionStateManager.cs#L43-L51) dictionaries need to be changed to `ConcurrentDictionary`?  This would have a bunch of downstream effects but I think the answer might depend on the expected DI usage pattern of the RedisCollection type.

**Comment by VagyokC4** [comment]
> I'm seeing both of these issues intermittently as well. I think I have a similar setup to @VagyokC4 where I have a wrapper "Repository" class that creates an instance of the `RedisCollection` in its constructor. This wrapper class is registered in my app with `AddScoped` however I did not see any change making it a transient service.

Yup, same pattern over here.  Are you doing any parallel processing on your side?  These issues really started popping up for me once I started doing in parallel queries that query the same collection (sometime different params, sometimes not).

I've been trying to get a repeatable test going.  I've been trying different variations to try and get the same error message as above, but in my LINQ pad it's proving a little tricky.  i.e. I can see it in a broken state, until it's not.

@slorello89 , Here is one variation that maybe can get us closer to the source of these problems.
```csharp
var redisConnectionProvider = new RedisConnectionProvider("redis://localhost:6379");
var redisCollection = redisConnectionProvider.RedisCollection<Customer>(false);
await redisConnectionProvider.Connection.CreateIndexAsync(typeof(Customer));

// Seed some data
var rnd = new Random(5);
await Task.WhenAll(Enumerable.Range(1, 10).Select(e =>
	redisCollection.InsertAsync(new Customer
	{
		FirstName = $"Test{rnd.Next(1, 3)}",
		NickNames = new[] { $"Test{rnd.Next(1, 3)}" }
	})
));

await Task.WhenAll(Enumerable.Range(1, 10).Select(e =>
	redisCollection.FirstOrDefaultAsync(x => x.NickNames.Contains($"Test1"))
	));
```
produces pretty regularly for me (when it shouldn't)
![image](https://user-images.githubusercontent.com/253250/191589345-39b1885a-7acb-4101-94dd-16a2926de89d.png)

**Comment by rpf3** [comment]
> When in theory it shouldn't once I set saveState=false

In order for this to be true, wouldn't every call to `StateManager` need to wrapped in a conditional based on the value of `saveState`?  Currently when you call `redisCollection.FirstOrDefaultAsync` it is trying to [insert into the underlying state manager dictionaries](https://github.com/redis/redis-om-dotnet/blob/3eeb031484d5a345ab647926d94dcae888a4a1d0/src/Redis.OM/Searching/RedisCollection.cs#L291-L292).  And because `Dictionary` isn't thread safe, running all of those async calls on the same redis collection will then be trying to read/write on the same underlying dictionary.

**Comment by VagyokC4** [comment]
> > When in theory it shouldn't once I set saveState=false
> 
> In order for this to be true, wouldn't every call to `StateManager` need to wrapped in a conditional based on the value of `saveState`? Currently when you call `redisCollection.FirstOrDefaultAsync` it is trying to [insert into the underlying state manager dictionaries](https://github.com/redis/redis-om-dotnet/blob/3eeb031484d5a345ab647926d94dcae888a4a1d0/src/Redis.OM/Searching/RedisCollection.cs#L291-L292). And because `Dictionary` isn't thread safe, running all of those async calls on the same redis collection will then be trying to read/write on the same underlying dictionary.

Yeah, I mentioned the Concurrent Dictionary #189 That will definitely help here without a doubt.  As for the `StateManager`, it just needs to know if we should be collecting state or not and do the exit early when appropriate to avoid any state related issues, to avoid any of the down stream methods from needing to change..

**Comment by slorello89** [comment]
@VagyokC4 @rpf3 - So my main issue with switching to a ConccurrentDictionary is that what we are seeing here is in fact a true race condition. If you enumerate the same collection twice (which was the root of Charles' issue in #189) you in fact have 2 distinct tasks (or threads, depending on how you're invoking it) populating the same StateManager simultaneously. This strikes me as quite wrong, especially since the first thing that happens when GetEnumorator is called, is clear the StateManager. The RedisCollection is not meant to be nor was it built to be thread-safe. We COULD wrap the errors up nicer - and be more explicit about this race condition - but I think throwing something out of the enumeration in which this race condition occurs is the correct course. 

Now WRT to the issue at hand, setting saveState to false SHOULD prevent this, but now that I've looked at it - I think it's pretty clear why this is happening inside the [RedisCollection](https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/Searching/RedisCollection.cs#L291) as @rpf3 pointed out, I boneheadedly forgot to guard these extra units from correctly checking if SaveState is set before trying to set it. Might have to think about how this is done to guard against this in the future.

**Comment by VagyokC4** [comment]
> @VagyokC4 @rpf3 - So my main issue with switching to a ConccurrentDictionary is that what we are seeing here is in fact a true race condition. If you enumerate the same collection twice (which was the root of Charles' issue in #189) you in fact have 2 distinct tasks (or threads, depending on how you're invoking it) populating the same StateManager simultaneously. This strikes me as quite wrong, especially since the first thing that happens when GetEnumorator is called, is clear the StateManager. The RedisCollection is not meant to be nor was it built to be thread-safe. We COULD wrap the errors up nicer - and be more explicit about this race condition - but I think throwing something out of the enumeration in which this race condition occurs is the correct course. 
> 
> Now WRT to the issue at hand, setting saveState to false SHOULD prevent this, but now that I've looked at it - I think it's pretty clear why this is happening inside the [RedisCollection](https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/Searching/RedisCollection.cs#L291) as @rpf3 pointed out, I boneheadedly forgot to guard these extra units from correctly checking if SaveState is set before trying to set it. Might have to think about how this is done to guard against this in the future.

My first thought would be to make it the state managers responsibility to determine if it's participating in state?  Then nothing changes downstream or going forward.

In my use case I am simulating views, different people with the possibility of the same view of the same data coming back all from multiple tasks.  And so, in this use case it's natural to expect the same query being run against the same collection at the same time, not necessarily everything unique.  Plus this is user data so...

Thank you for all the work you put into this so far, and I look forward to testing the fixed version.

**Comment by rpf3** [comment]
I also suspect that there might be some thread safety issues with the `FindByIdsAsync` method.  Within this method, a task for every ID is [created](https://github.com/redis/redis-om-dotnet/blob/a842268e9cd913fb9a76a647595c3825d3755f41/src/Redis.OM/Searching/RedisCollection.cs#L481-L487) and if I understand .NET async code (I probably don't) these tasks can be executed on any available thread.  Every individual call to `FindByIdAsync` will now be trying to write to the same StateManager internal Dictionary.
