### ISSUE TITLE
Convert Timespan to Long

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#208]
There is a bug when when you add an object with the TTL, looked at the code and it it should be ((long)ts.TotalMilliseconds).ToString(..)

it creates a PEXPIRE like this: PEXPIRE "KEY" "1579461.6029"
when you execute the same action with a long: PEXPIRE "KEY" "1579461" it works

**Comment by slorello89** [comment]
Interesting, good poing - but I'm curious - what code are you using to see something like this? Doubles usually support ~54 bits of integral precision (which I think should be enough to represent some pretty long TTLs)

**Comment by zulander1** [comment]
@slorello89 this: DateTime.Now.AddDays(1) - DateTime.Now, I think its the decimal place which redis doesn't like
