### ISSUE TITLE
.CreateAndEvalAsync() returns wrong value

### ISSUE THREAD

**Issue by wjfsdbd** [redis/redis-om-dotnet#214]
According to the current implement, the **return value** of **.CreateAndEvalAsync()** is converted from **RedisReply** to **int?**. But I found if the lua script returns **true**, **_internalLong** in **RedisReply** would be set 1 instead of **_internalInt**. This is proved by calling **.ExecuteAsync()** as an alternative.
![image](https://user-images.githubusercontent.com/36497011/192312742-a1fa1fa4-12f3-4ef0-9dda-0f8b034cc247.png)
However, the implicit is just implemented as beneath and returns **null** by mistake.
![image](https://user-images.githubusercontent.com/36497011/192313960-6fe42a92-6185-4ea1-85ac-46fd9618a550.png)
![image](https://user-images.githubusercontent.com/36497011/192315440-09ed4d7e-dd3c-40dd-8202-69b0a483504b.png)
Therefore I suppose the function should returns **RedisReply** instead so that user could convert it to appropriate type.

**Comment by slorello89** [comment]
This probably should not be a publicly exposed part of the API, it's meant to handle internal scripts that I wrote to update objects within redis, I think the fix here is to make it internal facing.
