### ISSUE TITLE
Hacktoberfest Examples: Create an Index and Store Documents

### ISSUE THREAD

**Issue by slorello89** [redis/redis-om-dotnet#218]
A useful example for folks would be a very basic Here's how you create an index (with embedded objects/arrays etc. . .) and store documents within it. I'll leave the models you want to use up to you but this should contain the following.

1. Two different classes to create indexes for. One stored as a hash, one stored as JSON
2. A blend of the different `DocumentAttribute` properties should be used to control things such as indexName, prefixes, stopwords
3. Each model should have a blend of different types to search on (strings, numbers, embedded objects etc. . .)

See #217 before getting started Thank you to all Hacktoberfest participants!

If you’d like to work on this please mention me [@slorello89](https://github.com/slorello89) or [@SuzeShardlow](https://github.com/SuzeShardlow) in a comment and we’ll assign this issue to you.
This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/
Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest [channel](https://discord.com/channels/697882427875393627/895802042797395989)

**Comment by zulander1** [comment]
@slorello89 i'll do it :)

**Comment by slorello89** [comment]
Sounds good @zulander1

**Comment by SuzeShardlow** [comment]
Hi @zulander1, how are you doing with this?

**Comment by zulander1** [comment]
@SuzeShardlow hey, sorry should be working on it this weekend, busy with work and stuff. Thanks
