### ISSUE TITLE
Hacktoberfest Examples: Full-Text Search within an Index

### ISSUE THREAD

**Issue by slorello89** [redis/redis-om-dotnet#220]
It would be pretty cool to see some examples of how to use Full-Text search within Redis OM.NET indexes, these mostly need to be decorated with `Text` attributes, and then more or less queried as normal. For more information on how to do full-text search in RediSearch (and probably some inspiration for this topic) check out the RediSearch docs, probably the topic on [FT.SEARCH](https://redis.io/commands/ft.search/) will be most instructive.

See #217 before getting started.

If you’d like to work on this please mention me [@slorello89](https://github.com/slorello89) or [@SuzeShardlow](https://github.com/SuzeShardlow) in a comment and we’ll assign this issue to you.
This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/
Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest [channel](https://discord.com/channels/697882427875393627/895802042797395989)

**Comment by Jeevananthan-23** [comment]
Hi, @slorello89/ @SuzeShardlow  I would like to work on this.

**Comment by SuzeShardlow** [comment]
Go for it @Jeevananthan-23. Please check out our guidelines and have fun! We look forward to seeing your pull request.

https://redis.io/community/hacktoberfest/

**Comment by Jeevananthan-23** [comment]
Thank you for giving me this opportunity @SuzeShardlow / @slorello89 . A pull request created please look into it.

**Comment by SuzeShardlow** [comment]
Thanks @Jeevananthan-23, we will check it out :)
