### ISSUE TITLE
Hacktoberfest Examples: Querying Strings within Arrays

### ISSUE THREAD

**Issue by slorello89** [redis/redis-om-dotnet#221]
Querying strings within arrays is something that comes up fairly often. Well, both querying strings within arrays and querying strings within arrays of embedded documents. In other-words. Given that a document has an array of strings, you should be able to query this array by using the `Contains` method on the array. Similarly, if a document contains an array of objects with an indexed string field, you should be able to use the `Any` method within your top-level query to find documents matching that pattern

See #217 before getting started.

If you’d like to work on this please mention me [@slorello89](https://github.com/slorello89) or [@SuzeShardlow](https://github.com/SuzeShardlow) in a comment and we’ll assign this issue to you.
This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/
Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest [channel](https://discord.com/channels/697882427875393627/895802042797395989)

**Comment by Ramin-Guliyev** [comment]
Hi @slorello89 , I would like to work on this.

**Comment by SuzeShardlow** [comment]
Hi @Ramin-Guliyev, go for it! Please check out our guidelines and have fun! We look forward to receiving your pull request.

https://redis.io/community/hacktoberfest/
