### ISSUE TITLE
Hacktoberfest Examples: Updating Documents Stored In Redis

### ISSUE THREAD

**Issue by slorello89** [redis/redis-om-dotnet#222]
Updating Documents within Redis with Redis OM .NET is something that comes up a lot. There are two basic ways to do this, with `Update` and with `Save` methods of RedisCollection. Examples for each of these methods I think would be quite helpful for folks.

See #217 before Starting.

If you’d like to work on this please mention me [@slorello89](https://github.com/slorello89) or [@SuzeShardlow](https://github.com/SuzeShardlow) in a comment and we’ll assign this issue to you.
This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/
Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest [channel](https://discord.com/channels/697882427875393627/895802042797395989)

**Comment by atrievel** [comment]
Hey there [@slorello89](https://github.com/slorello89) and [@SuzeShardlow](https://github.com/SuzeShardlow) - I'd love to work on this if it is still available. Thanks in advance!

**Comment by SuzeShardlow** [comment]
Hi @atrievel, I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/
#217

**Comment by Jeevananthan-23** [comment]
Hi @SuzeShardlow / @slorello89  if possible I would like to work on this. Is it ok for @atrievel ?

**Comment by SuzeShardlow** [comment]
@atrievel how are you getting on with this?

**Comment by atrievel** [comment]
Hey @SuzeShardlow, I didn't see the original notification that assigned me. Should be done shortly now that I know I can work on it
