### ISSUE TITLE
Hacktoberfest Examples: Deleting Documents within Redis

### ISSUE THREAD

**Issue by slorello89** [redis/redis-om-dotnet#223]
After a document has been added, deleteing it either via the referenced object, or simply by it's ID or key would be instructive for folks.

See #217 before starting.

If you’d like to work on this please mention me [@slorello89](https://github.com/slorello89) or [@SuzeShardlow](https://github.com/SuzeShardlow) in a comment and we’ll assign this issue to you.
This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/
Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest [channel](https://discord.com/channels/697882427875393627/895802042797395989)

**Comment by rahul-s-bhatt** [comment]
@slorello89  this looks like a really good opportunity, Can you assign this to me?

**Comment by SuzeShardlow** [comment]
Hi @rahul-s-bhatt, I've assigned this to you, looking forward to seeing your PR in the next couple of days.  Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/
https://github.com/redis/redis-om-dotnet/issues/217

**Comment by rahul-s-bhatt** [comment]
@SuzeShardlow Yes will do, thank you so much for assigning!
