### ISSUE TITLE
Hacktoberfest Examples: Dropping down to the lower-level Search API for an Index

### ISSUE THREAD

**Issue by slorello89** [redis/redis-om-dotnet#224]
It's not always possible for the RedisCollection to build a perfect representation of what the user needs, that's why we have the `RedisQuery` and raw Search command. An example showing folks how to drop down to this lower level API would be really helpful for those edge cases we can't catch). At the end of the day, one of these queries will result in a collection of strongly-typed results- which is pretty useful in and of itself. For more details of the things you can do with the raw query API, check out the [FT.SEARCH](https://redis.io/commands/ft.search/) command page, as well as the [Query Syntax](https://redis.io/docs/stack/search/reference/query_syntax/) page

See #217 before proceeding.

If you’d like to work on this please mention me [@slorello89](https://github.com/slorello89) or [@SuzeShardlow](https://github.com/SuzeShardlow) in a comment and we’ll assign this issue to you.
This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/
Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest [channel](https://discord.com/channels/697882427875393627/895802042797395989)

**Comment by berviantoleo** [comment]
Hi @slorello89 , @SuzeShardlow ,

May I take this? I think this is interesting too. :smile:

**Comment by slorello89** [comment]
Sounds good @berviantoleo - assigned.
