### ISSUE TITLE
Support for bulk insert

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#238]
It would be great and usefull to have a bulk insert. mostly for seeding data,

**Comment by Jeevananthan-23** [comment]
Hi @slorello89, please check whether the below BulkInsert method works fine or not.
My test 

``` CSharp
 [Fact]
        public void TestBulkInsert()
        {
            var collection = new RedisCollection<Person>(_connection);
            var persons = new List<Person>() {
                new Person() { Name = "Alice", Age = 51, NickNames = new[] { "Ally", "Alie", "Al" }, },
                new Person() { Name = "Robert", Age = 37, NickNames = new[] { "Bobby", "Rob", "Bob" }, } };

            collection.BulkInsert(persons);

            var people = collection.Where(x => x.NickNames.Contains("Bob") || x.NickNames.Contains("Alie")).ToListAsync();

            Assert.Equal(people.Result.Count, persons.Count);
            Assert.Contains(people.Result, x => x.Id==persons.First().Id);
        }

// BulkInset Method for seeding
  public async Task BulkInsert(IList<T> items)
        {
            var tasks = new List<Task>();
            foreach (var item in items)
            {
                tasks.Add(_connection.SetAsync(item));
            }

            await Task.WhenAll(tasks);
        }
```

**Comment by zulander1** [comment]
@Jeevananthan-23, I was thinking more like doing a MSET, i am already doing this and it's slow when you have 30k of objects

**Comment by Jeevananthan-23** [comment]
We have to focus on pipeline to make it as expected to insert bulk data.

**Comment by Jeevananthan-23** [comment]
@zulander1  [MSET with file](https://gist.github.com/MarshalOfficial/89c14cfaed7bbfa4f7c3f9eec16fa96a) similarly your trying ?

**Comment by slorello89** [comment]
@Jeevananthan-23 Ideally it would also return the key-names it derived from each insertion as well, those would either be 
1. bound to the object's `RedisIdField` property - generated at insertion
2. Already present in that property and honored for insertion

I do have questions wrt how this insertion would work. If you're inserting an object that will have the same ID twice - will the last one just win? will it error?

Also, to @zulander1's point - this will be a linear operation, so it could potentially take a lot of time, it should scale about linearly with the size of the data that is being inserted. My suggestion to folks in the past who are inserting massive sets of records (I've had people bulk-inserting millions of records) - is to chunk up the data and send it to Redis, there should probably be some configurable chunk-size for these insertions, of course that also brings in the challenge of what should we do with a partial insertion failure? Probably just alert the user to the items that failed to be inserted. (all this is why I haven't exposed an API like this yet :) ) Useful for discussion though.

**Comment by zulander1** [comment]
@slorello89  I have looked at https://github.com/StackExchange/StackExchange.Redis/issues/1089#issuecomment-471934196 which i think would work, what do you think?

**Comment by Jeevananthan-23** [comment]
> @Jeevananthan-23 Ideally it would also return the key-names it derived from each insertion as well, those would either be
> 
> 1. bound to the object's `RedisIdField` property - generated at insertion
> 2. Already present in that property and honored for insertion
> 
> I do have questions wrt how this insertion would work. If you're inserting an object that will have the same ID twice - will the last one just win? will it error?

@slorello89, please correct me if I'm wrong. In my case if the ID's are same the last one just win.
For eg: `redis-cli`:
```
SET foo bar
OK
GET foo
bar
SET foo newbar
OK
GET foo
newbar
```

**Comment by slorello89** [comment]
WRT duplicates having the latter overwrite the previous records, I think I buy that, but I'm still concerned as this operations when abused could easily crash the whole ConnectionProvider. It will need to chunk up the records and send them across the wire in waves rather than as one massive clump.

**Comment by Jeevananthan-23** [comment]
@slorello89, 4ce968f3924398dab1507907e0da5cbfc159f569 here I implemented Bulk insert with test it working fine it can be the alternative for `SaveAsync()` . please check I wish to create the PR for the same.

**Comment by zulander1** [comment]
@Jeevananthan-23 , I think this you should rename the method, so it's call insert, this will allow the insert to have an overload 😉

**Comment by Jeevananthan-23** [comment]
@zulander1, Did you test your case with the PR(#246) ? I hope this does not solve your problem 😒

**Comment by zulander1** [comment]
Did not test it , I have the same implementation as yours. When it's merged I will update accordingly.

But it's wasn't a problem, more of an enhancement.
