### ISSUE TITLE
Support for enum flag searching when storing as string

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#239]
Hi @slorello89,

Wanted to know your thoughts on the best way to address this issue.

Using the following model: 
```csharp
[Flags]
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum EnumFlags
{
	None = 0,
	Internal = 1 << 0,
	Client = 1 << 1,
	Server = 1 << 2,
	Edited = 1 << 3,
	Deleted = 1 << 4,
	Archived = 1 << 5
}

[Document(StorageType = StorageType.Json)]
public record EnumFlagTest
{
	[RedisIdField][Indexed] public string Id { get; set; }

	[JsonConverter(typeof(JsonStringEnumConverter))]
	[Indexed(Separator = ',')]
	public EnumFlags? Flags { get; set; }
}
```

and inserting the following record in like this:
```csharp
var coll = RedisDb.GetRedisCollection<EnumFlagTest>();
await coll.InsertAsync(new EnumFlagTest{Flags = EnumFlags.Client|EnumFlags.Server});
```

produces this result:
```json
{
  "Id": "01GFPFHRZ1GGVQXQ6Q3C5833VK",
  "Flags": "Client, Server"
}
```

and with the `[Indexed(Separator=',')]` it looks like we are very close to be able to search on it...  if only there was a way.

I would like to do something like this:
```csharp
var res = coll.Where(x => x.Flags.Contains(EnumFlags.Client)).ToListAsync();
```

I saw your post about the requests for ideas for Hacktoberfest. Maybe this is a little too advanced...  but I thought I'd post it here to start the conversation.

Thoughts?

**Comment by slorello89** [comment]
Interesting @VagyokC4  - looks like it's a bug:

```
"FT.CREATE" "enumflagtest-idx" "ON" "Json" "PREFIX" "1" "TestRedisOm.EnumFlagTest:" "SCHEMA" "$.Id" "AS" "Id" "TAG" "SEPARATOR" "|" "$.Flags" "AS" "Flags" "TAG"
```

is the index it's spitting out - as you can see it's using the default `|` separator as the separator.

**Comment by slorello89** [comment]
@VagyokC4 - so this one's a bit interesting, in RediSearch with hashes, a command would be the default delimiter, however since this is a JSON type, RediSearch does not automatically use a delimiter, so all we really need to do is have it explicitly set a delimiter if the Enum is a flag type enum - opened #241 to address this.

**Comment by VagyokC4** [comment]
> @VagyokC4 - so this one's a bit interesting, in RediSearch with hashes, a command would be the default delimiter, however since this is a JSON type, RediSearch does not automatically use a delimiter, so all we really need to do is have it explicitly set a delimiter if the Enum is a flag type enum - opened #241 to address this.

So would the end query be a contains query?

**Comment by slorello89** [comment]
No it would just be an equals query see my test in the PR
