### ISSUE TITLE
RedisCollection.Any() without parameters is not implemented

### ISSUE THREAD

**Issue by gabrieldep** [redis/redis-om-dotnet#243]
I cannot use Any() in RedisCollection. To verify if there are any registers, we have to get the count and compare it to 0. 
![image](https://user-images.githubusercontent.com/55631838/197431694-22d9f677-bed1-4cf4-8554-f932096a8007.png)
![image](https://user-images.githubusercontent.com/55631838/197431414-f6264cd9-aef8-467d-ab2e-bf154f3c9525.png)
![image](https://user-images.githubusercontent.com/55631838/197431602-0a6e988a-849c-457b-ab6f-0c4e4f772bdd.png)

**Comment by gabrieldep** [comment]
I tried to implement it but still with the same error.
![image](https://user-images.githubusercontent.com/55631838/197431866-62a74347-b4ac-4f7c-8ed3-f3b064c10b4e.png)

**Comment by slorello89** [comment]
Interesting, this should just be producing a very basic `FT.SEARCH indexname * LIMIT 0 0` and doing the check like you're doing. I'll dig into it.
