### ISSUE TITLE
Link not Working -- 404 Error

### ISSUE THREAD

**Issue by samgithub** [redis/redis-om-dotnet#25]
The link for "Redis OM .NET docs site: is not working,

https://redis-developer.github.io/redis-om-dotnet   - - > 404 Error

**Comment by slorello89** [comment]
Looks like the error happened when the repo was moved from the redis-developer org to the redis org. Regardless, the tutorial now lives on `developer.redis.com` - updated the link and added another link to the github page for the repo. That should straighten everything out.
