### ISSUE TITLE
Escape Contains

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#252]
When using contains, it does not escape:

```
List<string> emails = new List<string>() { "offthelip@comcast.net", "someoue@outlook.com", "quantaman@verizon.net", "jwarren@hotmail.com", "presoff@hotmail.com", "lamky@aol.com", "danzigism@me.com", "feamster@hotmail.com", "mailarc@mac.com", "gomor@sbcglobal.net", "fudrucker@gmail.com", "odlyzko@icloud.com" };
var newton = await customers.Where(x => emails.Contains(x.Email)).FirstOrDefaultAsync();
```

Will results in:
`
"FT.SEARCH" "customer-idx" "(offthelip@comcast.net|someoue@outlook.com|quantaman@verizon.net|jwarren@hotmail.com|presoff@hotmail.com|lamky@aol.com|danzigism@me.com|feamster@hotmail.com|mailarc@mac.com|gomor@sbcglobal.net|fudrucker@gmail.com|odlyzko@icloud.com:{\\@Email})" "LIMIT" "0" "1"`

**Comment by slorello89** [comment]
that query appears to be inverted as well - interesting.

**Comment by iozcelik** [comment]
I think it is related with #203

**Comment by Jeevananthan-23** [comment]
Hi @slorello89, #263 PR is opened to address the fix for the issue. Kindly review the same, Thanks!
