### ISSUE TITLE
An error will occur when a key expire, while enumerating

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#256]
This took a while to figure it out, and it is related to [this](https://github.com/redis/redis-om-dotnet/issues/169) issue, when you execute this code, you will get System.IndexOutOfRangeException: 'Index was outside the bounds of the array. after 10 seconds, the expected behavior should be null

```

    public class Program
    {
        [Document(StorageType = StorageType.Json)]
        public class Customer
        {
            [Indexed] public string FirstName { get; set; }
            [Indexed] public string LastName { get; set; }
            [Indexed] public string Email { get; set; }
            [Indexed(Aggregatable = true)] public int Age { get; set; }
            [Indexed(Aggregatable = true)] public GeoLoc Home { get; set; }
        }

        private static void Main(string[] args)
        {
            // connect
            var provider = new RedisConnectionProvider("redis://localhost:6379");
            var connection = provider.Connection;
            var customers = provider.RedisCollection<Customer>();
            var customerAggregations = provider.AggregationSet<Customer>();

            // Create index
            connection.CreateIndex(typeof(Customer));

            // Get Index info
            var indexinfo = connection.GetIndexInfo(typeof(Customer));

            // Insert Object
            customers.Insert(new Customer
            {
                FirstName = "James",
                LastName = "Bond",
                Email = "bondjamesbond@email.com",
                Age = 68
            }, TimeSpan.FromSeconds(10));

            List<Customer> res = null;
            while (true)
            {
                res = customers.Where(x => x.LastName == "Bond").ToList();
                Task.Delay(1000);
            }
 
        }
    }


```

**Comment by slorello89** [comment]
Dropping this here (we chatted in discord already) but the task in your while loop isn't being properly awaited, so some weird race condition I can't pin down is arising here.

Your point about the error handling is totally valid though, the index out of bounds error that occurs whenever we run into a parsing issue on the responses we get back from Redis is really crappy.  Think the PR you opened is a good first step, will look into it.

**Comment by zulander1** [comment]
@slorello89 , I think i found it (maybe), i've looked at the code and looked at the  what we have discussed, when a little future; the problem is that the   RedisReply is not be phrased property ..  

This is the results of the failing query (of [this](https://github.com/redis/redis-om-dotnet/blob/2beb85807622e43b7e1ec566f8be45e6ef1109f0/src/Redis.OM/RedisConnection.cs#L36))
![image](https://user-images.githubusercontent.com/12099546/205806730-f1503ff0-bef0-43f8-a5d6-409e9fadd4de.png)

The same query was executed (succesfully) and this was the results:
![image](https://user-images.githubusercontent.com/12099546/205807548-b86e5404-281f-4a16-a4c6-75fabb4234b5.png)
