### ISSUE TITLE
Add ability in Aggregation expressions for typed parameter expression

### ISSUE THREAD

**Issue by salmanrazacl** [redis/redis-om-dotnet#260]
Currently for grouping or sorting i have to provide fixed expressions like below
```
employeeAggregations.GroupBy(x => x.RecordShell.Department)
                .Sum(x => x.RecordShell.Sales).OrderBy(x => x.RecordShell.Department);
```

If we had the ability to use reflection instead of direct fields, this could be used in more dynamic way like below
```
employeeAggregations.GroupBy(x => x.RecordShell.GetType().GetProperty("Department").GetValue(x, null))
                .Sum(x => x.RecordShell.Sales).OrderBy(x => x.RecordShell.Department);
```

If there's a way to this in current latest build please let me know otherwise if we can have this as a feature/enhancement for future release.

**Comment by slorello89** [comment]
@salmanrazacl, actually you should be able to use indexed access on the Aggregation result e.g.

```cs
employeeAggregations.GroupBy(x => x["Department"])
                .Sum(x => x.RecordShell.Sales).OrderBy(x => x.RecordShell.Department);
```
would be just as valid. It's impossible for us to know completely ahead of time everything that can be produced in the pipeline - so you're allowed to use the aggregation result like it's a dictionary (which is what it basically is under the hood).

**Comment by slorello89** [comment]
Going to close this out as I think the question is answered. Feel free to reopen if needed.
