### ISSUE TITLE
Bulk Operations

### ISSUE THREAD

**Issue by MohamadTahir** [redis/redis-om-dotnet#261]
Hello, Adding the ability to do bulk operations like InsertMany and deleteMany, and updateMany.

**Comment by zulander1** [comment]
There is already a batch https://github.com/redis/redis-om-dotnet/pull/246, but there is none for deleteMany and updateMany

**Comment by slorello89** [comment]
FWIW `Save` is more or less update many - you just need to make sure that those you wish to update are currently enumerated, otherwise the batch insert would serve to do a full update (as you're setting everything at the root path)

**Comment by Jeevananthan-23** [comment]
hi @slorello89, I would like to work on this enhancement. As I already added a batch by #246 
Few items for clarification:
- **Bulk insert** which is already added but anyway this function is `Async` so I should refactor and add a `Sync` function for the bulk insert operation -  please add your points.
-  **` WhenKey`** - should be part of the bulk operation?
- **UpdateMany** - as you mentioned above this function should check for the snapshot to get diff and update the record accordingly.
- **DelMany** - uses `Unlink` to remove the enumerated item.
- **All the bulk operations should have `Sync` & `Async` methods?**
