### ISSUE TITLE
Issue with Query when using Sortable on INT value property.

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#262]
@slorello89 I'm running into a weird issue where my query, when using a Sortable numeric property gives back different results.

So using the following code:
```csharp
	var requestFrom = 0.Dump("From");
	var requestTo = DateTime.UtcNow.ToUnixTimeMs().Dump("To");
	var query = redisDb.Records.Where(q => q.Accno == "XXX");

	query = query.Where(q => q.TimeSearch < requestTo);
	query = query.Where(q => q.TimeSearch > requestFrom);
        query = query.Where(x => x.Hold == false);

	var count = query.CountAsync();
	var results = query
		.OrderByDescending(x => x.TimeSearch)
		.Skip(0)
		.Take(10)
		.ToListAsync();

	await Task.WhenAll(count, results).ConfigureAwait(false);
	count.Result.Dump("Count");
```
Produces the following redis query:
```
"FT.SEARCH" "record-idx" "((((@Accno:{XXX}) (@TimeSearch:[-inf (1669166114118])) (@TimeSearch:[(0 inf])) (@Hold:{False}))" "LIMIT" "0" "0"
"SELECT" "0"
"FT.SEARCH" "record-idx" "((((@Accno:{XXX}) (@TimeSearch:[-inf (1669166114118])) (@TimeSearch:[(0 inf])) (@Hold:{False}))" "LIMIT" "0" "10" "SORTBY" "TimeSearch" "DESC"
"INFO" "all"
```
and the following results: (each flash is me re-running the query)

https://user-images.githubusercontent.com/253250/203449888-96a1fd4b-2e95-4de0-8d9c-492b1e0866b9.mp4

But as soon as I comment out the TimeSearch clauses, I get consistent results again:
```csharp
	var requestFrom = 0.Dump("From");
	var requestTo = DateTime.UtcNow.ToUnixTimeMs().Dump("To");
	var query = redisDb.Records.Where(q => q.Accno == "XXX");

	// query = query.Where(q => q.TimeSearch < requestTo);
	// query = query.Where(q => q.TimeSearch > requestFrom);
        query = query.Where(x => x.Hold == false);

	var count = query.CountAsync();
	var results = query
		.OrderByDescending(x => x.TimeSearch)
		.Skip(0)
		.Take(10)
		.ToListAsync();

	await Task.WhenAll(count, results).ConfigureAwait(false);
	count.Result.Dump("Count");
```
producing this redis query:
```
"FT.SEARCH" "record-idx" "((@Accno:{XXX}) (@Hold:{False}))" "LIMIT" "0" "0"
"SELECT" "0"
"FT.SEARCH" "record-idx" "((@Accno:{XXX}) (@Hold:{False}))" "LIMIT" "0" "10" "SORTBY" "TimeSearch" "DESC"
"INFO" "all"
```

With results like so: (each flash is me re-running the query)

https://user-images.githubusercontent.com/253250/203450551-f782ba26-fdaf-4fa9-ac13-9c03cb5e095a.mp4

So far I have not been able to repeat this in a small test, but I see this issue with my current production data.  I will try to put together a repeatable test and add to this issue, but I wanted to get what I'm seeing now out there.  Because I think the raw query is looking right, I'm guessing this will be a lower level issue in RediSearch itself?

Any ideas?

**Comment by VagyokC4** [comment]
I'm going to close this issue out.  The results I was seeing were due to the default timeout of 500ms.  Once I gave the query more time to run, it was able to complete with consistent results.

**Comment by ashtul** [comment]
Thank you @VagyokC4.
Timeout is a suspect whenever the number of results changes but always have 99 at the end.
