### ISSUE TITLE
Support for RediSearch Wildcard Support

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#264]
![image](https://user-images.githubusercontent.com/253250/203922796-7f1f2b36-a95c-48ef-bd83-eae012449687.png)
https://github.com/RediSearch/RediSearch/pull/2886

Hi @slorello89 Hope you had a good Thanksgiving.  Can we get support for `.StartsWith("vatore")` `vatore*` / `.EndsWith("vatore")` `*vatore`, and `.Contains("vatore")` `*vatore*` now that wildcard support has been added to RediSearch?

As in #244, we start to want different logic out of the same `.Contains()` method, and how do we manage that going forward?  Can it be contextual enough to overload the `.Contains()`, or should there be a new unambiguous methods to separate out the logic? `.ContainsWildcard()` for #264, and `.ContainsSearch()` for #244 ?

**Comment by VagyokC4** [comment]
Hey @slorello89.  Hope all is well.  Any updates as to when we can see these new filters implemented?
I'm desperately missing the `x=> x.StringProperty.Contains("needle")` filter, that would translation into the new `*needle*` filter.

**Comment by VagyokC4** [comment]
> Yep @VagyokC4 - there's a lot in v2.6.1 that I want to look at adding (it also allows you to index arrays of numbers, geo's, and full text search)

Hi @slorello89.  Any movement on this feature?  I'm finding myself more and more wanting to do a .StartWith(), .EndsWith() and .Contains() query.

**Comment by slorello89** [comment]
Hey @VagyokC4 - it's on my todo list - don't have an ETA yet.

**Comment by VagyokC4** [comment]
Woohoo!!!
