### ISSUE TITLE
GroupBy + Count

### ISSUE THREAD

**Issue by dstoyanoff** [redis/redis-om-dotnet#265]
Hello team,
I have recently started using Redis Stack with the OM Dotnet library, but I having some troubles achieving a group + count result.

I have a collection of sport events. Each, among other properties, has `SportCode` and `Status`. What I am trying to achieve is to first group all items by `SportCode` and then execute 2 counts - 1 unconditional count of all records within a group and one conditional count of the events whose status is equal to IN_PROGRESS.

This sort of aggregations are described in the documentation using an example with a SUM, where the return type is `GroupedAggregationSet<TEntity>`. Using `COUNT` however returns an int instead.

```
 var grouped = _cacheAggregation.GroupBy(x => x.RecordShell.SportCode).Count();
```

Is this a bug or am I missing something?

**Comment by slorello89** [comment]
`Count` is a native extension of IEnumerable that reduces the whole enumerable to a single integer with a count, use `CountGroupMembers`, that should do what you're looking for - the output will be stored at the `COUNT` key.

**Comment by dstoyanoff** [comment]
Thanks, this is a nice one. Is there a plan to support conditional count? On the above example, I need to get all groups, but in addition count how many events in a group have a status of IN_PROGRESS, which doesn't seem to be possible with `CountGroupMembers`

**Comment by slorello89** [comment]
You'd have to filter it ahead of time using a Where/Filter

**Comment by slorello89** [comment]
Closing this out as I think the questions posed are answered
