### ISSUE TITLE
when using document storage type of hash, nested array of objects (not primitives) are stored with a "." in the property, but never looked up during load 

### ISSUE THREAD

**Issue by rajasekarshanmugam** [redis/redis-om-dotnet#267]
When the class is decorated with storage type "Hash" and if the class has a list of objects (not primitives), it gets  stored in redis with an extra "." in the property name. however, if we use the find APIs and deserialize, the nested collection returns empty (since property with . is never looked up).

Eg. consider the below record definitions.

```
[Document(StorageType = StorageType.Hash, Prefixes = new[] { "case" })]
public record Case([property: RedisIdField]string Id, string Title, List<CaseHistory> History);
public record CaseHistory(string Version, string Note);
```

A case object successfully saves along with history, but on findxxx API, History will always return empty/null.

Full test program is attached. Please rename to cs. Expected count will be 2, however, output will be empty.

Using JSON storage type will work, however, for our use case we will need the Hash type to work.

Lines that seem to cause the issue - \redis-om-dotnet\src\Redis.OM\RedisObjectHandler.cs

```
                    var entries = hash.Where(x => x.Key.StartsWith($"{propertyName}["))
                        .ToDictionary(x => x.Key, x => x.Value);
                    var innerType = type.GetGenericArguments().SingleOrDefault();
```

entries will be empty as the property starts with "propertyName.[" and not "propertyName[".
it never reaches the else part as only primitives are read and no complex types.

[Program.HashRepro.cs.txt](https://github.com/redis/redis-om-dotnet/files/10139026/Program.HashRepro.cs.txt)

**Comment by slorello89** [comment]
Hi @rajasekarshanmugam - thanks for writing in, I would highly recommend using JSON if you are handling any sort of collections with Redis OM, Hashes are only meant for very flat-objects, and the conventions around storage of Hashes break down pretty quickly when you get into the storage of and querying of arrays. IIRC the case you're encountering here (where your model as an array-like collection of objects, is not something that's fully fleshed out in the hash-parser - it can handle arrays of scalars, but I don't think I ever wrote in the smarts to handle arrays of objects in a model.

**Comment by rajasekarshanmugam** [comment]
@slorello89 - Thank you so much for the note. Will move into JSON model for storage. Since write was supported, thought read when failed could be a bug.
