### ISSUE TITLE
Issue when specifying SELECT in Multiplexer

### ISSUE THREAD

**Issue by devbrian** [redis/redis-om-dotnet#268]
```
var muxer = ConnectionMultiplexer.Connect("localhost,$SELECT=");
builder.Services.AddSingleton(new RedisConnectionProvider(muxer));
```

When I attempt to specify a SELECT clause in the Multiplexer, there seems to be an issue inside redis SE

```
07:20:37.050 [0 172.17.0.1:60112] "GET" "__Booksleeve_TieBreak"
07:20:37.050 [0 172.17.0.1:60112] "ECHO" "\xfc;\xfb\xae\xb6\x1e\xc4C\x8b8\x8e\x12\x1d\xaa\xb1\xce"
07:20:37.051 [0 172.17.0.1:60112] "INFO" "replication"
07:20:37.228 [0 172.17.0.1:60126] "AUTH" "(redacted)"
07:20:37.229 [0 172.17.0.1:60126] "CLIENT" "SETNAME" "instance-1(SE.Redis-v2.6.70.49541)"
07:20:37.229 [0 172.17.0.1:60126] "INFO" "replication"
07:20:37.229 [0 172.17.0.1:60126] "INFO" "server"
```

This is spammed over and over again, however, if I remove `$SELECT=` from the Multiplexer argument, my application runs fine.

**Comment by slorello89** [comment]
@devbrian - remind me - you were trying to run a bunch of Inserts with timeouts right?

**Comment by slorello89** [comment]
This is a SE.Redis issue - follow StackExchange/StackExchange.Redis#2321 for eventual resolution.

**Comment by slorello89** [comment]
FYI @devbrian - looks like the PR for this issue has been merged so if it's still relevant to you, it should be fixed in the next release.
