### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by FatuityCookie** [redis/redis-om-dotnet#27]
StackExchange.Redis.RedisServerException:“ERR unknown command `FT.CREATE`, with args beginning with: `customer-idx`, `ON`, `Json`, `PREFIX`, `1`, `Redis.OM.Test.ConsoleApp.Program+Customer:`, `SCHEMA`, `$.FirstName`, `AS`, `FirstN`, ”

**Comment by FatuityCookie** [comment]
redis version i can use ?

**Comment by MayueCif** [comment]
不是redis版本问题，需要安装redisearch module

**Comment by MayueCif** [comment]
> redis version i can use ?

不是redis版本问题，需要安装redisearch module

**Comment by slorello89** [comment]
As @MayueCif said - you need to have the RediSearch module active to use the indexing/searching features of this library. To test it out I would suggest using the RedisMod docker image (as that will allow you to use everything feature of this library):

`docker run -p 6379:6379 redislabs/redismod`

As I think the question has been answered I'm going to close this issue. Feel free to reopen if this didn't sufficiently answer your question - Thanks!
