### ISSUE TITLE
Bulk Operations batch

### ISSUE THREAD

**Issue by Jeevananthan-23** [redis/redis-om-dotnet#274]
hi @slorello89, I would like to work on this enhancement. As I already added a batch by #246 
Few items for clarification:
- **InsertMany** which is already added but anyway this function is `Async` so I should refactor and add a `Sync` function for the bulk insert operation -  please add your points.
-  **` WhenKey`** - should be part of the bulk operation?
- **UpdateMany** - as you mentioned above this function should check for the snapshot to get diff and update the record accordingly.
- **DelMany** - uses `Unlink` to remove the enumerated item.(TC: O(N)) iterator into each key and take a round trip also expensive --> adding your suggestion.
- **All the bulk operations should have `Sync` & `Async` methods?**

_Originally posted by @Jeevananthan-23 in https://github.com/redis/redis-om-dotnet/issues/261#issuecomment-1350962472_

**Comment by slorello89** [comment]
I can see the utility of a Bulk deletion. Update Many is already fulfilled by `Save` and `SaveAsync`. I wouldn't say that all of these operations necessarily should be sync & async; sync is going to be pretty inefficient (just like `Save` is) because it needs to make a round-trip to redis per item.

**Comment by Jeevananthan-23** [comment]
I agree with your point `Save` has already been fulfilled Update Many operation, and Bulk Delete also had the same issue round -a trip to Redis per item but resolved it by simple Redis command `UNLINK key [key]` interesting one 😎 . Submitted PR #278  take a look at it. I think adding UpdateMany will help because of the batch.
