### ISSUE TITLE
Issue with Contains in the latest version 0.4.0

### ISSUE THREAD

**Issue by GrigDourden** [redis/redis-om-dotnet#276]
Hello!

After last update I faced with issue in Contains().

Something like that works fine:
`var cacheDtos = collection.Where(x => x.Tags.Contains("test")).ToList();`

but when I use variable it throw exception "Called contains for a non-indexed property"
```
var tag = "test";
var cacheDtos = collection.Where(x => x.Tags.Contains(tag)).ToList();
```

Property Tags has necessary attribute 
    
```
    [Indexed]
    public List<string> Tags { get; set; }
```
I've tried to use another attribute Searchable, but it doesn't work too.

Thank you!

**Comment by slorello89** [comment]
Ugh, this must have been caused by #263 when I reordered the if/else-if's the closure from the variable is interpreted as a member expression so it's interpreting it weirdly. Will need to take a closer look.
