### ISSUE TITLE
Update doesn't work with DateTimeOffset

### ISSUE THREAD

**Issue by GrigDourden** [redis/redis-om-dotnet#280]
Hello!

I've updated one project from version 0.1.9 to the latest (and checked it on one before it). 
Note: version 0.1.9 works fine with DateTimeOffset

And faced that update function doesn't work wit DateTimeOffset. It throw exception 

'ERR Error running script (call to f_cbbf1c4fab5064f419e469cc51c563f8bf51e6fb): @user_script:13: trailing characters at line 1 column 6
Failed on EVALSHA cbbf1c4fab5064f419e469cc51c563f8bf51e6fb 1 ConsoleApp4.Customer:1 SET $.Date 12.11.2010 0:00:00'

I've tested it on clean project and it's easy to reproduce:

using ConsoleApp4;
using Redis.OM;

var provider = new RedisConnectionProvider(***********);
provider.Connection.CreateIndex(typeof(Customer));
var collection = provider.RedisCollection<Customer>();
var customer = new Customer()
{
   Id = 1, Date = new DateTime(2010, 11,11)
};
collection.Insert(customer);
var storedCustomer = collection.FirstOrDefault();
storedCustomer.Date = new DateTime(2010, 11, 12);
collection.Update(storedCustomer);

the tested class is

    [Document(StorageType = StorageType.Json)]
    public class Customer
    {
        [RedisIdField]
        public int Id { get; set; }
        [Indexed] public string FirstName { get; set; }
        public DateTimeOffset Date { get; set; }
    }

Could you help me, please?

**Comment by slorello89** [comment]
Hi @GrigDourden - sorry I missed this issue (think it fell through the cracks around the holiday) - it looks like the issue with going from 0.1.9 -> 0.4.1 is that now 0.4.1 is now trying to update it and not formatting the string correctly for it's JSON.SET. Need to look into why it's doing this.

**Comment by JayavardhaniKathika** [comment]
Hi @slorello89. Is there any update on this issue? Please let me know if there is a workaround for this issue that I can use in 0.4.1. Thanks!
