### ISSUE TITLE
Best practices and concerns for creating indexes

### ISSUE THREAD

**Issue by MohamadTahir** [redis/redis-om-dotnet#283]
Hello, I'm sorry if this isn't the proper place to ask this, but I couldn't find forms for .net Redis om.

Anyhow, as the title says, I am wondering what are the best practices and concerns for creating an index?

let me explain where my question comes from, I am deploying my API on a Kubernetes cluster which means I will have multiple instances running/starting at the same time which adds some concerns, for example, if you are using a SQL database you will have to make sure that only one migration is running at a time, you shouldn't allow multiple instances of your application to run migrations as this can lead to data corruption, so this is the source of my question, is it okay to have multiple instances running the Redis index creation?

**Comment by slorello89** [comment]
As long as they are all in sync (sending the same create command) it's fine to have multiple instances creating the index at the same time - the worst thing that would happen is that Redis will fail to create the index (as it's already been created) and simply return false from CreateIndex (which is just sugar coating an ignorable error)
