### ISSUE TITLE
Inconsistent results with Redis OM .NET vs CLI query / Node OM

### ISSUE THREAD

**Issue by paulers** [redis/redis-om-dotnet#288]
Finding inconsistencies between the .NET OM package, Node OM package and regular Redis CLI / Redis Insight. The following query:
`FT.SEARCH products "@VendorId:{6b11fdc8\\-d5f1\\-477a\\-997f\\-ebc2c1460fdb}" LIMIT 0 10 SORTBY Name DESC`
fails to execute in RedisOM .NET, but succeeds in RedisOM Node and in the CLI.

Here's the specific code which throws an exception:

```csharp
var query = new RedisQuery("products")
{
    SortBy = new RedisSortBy
    {
        Direction = sortDirection == "ASC" ? SortDirection.Ascending : SortDirection.Descending,
        Field = sortField
    },
    Limit = new SearchLimit
    {
        Offset = skip,
        Number = take
    }
};

string queryText = "\"@VendorId:{" + vendorId.ToString().Replace("-", "\\\\-") + "}\"";
if (vendorId.HasValue) query.QueryText = queryText;
if (fields?. Length > 0) query.Return = new ReturnFields(fields.ToList());

var result = await _redis.Connection.SearchAsync<Terminal>(query);
```

The error I'm getting is this:
`Syntax error at offset 1 near VendorId
Failed on FT.SEARCH terminals "@VendorId:{6b11fdc8\\-d5f1\\-477a\\-997f\\-ebc2c1460fdb}" LIMIT 0 10 SORTBY Name DESC`

The index is built with VendorId as a tag:
```csharp
[Indexed][Required] public Guid VendorId { get; set; }
```
Required tag is from `System.ComponentModel.DataAnnotations`, but that's not relevant.

When I copy the above query and toss it into RedisInsight's Workbench, it works just fine. Also Node's OM package runs the query successfully.

Using Redis.OM 0.4.1. RediSearch 20603 in the cloud.

**Comment by paulers** [comment]
I cloned this repository and added it as a project to my solution just so I could debug what is going on. Here is some more information:

The exception is thrown exactly at this line:
https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/RedisObjectHandler.cs#L60

The `hash` dictionary that comes in has only the names of the fields as keys, it does not have a '$', so it throws an exception.

**Comment by paulers** [comment]
Thanks for the explanation. I did see the difference in response while debugging. I'd like to use the `Select` statement to build the query, but I'm letting users define which fields they want to see. That Select needs to be built dynamically, hence the `Search<T>` being brought in instead. Could you recommend a way to accomplish the aforementioned scenario using RedisOM? `Search<T>` and `SearchAsync<T>` require a type to be passed in.

**Comment by slorello89** [comment]
@paulers if you change: https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/RedisObjectHandler.cs#L58

from

```cs
if (attr != null && attr.StorageType == StorageType.Json)
```

to

```cs
if (attr != null && attr.StorageType == StorageType.Json && hash.ContainsKey("$"))
```

does that fix the issue for you?

**Comment by paulers** [comment]
It does indeed. I found that Guid types are not deserialized correctly though. I updated line 407 in the SendToJson method and it's working correctly now:
```csharp 
if (type == typeof(string) || type == typeof(Guid) || type == typeof(GeoLoc) || type == typeof(DateTime) || type == typeof(DateTime?) || type == typeof(DateTimeOffset))
```

This does fix all the issues I had above for now. Thanks for the assist! Not sure if you want me to close this, or whether you wanna use this issue to track these updates?
