### ISSUE TITLE
No such property, Failed on FT.AGGREGATE

### ISSUE THREAD

**Issue by LeoInTrance** [redis/redis-om-dotnet#291]
Model
```
[Document(StorageType = StorageType.Json, Prefixes = new[] { nameof(AdvertisementModel) })]
public class AdvertisementModel
{
	[RedisIdField, Indexed]
	public string? InternalId { get; set; }

	[Indexed]
	public long Id { get; set; }

	[Indexed(Aggregatable = true)]
	public string? Name { get; set; }

	[Indexed(Sortable = true, Aggregatable = true)]
	public long Timestamp { get; set; }

	[Indexed(CascadeDepth = 1)]
	public VehicleModel Vehicle { get; set; }
}

public class VehicleModel
{
	[Indexed(Aggregatable = true)]
	public string Brand { get; set; }

	[Indexed(Aggregatable = true)]
	public string Model { get; set; }
}
```

Group
```
var advertisementAggregation = _redisConnectionProvider.AggregationSet<AdvertisementModel>();
var groups = advertisementAggregation.GroupBy(x => x.RecordShell.Vehicle.Brand).CountGroupMembers();

foreach (var group in groups)
....
```

Error occours on foreach loop
```
System.Exception
  HResult=0x80131500
  Message=No such property `Brand`
Failed on FT.AGGREGATE advertisementmodel-idx * GROUPBY 1 @Brand REDUCE COUNT 0 AS COUNT
  Source=Redis.OM
  StackTrace:
   at Redis.OM.RedisConnection.Execute(String command, String[] args)
   at Redis.OM.Aggregation.AggregationEnumerator`1.StartEnumeration()
   at PandoraRedisSearch.Core.Impl.RedisSearchService.Start() in 

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
RedisServerException: No such property `Brand`
```

I don´t know why i'm receiving this error, if i use the same code but aggregating with [Name] property on root object work as expected. 

![redis](https://user-images.githubusercontent.com/30814646/214375115-d073ffd4-3df7-4e8d-b1b8-f1b2c1b5e796.PNG)

**Comment by slorello89** [comment]
This sounds related to #289 - basically the correct proprety should be "Vehicle_Brand"

```cs
var groups = advertisementAggregation.GroupBy(x => x.RecordShell["Vehicle_Brand"]).CountGroupMembers();
```

should probably work? - but obviously you shouldn't have to do that - it's not constructing the correct member names.

**Comment by LeoInTrance** [comment]
> This sounds related to #289 - basically the correct proprety should be "Vehicle_Brand"
> 
> ```cs
> var groups = advertisementAggregation.GroupBy(x => x.RecordShell["Vehicle_Brand"]).CountGroupMembers();
> ```
> 
> should probably work? - but obviously you shouldn't have to do that - it's not constructing the correct member names.

Thanks for the answer but with this code im getting a compilation error on x.RecordShell["Vehicle_Brand"]

```
Error	CS0021	Cannot apply indexing with [] to an expression of type 'AdvertisementModel'
```

**Comment by slorello89** [comment]
sorry `x["Vehicle_Brand"]`

**Comment by LeoInTrance** [comment]
> sorry `x["Vehicle_Brand"]`

I tried that before your answer, work like a charm!

You are a God, thank you so much!

**Comment by slorello89** [comment]
Glad to hear it worked, let's keep this open as it's a legit bug, this should be resolving to the correct member name as defined in the model.
