### ISSUE TITLE
change database number 

### ISSUE THREAD

**Issue by imansafari1991** [redis/redis-om-dotnet#292]
Hi
Can I change the database number when I want to connect to Redis?
For example, Redissearch connects to db0 by default; I want to connect to db1.
Do you know how I can do that?

**Comment by slorello89** [comment]
Technically the path in the redis-uri is the db number (redis://host:port/dbNum)

But using numbered DBs is considered an anti-pattern, and RediSearch will not support anything but db0 (it will just fail)

**Comment by soroshsabz** [comment]
ITNOA

@slorello89 why numbered DBs is anti pattern?

**Comment by slorello89** [comment]
Hi @soroshsabz,

Numbered databases in Redis is an original feature. It's purpose was to allow developers to isolate parts of the keyspace for different applications. This can lead to the false perception that the keyspaces are truly isolated, and that the separate databases have their own resources (both of which are false in the Redis internals). Salvatore (the creator of Redis) famously describes numbered databases in Redis as his biggest design regret when building Redis.

If you truly want to isolate your keyspace, use a different Redis instance altogether.
