### ISSUE TITLE
Problem with saving arrays of primitives to Redis

### ISSUE THREAD

**Issue by Zlejsi** [redis/redis-om-dotnet#299]
I have different problems with saving arrays of primitives to Redis.

https://github.com/Zlejsi/TestRedisOM.git - branch Arrays

I this repo I commented error messages and strange behaviors when inserting and updateting objects with arrays in it.

**Comment by zulander1** [comment]
I've looked at it and spent some time and thought it was a bug, but it's not; if you consider this, the results will be 1, since the hash for the comparer is the same for all object in the list...  
```
var a = JArray.FromObject(new List<string>
    {
        "1",
        "1",
        "1",
        "1",
    });

var b = JArray.FromObject(new List<string>
    {
        "2",
        "2",
        "2",
        "2",
    });

var diffab = a.Except(b, new JTokenEqualityComparer());
```

However if you have a distinct value in the array, you should not experience the this problem;
```
var c = JArray.FromObject(new List<string>
    {
        "1",
        "2",
        "3",
        "4",
    });

var d = JArray.FromObject(new List<string>
    {
        "2",
        "6",
        "7",
        "8",
    });

var diffab = c.Except(d, new JTokenEqualityComparer());
```

**Comment by Zlejsi** [comment]
I know that with distinct values, there is no problem. 
But when I save 4 values in array I expect 4 values when I load object from redis not just 1 value because 4 values was same.
And in my example there was a wierd issue when I save 5 "1", save clean and save 5 "2" in redis was saved "1","1","1","1","2".

**Comment by zulander1** [comment]
@Zlejsi, behind the scene, it's calling distinct which is causing this behaviour

**Comment by slorello89** [comment]
My first instinct here is to tell you to use JSON instead of a hash - as hashes do not do a great job of managing collections in the first place - but realistically here this appears to be an issue with how the object handler is interrogating the object, so I think it's something we should be able to fix.
