### ISSUE TITLE
[Question] Is get/set thread safe?

### ISSUE THREAD

**Issue by ShuiRuTian** [redis/redis-om-dotnet#303]
Summary:

Do I need a lock(like execute "SETNX" on redis) to make sure it's thread safe to add or remove the collection?

Background:

I use this lib and redis as a simple and fast database. And I create a asp.net program to CURD the data. So when there are multi requests at almost the same time(.i.e, multi threads may want to change the data meanwhile), do I need some lock to make sure the data will not race?

What I have done:

I read the document, but it seems this part is not mentioned.

**Comment by ShuiRuTian** [comment]
Thanks a lot for the quick and detailed response!

Still wander something about concurrent write:

Redis is single threaded, so it is atomically to write into it, but the `RedisCollection` is not thread-safe, so I still need some synchronization to make sure the collection is not broken, right?

**Comment by VagyokC4** [comment]
@ShuiRuTian Perhaps you are looking for something like this [RedLock](https://redis.com/redis-best-practices/communication-patterns/redlock/)?  This will allow you to isolate in your code any process that needs this thread-safeness regardless if your final destination is writing to Redis or not.  In a multi-threaded, micro-service application, it's almost a must have. to slow down any race conditions.

**Comment by ShuiRuTian** [comment]
@VagyokC4 Thanks, I will have a try. Really appreciate it.
