### ISSUE TITLE
Unknown separator type when using where in particular way

### ISSUE THREAD

**Issue by imansafari1991** [redis/redis-om-dotnet#304]
Hi there,

I have a redis collection, I want to write where like regular Linq:
`
var roomBoxes = RedisConnectionProvider.RedisCollection<RoomBoxCacheDto>();
roomBoxes = roomBoxes.Where(p => p.PersonCapacity+ p.ExtraPersonCapacity >= roomFilter.PersonCount.Value);
`
but it throws an "Unknown separator type" exception when I want to use .ToList() .
I tried to use an aggregation set for solving this issue and it worked, but I have many filters in my search that I don't need to use an aggregation set.

How can I write this query on rediscollection?

Thank you

**Comment by VagyokC4** [comment]
@imansafari1991 There may be other answers out there, but the way I would do this would be to create an indexed computed property on your model and then query that.

i.e. `public int TotalCapacity => PersonCapacity+ExtraPersonCapacity;`
Then query like you are expecting, just against the computed field `Where(p=>p.TotalCapacity <= roomFilter.PersonCount.Value)`

**Comment by imansafari1991** [comment]
What a great trick, this worked for me.
Thank you so much @VagyokC4

**Comment by slorello89** [comment]
Either a computed field like @VagyokC4 points out, or an [Aggregation](https://developer.redis.com/develop/dotnet/redis-om-dotnet/aggregations/apply-functions) with a filter would do the trick.

**Comment by slorello89** [comment]
Going to close this out to tidy up :)
