### ISSUE TITLE
Exception encountered while trying to save State in RedisCollection.FindById

### ISSUE THREAD

**Issue by AlexanderAnatolich** [redis/redis-om-dotnet#308]
Steps for reproducing:
1. Use redis stack in docker.
2. Use the latest Redis.OM (0.4.1) with .Net 7
3. Create a model with several indexes.
4. Insert 4000+ entities in redis.
5. Receive Ids from redis 500+.
6. Get full payload in parallel.

Code example:

>List<long> dataIds = redisCollection.Where(condition).Select(it => it.Id).ToList();
>ConcurrentBag<MyModel> data = new ConcurrentBag<MyModel>();
>var getAction = new System.Threading.Tasks.Dataflow.ActionBlock<long>((id) =>
>{
>var payload = redisCollection.FindById(id.ToString());
> data.Add(payload);
>}, new ExecutionDataflowBlockOptions()
>{
>CancellationToken = cancellationToken,
>MaxDegreeOfParallelism = Environment.ProcessorCount, //(My processes count is equal to 32.)
>});
>dataIds.ForEach(it => getAction.Post(it));
>getAction.Complete();
>await getAction.Completion;

Issue reproducing frequency is 2-5 in 10 attempts.

`
System.Exception: Exception encountered while trying to save State. This indicates a possible race condition. If you do not need to update, consider setting SaveState to false, otherwise, ensure collection is only enumerated on one thread at a time
 ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary'2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary'2.Add(TKey key, TValue value)
   at Redis.OM.Searching.RedisCollection'1.SaveToStateManager(String key, Object value)
   --- End of inner exception stack trace ---
   at Redis.OM.Searching.RedisCollection'1.SaveToStateManager(String key, Object value)
   at Redis.OM.Searching.RedisCollection'1.FindById(String id)
`

**Comment by slorello89** [comment]
Try initializing the `RedisCollection` with `saveState` set to `false`?

**Comment by slorello89** [comment]
This is the same issue as one of the key ones from #295, basically the async `FindByIdAsync` methods are colliding with each other on different threads when accessing the Dictionary that stores all the snapshots/references enumerated by the collection. If you need to maintain the state the newly improved `FindByIdsAsync` in the forthcoming 0.4.2 should get the job done.

**Comment by AlexanderAnatolich** [comment]
> Try initializing the `RedisCollection` with `saveState` set to `false`?

What is `State`? In which cases do I need it? And in which I can skip it?

**Comment by AlexanderAnatolich** [comment]
Initializing the RedisCollection with saveState = false, resolve the problem.
