### ISSUE TITLE
[Nuget Package] Enable documentation on release

### ISSUE THREAD

**Issue by fluzionhanaj** [redis/redis-om-dotnet#311]
#### Problem:

When working with the nuget package navigating to the api or hovering on method does not include documentation of source code.

#### Example:

![image](https://user-images.githubusercontent.com/20613629/220125483-7ece4d79-51a9-47fb-b2fb-0ec7ac23f834.png)

On [source code](https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/Modeling/RedisIdFieldAttribute.cs) exists documentation for attribute 

#### Suggested solution:

Include attribute  ```<GenerateDocumentationFile>True</GenerateDocumentationFile>``` on csproj file.

**Comment by slorello89** [comment]
Weird, I thought this was done already - looks like I set it up for the Debug NuGet package 😆. Thanks for pointing this out, We'll get this patched up :)
