### ISSUE TITLE
redisOM when desterilizing converts datetime (unix) to DateTime+00.00 (offset) 

### ISSUE THREAD

**Issue by MostafaSDesoky** [redis/redis-om-dotnet#312]
Hello
I'm using RedisOM with .Net 7 it works really fine but I had this only issue when retrieving DateTime from Redis it converts it to DateTime with offset +00.00 and this pops errors in my frontend

**Comment by slorello89** [comment]
As of 0.4.2 you'll be able to set your TimeZone with the `RedisSerializationSettings` introduced in #294 - so I think this should be solved? Going to close - Feel free to reopen if that doesn't get you what you need.

**Comment by MostafaSDesoky** [comment]
I just wanted to know where will 0.4.2 be released ?
