### ISSUE TITLE
Incompatible with NodaTime due to lack of ability to add-to Json Serializer Settings

### ISSUE THREAD

**Issue by Twinki14** [redis/redis-om-dotnet#313]
NodaTime provides custom JsonConverters in separate packages so that their types can be serialized/deserialized to json.

Currently this framework is incompatible with NodaTime types, and any other libraries that provide such custom types, while we're unable to access the Serializer Settings this framework is using when serializing/deserializing.

We can't even add to the converters as it currently stands.

https://nodatime.org/3.1.x/userguide/serialization

```
{"@t":"2023-02-22T14:48:59.2134316Z","@mt":"Exception caught","@l":"Error","@x":"System.Text.Json.JsonException: Cannot convert value to NodaTime.AnnualDate\n ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.\n   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)\n   at System.Text.Json.Utf8JsonReader.GetString()\n   at NodaTime.Serialization.SystemTextJson.NodaPatternConverter`1.ReadJsonImpl(Utf8JsonReader& reader, JsonSerializerOptions options)\n   at NodaTime.Serialization.SystemTextJson.NodaConverterBase`1.Read(Utf8JsonReader& reader, Type objectType, JsonSerializerOptions options)\n   --- End of inner exception stack trace ---\n   at NodaTime.Serialization.SystemTextJson.NodaConverterBase`1.Read(Utf8JsonReader& reader, Type objectType, JsonSerializerOptions options)\n   at MidnightHaven.Redis.Documents.PassThroughConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /src/MidnightHaven.Redis/Documents/UserDocument.cs:line 13\n   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)\n   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)\n   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)\n   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)\n   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)\n   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)\n   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)\n   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)\n   at Redis.OM.RedisCommands.JsonGetAsync[T](IRedisConnection connection, String key, String[] paths)\n   at Redis.OM.RedisCommands.GetAsync[T](IRedisConnection connection, String keyName)\n   at Redis.OM.Searching.RedisCollection`1.FindByIdAsync(String id)\n   at MidnightHaven.Redis.Repositories.DocumentRepository`1.UpsertAsync(Nullable`1 documentId, Action`1 documentFunc)\n   at MidnightHaven.Chan.Services.Logic.DocumentService`1.UpsertAsync(Nullable`1 documentId, Action`1 documentFunc) in /src/MidnightHaven.Chan/Services/Logic/DocumentService.cs:line 61","EventId":{"Name":"LogErrorException"},"SourceContext":"MidnightHaven.Chan.Services.Logic.UserService","ExceptionDetail":{"HResult":-2146233088,"Message":"Cannot convert value to NodaTime.AnnualDate","Source":"NodaTime.Serialization.SystemTextJson","TargetSite":"T Read(System.Text.Json.Utf8JsonReader ByRef, System.Type, System.Text.Json.JsonSerializerOptions)","InnerException":{"Type":"System.InvalidOperationException","HResult":-2146233079,"Message":"Cannot get the value of a token type 'StartObject' as a string.","Source":"System.Text.Json.Rethrowable","TargetSite":"Void ThrowInvalidOperationException_ExpectedString(System.Text.Json.JsonTokenType)"},"LineNumber":0,"BytePositionInLine":60,"Path":"$.AnnualBirthdate","Type":"System.Text.Json.JsonException"}}```

**Comment by slorello89** [comment]
Hi @Twinki14 - ATM we only support very limited interventions for serialization (well actually 0.4.1 doesn't support any but we're adding a global timezone in 0.4.2) I'm a bit confused as to why this would be an issue? The library is serializing and deserializing your datetimes to/from unix timestamps - so it shouldn't matter? what model/code are you you trying to use here exactly?

**Comment by Twinki14** [comment]
I'm using [AnnualDate](https://nodatime.org/2.1.x/api/NodaTime.AnnualDate.html) and [DateTimeZone ](https://nodatime.org/1.2.x/api/NodaTime.DateTimeZone.html) in my models, NodaTime offers quite a lot more than Microsoft does. However, for both of these types to deserialize / serialize the JsonSerializer used needs to be enhanced with their own JsonConverters that they ship in a different package specific to whatever Json framework (System.Text.Json, Newtonsoft, etc)

However in 0.4.1 I'm unable to access the JsonSerializers' options, and I can't enhance it with the NodaTime shipped JsonConverters, therefore I cannot use NodaTime types in my models that're used for RedisOM.

I noticed in 0.4.2 [there is a static JsonSerializerOptions](https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/RedisSerializationSettings.cs#L21) that I can actually access, so this is probably a mute issue after 0.4.2 is released.

**Comment by slorello89** [comment]
I'm not convinced that 0.4.2 will get you where you want to go without some dark reflection magic (you can set timezones but you can't muck with the enabled Serialization Options). I still don't quite understand what the issue is? Can you share your model and the code you're using to generate that error?

**Comment by Twinki14** [comment]
Create a model with a AnnualDate type, Insert that model into Redis, then attempt to Get that model from Redis.

I don't really know how much more straightforward I can be, NodaTime types require NodaTime provided JsonConverters to properly serialize or deserialize, without these JsonConverters you may get exceptions or wonkyness when properties in a model using NodaTime types are deserialized or serialized.

**Comment by Twinki14** [comment]
This was fixed with https://github.com/redis/redis-om-dotnet/pull/294

For example, using the System.Text.Json NodaTime package,
```csharp
RedisSerializationSettings.JsonSerializerOptions.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
```
