### ISSUE TITLE
Wrong Apply function query translation 

### ISSUE THREAD

**Issue by imansafari1991** [redis/redis-om-dotnet#317]
Hi there.
In a particular scenario, I want to write a conditional query like following LINQ query:
`await RoomDailyPriceRepository.Where(x => x.DateTime.Date >= checkin.Value.Date &&
                                                                            x.DateTime.Date < checkout.Value.Date)
                                                                .GroupBy(x => x.RoomId)
                                                                .Select(x => new
                                                                {
                                                                    roomId = x.Key,
                                                                    afterDiscountAmount = 
                                                                        x.Min(z => z.AfterDiscountAmount +
                                                                    (roomFilter.PersonCount.Value > z.PersonCapacity ? (roomFilter.PersonCount.Value - z.PersonCapacity) * stayingDays * z.ExtraPersonPriceBeforeDiscount : 0))
                                                                })`
That stayingDays is an integer, and ExtraPersonPriceBeforeDiscount is a double.
I want to sum `(roomFilter.PersonCount.Value - z.PersonCapacity) * stayingDays * z.ExtraPersonPriceBeforeDiscount ` when 
`roomFilter.PersonCount.Value > z.PersonCapacity` is true. 
I tried to use where in the aggregation set but got an error.
 So I tried using Apply function to specify that which one has this condition:
```cs 
roomDailySpecificAggregations = roomDailySpecificAggregations.Apply(
                    x => roomFilter.PersonCount.Value - x.RecordShell.PersonCapacity>0, "CalculateExtraPerson");
```
And use another apply function to establish the desired condition:
```cs 
roomDailySpecificAggregations = roomDailySpecificAggregations.Apply(x =>
    x.RecordShell.AfterDiscountAmount +x.Aggregations["CalculateExtraPerson"]* (roomFilter.PersonCount.Value - x.RecordShell.PersonCapacity) * stayingDays *
    x.RecordShell.ExtraPersonPriceBeforDiscount, "AfterDiscountAmountWithExtraPerson");
var roomDailySpecs =await roomDailySpecificAggregations.ToListAsync(cancellationToken);
```

And I got an error:
`System.Exception
Syntax error at offset 71 near 'CalculateExtraPerson'
Failed on FT.AGGREGATE roomDailySpecification-idx * APPLY 5 - @PersonCapacity > 0 AS CalculateExtraPerson APPLY @AfterDiscountAmount + @CalculateExtraPerson * 5 - @PersonCapacity * 3 @CalculateExtraPerson * 5 - @PersonCapacity * 3 * @ExtraPersonPriceBeforDiscount AS AfterDiscountAmountWithExtraPerson
   at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args)
   at Redis.OM.Aggregation.AggregationEnumerator`1.StartEnumerationAsync()
   at Redis.OM.Aggregation.AggregationEnumerator`1.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)`

After more investigation, I found the translated query is **Wrong**.

I tried to write a correct query in RedisSearch with "roomFilter.PersonCount.Value=5 and stayingDays=3":
` FT.AGGREGATE roomDailySpecification-idx * APPLY "5 - @PersonCapacity > 0" AS CalculateExtraPerson Apply "@CalculateExtraPerson*(5-@PersonCapacity)*3*@ExtraPersonPriceBeforDiscount" As AfterDiscountAmount2 `

And this returned value as I want.
So is there any solution in Redis.Om, for my scenario?

Thank you.

**Comment by slorello89** [comment]
@imansafari1991 - There's a lot going on here, but from what I can tell it's building the pipeline correctly (I don't have the exact bits you have so it's hard for me to make a like to like reconstruction of this pipeline). that translated query looks like it's exactly what I would expect based on your inputs (it drops a lot of quotes and parenthese but I think that's just how the exception formatting works). Can you share your model as well?

What I will tell you is that it sounds like you want to use `Filter`, which is basically a hybrid between a `Where` and a an `Apply` (you can run calculations and filter down on the results).

**Comment by slorello89** [comment]
@imansafari1991 - turns out that the expression parsing bit wasn't detecting a binary expression - which was causing it to push an extra translated expression onto operation stack. Opened a PR to fix.
