### ISSUE TITLE
series of issue on  linq select for Enum type

### ISSUE THREAD

**Issue by 29654761** [redis/redis-om-dotnet#327]
for v 0.4.2
1.
table.Where(...).Select(e=>e.state).FirstOrDefaultAsync()
throw exception   "Searches can only be performed on objects decorated with a RedisObjectDefinitionAttribute that specifies a particular index"
but success with FirstOrDefault

2.
table.Where(...).Select(e=>e.state).FirstOrDefault
throw  "The JSON value could not be converted to XXX"  if state is an Enum Type
can success with   table.Where(...).Select(e=>new{e.state} ).FirstOrDefault()

3.
can't index filed name converted by JsonPropertyName.  (can't search any rows)

**Comment by 29654761** [comment]
Create index using Prefixes missing ":"
 It's lead to search out raws from other tables witch names same prefixes .

**Comment by zulander1** [comment]
Can you provide an example?

**Comment by slorello89** [comment]
Possibly solved by #363
