### ISSUE TITLE
Create index with custom Prefixes missing ":"

### ISSUE THREAD

**Issue by 29654761** [redis/redis-om-dotnet#329]
Create index with custom Prefixes missing ":" 
It's lead to search out rows from other tables witch names same Prefixes key.
If add ":" in DocumentAttribute.Prefixes , this will be the key format like key::id (double ":")

**Comment by slorello89** [comment]
Hi @29654761 - that's by design, the typical namespace pattern in Redis is divided by a single `:`, the Prefix is used for two things 

1. Scoping the domain of the index (so any keys that start with the prefix are indexed)
2. When the keynames are generated at insertion by Redis OM, it DOES add an `:` between the prefix and the Id.

Not sure what the general purpose of having a double `:` is? If it's really needed, you can always add it to the prefix.

**Comment by 29654761** [comment]
> Hi @29654761 - that's by design, the typical namespace pattern in Redis is divided by a single `:`, the Prefix is used for two things
> 
> 1. Scoping the domain of the index (so any keys that start with the prefix are indexed)
> 2. When the keynames are generated at insertion by Redis OM, it DOES add an `:` between the prefix and the Id.
> 
> Not sure what the general purpose of having a double `:` is? If it's really needed, you can always add it to the prefix.

The problem is:  
add colon to DocumentAttribute.Prefixes, The key will be key:::id.
If don't add colon to DocumentAttribute.Prefixes, The index will no colon, it lead to search out wrong results

**Comment by slorello89** [comment]
@29654761 Can you provide a more concrete example of this? I'm having a hard time groking what you're talking about here or why there would be an issue - your prefix should just be the prefix - it's not a required field because Redis OM will just use whatever the fully-qualified class-name is without a prefix, and if you do add a prefix - then it will just use that, and when it creates the key - prepend a colon to the Id that it uses.

**Comment by 29654761** [comment]
> @29654761 Can you provide a more concrete example of this? I'm having a hard time groking what you're talking about here or why there would be an issue - your prefix should just be the prefix - it's not a required field because Redis OM will just use whatever the fully-qualified class-name is without a prefix, and if you do add a prefix - then it will just use that, and when it creates the key - prepend a colon to the Id that it uses.

HI @slorello89 
Sorry for my poor English.
for example:
There are two tables:
```code
[Document(StorageType = StorageType.Json, Prefixes = new[] { "persion" })]
public class Persion
{
        [RedisIdField]
        public Ulid id { get; set; }
        [Indexed]
        public string name { get; set; }
        ...
}

[Document(StorageType = StorageType.Json, Prefixes = new[] { "persion_man" })]
public class PersionMan
{
        [RedisIdField]
        public Ulid id { get; set; }
        [Indexed]
        public string name { get; set; }
        ...
}
```
Now I wan to search in table "persion_man":

```code
var table=redis.RedisCollection<PersionMan>();
await table.FirstOrDefaultAsync(e=>e.name=="John"); 
```
but I search out the row in table "persion"


Another way If I change the prefixes
```code
[Document(StorageType = StorageType.Json, Prefixes = new[] { "persion:" })]
public class Persion

[Document(StorageType = StorageType.Json, Prefixes = new[] { "persion_man:" })]
public class PersionMan
```
It can get correct rows, but the key insert into redis wiil be like this:
```code
persion::{id}
```

**Comment by slorello89** [comment]
@29654761 - I do think the library is doing the right thing here. The default behavior (if you don't have a prefix) is to append a `:` to the end of the string. But in this case you are supplying the prefix, so collisions need to be managed on your applications end. It's a little weird that it adds the extra `:` at insertion if you add the `:` but it looks like everything still works as far as I can tell (seems all the sets and gets still work appropriately).

The change you are suggesting would be a breaking change so not sure we want to integrate it.

Hope this helps!

**Comment by SMAH1** [comment]
Hi
Why is it not mentioned in the documentation that "prefix one" should not be a subset of "prefix other"?

> @29654761 - I do think the library is doing the right thing here. The default behavior (if you don't have a prefix) is to append a `:` to the end of the string. But in this case you are supplying the prefix, so collisions need to be managed on your applications end. It's a little weird that it adds the extra `:` at insertion if you add the `:` but it looks like everything still works as far as I can tell (seems all the sets and gets still work appropriately).
> 
> The change you are suggesting would be a breaking change so not sure we want to integrate it.
> 
> Hope this helps!

Hi
OK. But why is it not mentioned in the documentation that "prefix one" should not be a subset of "prefix other"?
This is confusing.
