### ISSUE TITLE
How to remove z in Datetime when deserializing 

### ISSUE THREAD

**Issue by MostafaSDesoky** [redis/redis-om-dotnet#335]
Hello
I had this issue that datetime have the offset +02.00 when deserializing but I upgraded to 0.4.2 The offset removed but it had been replaced with z in the datetime which the front also converts it to local time from utc so he add offset to the time.

how can I remove the z when deserializing to prevent this issue ?

**Comment by MostafaSDesoky** [comment]
Something like DateTime.SpecifyKind(item.DateTime, DateTimeKind.Unspecified)
fixs the problem but I can't foreach for every record in a large table when getting it
that would be a headache for  the server

**Comment by slorello89** [comment]
So like @zulander1 points out the date-times are converted to/from longs when being stored in Redis - be curious to see what you mean (we provide the ability to set a timezone now for you application - may be something that needs to get more granular).

**Comment by slorello89** [comment]
Going to close this out for now (I think 0.4.2's timezone setting capabilities should have resolved this) if not feel free to reopen with something that I can reproduce with :) - thanks!
