### ISSUE TITLE
Enhancement: Add support for "vector similarity" search

### ISSUE THREAD

**Issue by p-ob** [redis/redis-om-dotnet#342]
## Summary

Similar to the recently added Java / Spring support for vector search, it would be awesome to see a similar feature added for .NET developers.

## Resources
* [RedisStack Vector Similarity](https://redis.io/docs/stack/search/reference/vectors/)
* [Spring OM support PR](https://github.com/redis/redis-om-spring/pull/185)

**Comment by slorello89** [comment]
@bsbodden is already trying to peer-pressure me into adding it - we'll see :)
