### ISSUE TITLE
Error, when using multiple where clause against aggregation set sequentially

### ISSUE THREAD

**Issue by imansafari1991** [redis/redis-om-dotnet#345]
I've got an error when using multiple where clause against aggregation set as follows:
```        
 customerAggregations = customerAggregations.Where(x => x.RecordShell.FirstName == "James");
 customerAggregations = customerAggregations.Where(x => x.RecordShell.LastName == "Bond");
 var res = customerAggregations.Where(x => x.RecordShell.Age > 10).ToList(); 
```
The error was: `System.IndexOutOfRangeException: 'Index was outside the bounds of the array.`
I tried to inspect the translated query; I saw the following query:
`FT.AGGREGATE Customer-idx "@FirstName:{James}" FILTER "@LastName == 'Bond'" FILTER "@Age > 10"` 
I expected `where` clauses supposed to be translated as `query`, not `Filter`.
After tracing the source code, I discovered all of the `where` clauses translate to `Filter` except the First one: 
[`https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/Common/ExpressionTranslator.cs`](url)
Why `where` clause should be changed to `Filter`? According to [https://redis.io/docs/stack/search/reference/aggregations/](url) they have different definitions.

It is a repetitive scenario in that we have to use a sequence of `where` clauses; I tried to change it in my forked project and open a pr.
#344

**Comment by slorello89** [comment]
What you are describing is actually the way it was originally intended to behave (the first where clause would be the query and each subsequent one + filter would be the filter). This is probably out-moded now and should be updated similarly to how we did it elsewhere to resolve #78

**Comment by slorello89** [comment]
Finished by #344
