### ISSUE TITLE
[Question] Strange prefix in JSON indexing

### ISSUE THREAD

**Issue by AndersenGans** [redis/redis-om-dotnet#347]
https://github.com/redis/redis-om-dotnet/blob/dc2e33e667f0bb458b1c0f4a5432314f153fc2b4/src/Redis.OM/Modeling/RedisSchemaField.cs#L72
Guys, could u please explain me what was a purpose when u were doing such a thing *$"{pathPrefix}{attr.PropertyName}{pathPrefix}"*? I would understand if u use pathPostFix in both places, but when I see '$.key$.' as index identifier I have no idea what to do. Do u suggest to and '$.' as ending to each and every property of my documents I want to index eventually?

**Comment by slorello89** [comment]
Can you provide a concrete example where this is causing an issue for you? The paths are JSON paths to particular elements within the document. If the documented is nested within another, we construct a full path to that document e.g. `Person.Address.ZipCode` would translate to `$.Address.ZipCode` for the path, but would be aliased as `Address_ZipCode`

**Comment by slorello89** [comment]
Hi @AndersenGans thanks for pointing this out - yeah looks like something's wrong with how it's formatting the path when `PropertyName` is present in the `Indexed` attribute. Oddly this has never come up before (I don't think I know anyone using this property!).

**Comment by AndersenGans** [comment]
hey, @slorello89. yup, I needed this because in my c# code the properties were uppercased but I used `JsonPropertyNameAttribute` to specify that in JSON I want those properties' names to be like *property_name* thus I needed to provide `PropertyName` value as well in `IndexedAttribute` as the Redis.OM package doesn't now that I changed properties names eventually. so that's were issue appeared
