### ISSUE TITLE
How to dynamically build query with multiple conditions

### ISSUE THREAD

**Issue by askids** [redis/redis-om-dotnet#350]
hi,

Suppose I have a collection with client information with ClientId, ClientName, TaxId, Address, PhoneNo, Email. Now in UI, I have different input textboxes for each field. So user can enter any combination of inputs. In such case, how do I build the query dynamically, based on user input and then execute the consolidated where condition only once? All the samples that I see are showing individual where clauses being applied with fixed conditions, that are known upfront. However, in my usecase, there are multiple combination of conditions that can be applied, based on user input.

Thanks!

**Comment by slorello89** [comment]
See #157 - we added the ability to build the queries in stages last summer. basically you will set your collection equal to your collection with a new predicate:

```cs
collection = collection.Where(x=>x.Name=="steve");
collection = collection.WHere(x=>x.Age > 30);

var materialized = collection.ToList();
```

**Comment by askids** [comment]
Thanks @slorello89. So when we execute the 1st where condition, are we pulling any data from redis or is it not retrieved till the ToList is executed? We will be working with some 2M records in the collection. Hence just need to ensure that we are not pulling data for every where condition.

**Comment by slorello89** [comment]
Yeah, it will not materialize until you call ToList or enumerate it some other way (e.g. in a foreach loop). It's the enumerator that queries Redis, not the query's clauses.

**Comment by askids** [comment]
Great. Can I also use Take and Skip similar to LINQ to support pagination of results?

**Comment by slorello89** [comment]
Skip/take both work but it actually will automatically paginate as it enumerates FYI (obviously if you are presenting results in a UI you might not want to block the internal pagination it's doing).

**Comment by askids** [comment]
Right. Eventually results will be displayed in UI. 

Thanks a lot for answering all my queries. From the query sample in readme, it was not very evident that such multi stage query can be built.
