### ISSUE TITLE
Set custom alias for aggregation methods

### ISSUE THREAD

**Issue by imansafari1991** [redis/redis-om-dotnet#354]
Hi, there
In `RedisSearch`, you can set arbitrary alias for aggregation methods like AVG, SUM, ..., but in `Redis.OM` we can't change the name on the pipeline. Can we have this feature in `Redis.OM`?
Thanks.

**Comment by slorello89** [comment]
Hi @imansafari1991 - do you mean the results from reductions (e.g. `Sales_SUM`)?

**Comment by imansafari1991** [comment]
Sounds good. Thanks for the explanations.

**Comment by slorello89** [comment]
np - closing
