### ISSUE TITLE
Partial choice of entity is not working without the Id field

### ISSUE THREAD

**Issue by AlexanderAnatolich** [redis/redis-om-dotnet#358]
Versions:
.Net 6
Redis OM 0.5.0

Redis modules:
Redis search 2.4.16
Redis JSON 2.2.0

**Steps to reproduce:**
Create models, like that:

```
public class NecessarySubEntity {
      public SomeSubModel Field1 { get; set; }
      public SomeSubModel Field2 { get; set; }
}

public class SomeSubModel {
      public long Id { get; set; }
      public string Name { get; set; }
}

[Document(IndexName = "SomeModel", Prefixes = new[] { "SomeModel" }, StorageType = StorageType.Json)]
    public class SomeModel
    {
        [RedisIdField]
        [Indexed(Aggregatable = true, Sortable = true)]
        public long Id { get; set; }

        [Indexed(Aggregatable = true, Sortable = true)]
        public long? Timestamp { get; set; }

        [Indexed(CascadeDepth = 1)]
        public SomeSubModel Field1 { get; set; }
        
        [Indexed(CascadeDepth = 1)]
        public SomeSubModel Field2 { get; set; }
        
        .....
        
        [Indexed]
        public SomeStatus? SomeStatusId { get; set; }
}
```

**Insert 100+ entities to Redis.**

**Execute it the next way:**

```
public async Task<IList<NecessarySubEntity>> GetData(
             int? count,
             Expression<Func<SomeModel, bool>>? predicate = null)
        {
            try
            {
                var source = redisCollection;

                if (predicate != null)
                {
                    source = redisCollection.Where(predicate);
                }

                if (count.HasValue)
                {
                    source = source.Take(count.Value);
                }

                var resulted = source.Select(it => new NecessarySubEntity
                {
                    Field1 = it.Field1 ,
                    Field2 = it.Field2 
                });

               // ToList or ToListAsync doesn't matter
                var result = await resulted.ToListAsync();

                return result;
}
```
**Actual result:**
result is empty

**Expected result:**
result has a list of the values from Redis.

**Comments:**

It start working when I added the Id field to `NecessarySubEntity`, even though I do not select it.
I mean:
```
var resulted = source.Select(it => new NecessarySubEntity
                {
                    Field1 = it.Field1 ,
                    Field2 = it.Field2 
                });
```
OR
```
var resulted = source.Select(it => new NecessarySubEntity
                {
                    Id = it.Id,
                    Field1 = it.Field1 ,
                    Field2 = it.Field2 
                });
```
It works correctly when the `NecessarySubEntity` contains the Id filed.
Like:
```
public class NecessarySubEntity {
      public long Id { get; set; }
      public SomeSubModel Field1 { get; set; }
      public SomeSubModel Field2 { get; set; }
}
```

When I remove the Id field, it starts to return empty results.

**Comment by AlexanderAnatolich** [comment]
One more problem, returned subentity is empty, like:
```
[
  {
     Id == 1234,
     Field1 is null,
     Field2 is null
  },
  {
     Id == 12345,
     Field1 is null,
     Field2 is null
  }
]
```

**Comment by slorello89** [comment]
I see what's happening - 

Redis OM is trying to build the alias of the field rather than building out the path to the field when it's requested to pull back a sub-entity.

So when you execute one of those queries you get something like:

```
FT.SEARCH" "SomeModel" "(@Field2_Name:{bar})" "LIMIT" "0" "100" "RETURN" "2" "Field1" "Field2"
```

Those aren't valid paths (or aliases) in the return statement, so it's not pulling anything back. What it ought to do is request it with the path:

```
FT.SEARCH" "SomeModel" "(@Field2_Name:{bar})" "LIMIT" "0" "100" "RETURN" "2" "$.Field1" "$.Field2"
```

This also explains why the Id "works" with null results for the fields as it produces something analogous to:

```
FT.SEARCH" "SomeModel" "(@Field2_Name:{bar})" "LIMIT" "0" "100" "RETURN" "3" "Field1" "Field2" "Id"
```

Since Id is a known alias it will pull your Id back, and you'll get the parts of the document it was able to identify and pull back. However that doesn't change the fact that it doesn't know what to do with Field1 and Field2, so those are just ignored.

Will fix.

In the iterm the easy (but definitely less efficient) thing to do is just to materialize the query ahead of the select:

```cs
var res = (await collection.Where(x => x.Field2.Name == "bar").ToListAsync()).Select(x=>new NecessarySubEntity{Field1 = x.Field1, Field2 = x.Field2}).ToList();
```

**Comment by AlexanderAnatolich** [comment]
Hello, thanks for the quick reply.
Waiting for a new release.
About your idea, yep, you described how it's implemented now on our side.
But is not acceptable, because we have a very large object and the entire object's deserialization takes a lot of time.
