### ISSUE TITLE
Partial choice of entity to exactly object is not working

### ISSUE THREAD

**Issue by AlexanderAnatolich** [redis/redis-om-dotnet#371]
Parent issue: #358 
Versions:
.Net 6
Redis OM 0.5.1

Redis modules:
Redis search 2.4.16
Redis JSON 2.2.0

**Steps to reproduce:**
Create models, like that:

```
public class NecessarySubEntity {
      public SomeSubModel Field1 { get; set; }
      public SomeSubModel Field2 { get; set; }
}

public class SomeSubModel {
      public long Id { get; set; }
      public string Name { get; set; }
}

[Document(IndexName = "SomeModel", Prefixes = new[] { "SomeModel" }, StorageType = StorageType.Json)]
    public class SomeModel
    {
        [RedisIdField]
        [Indexed(Aggregatable = true, Sortable = true)]
        public long Id { get; set; }

        [Indexed(Aggregatable = true, Sortable = true)]
        public long? Timestamp { get; set; }

        [Indexed(CascadeDepth = 1)]
        public SomeSubModel Field1 { get; set; }
        
        [Indexed(CascadeDepth = 1)]
        public SomeSubModel Field2 { get; set; }
        
        .....
        
        [Indexed]
        public SomeStatus? SomeStatusId { get; set; }
}
```

**Insert any count of entities to Redis.**

**Execute it the next way:**

```
public async Task<IList<NecessarySubEntity>> GetData()
        {
            try
            {
                var resulted = redisCollection.Select(it => new NecessarySubEntity
                {
                    Field1 = it.Field1 ,
                    Field2 = it.Field2 
                });

               // ToList or ToListAsync doesn't matter
                var result = await resulted.ToListAsync();

                return result;
}
```
**Actual result:**
Receive an array with properties that have null values.

**Expected result:**
Receive an array with properties that have necessary values.

**Comments:**

It works when I select the necessary properties to anonymize the object.
I mean:
```
var resulted = source.Select(it => new
                {
                    Field1 = it.Field1 ,
                    Field2 = it.Field2 
                });
```
But when I'm selecting it to exactly object, I receive a null for the properties.
```
[
  {
     Field1 is null,
     Field2 is null
  },
  {
     Field1 is null,
     Field2 is null
  }
]

**Comment by slorello89** [comment]
At first brush this looked a lot like [this test](https://github.com/redis/redis-om-dotnet/blob/e3cff606536f1da5b57ff9fb6c26adf86eb22aab/test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs#LL1100C19-L1100C19)

However it appears that because it was using the same name for the field in the destination object as it was in the initial object, it isn't seeing the alias appropriately making the result fairly hard to pull back appropriately. Have #372 open to fix.
