### ISSUE TITLE
Can Redis.OM support GeoFilters on Aggregations ?

### ISSUE THREAD

**Issue by marlenehildebrand-eaton** [redis/redis-om-dotnet#374]
Hello,

Using the Redis CLI, it is possible to pass a GeoFilter as a parameter to an FT.AGGREGATE command like this :

`FT.AGGREGATE test-index "@Position:[6.6 46.5 20 km]"`

However, in redis.OM, GeoFilters only seem applicable to RedisCollections and not Aggregations. I have found this for Collections :

```
public static IRedisCollection<T> GeoFilter<T>(this IRedisCollection<T> source, Expression<Func<T, GeoLoc?>> expression, double lon, double lat, double radius, GeoLocDistanceUnit unit) where T : notnull
{
            RedisCollection<T> redisCollection = (RedisCollection<T>)source;
            MethodCallExpression expression2 = Expression.Call(null, GetMethodInfo<IRedisCollection<T>, Expression<Func<T, GeoLoc?>>, double, double, double, GeoLocDistanceUnit, IRedisCollection<T>>(new Func<IRedisCollection<T>, Expression<Func<T, GeoLoc?>>, double, double, double, GeoLocDistanceUnit, IRedisCollection<T>>(GeoFilter), source, expression, lon, lat, radius, unit), source.Expression, Expression.Quote(expression), Expression.Constant(lon), Expression.Constant(lat), Expression.Constant(radius), Expression.Constant(unit));
            return new RedisCollection<T>((RedisQueryProvider)source.Provider, expression2, source.StateManager, redisCollection.BooleanExpression, source.SaveState, source.ChunkSize);
}
```

But haven't found anything similar for Aggregations.

Is this feature planned anytime soon, or is there a way to apply GeoFilters to Aggregations that I'm missing out on ?

**Comment by slorello89** [comment]
You can accomplish something like this using the `geodistance` apply function and a filter, atm though there's no way to add a geo-query to the aggregation's main query.

**Comment by marlenehildebrand-eaton** [comment]
Hi @slorello89, thanks for the suggestion, it does indeed do the trick !

**Comment by slorello89** [comment]
Glad to hear it @marlenehildebrand-eaton - going to close this issue to tidy up.
