### ISSUE TITLE
Redis Cluster Support?

### ISSUE THREAD

**Issue by jkuehnemundt** [redis/redis-om-dotnet#381]
Does Redis OM also support Redis Cluster?
I only get data from one node and not from all nodes when I make a query.

**Comment by slorello89** [comment]
Yes it does, the client that it uses under the hood (StackExchange.Redis) will automatically discover the topography of your cluster, and it will JSON.SET/JSON.GET HSET/HGET to the appropriate node.

Querying an index is a single node operation to the client(its only meant to query one node) the server is responsible for fanning out the queries to the other nodes. If your cluster isn't configured to use the RSCoordinator - then the results will be limited to a single node.

**Comment by slorello89** [comment]
It's something to that effect.

**Comment by jkuehnemundt** [comment]
It works. Thank you very much for your help!
