### ISSUE TITLE
Duplicating child array of entities during update

### ISSUE THREAD

**Issue by htmlpk** [redis/redis-om-dotnet#383]
Versions:
.Net 7
Redis OM 0.5.2

Model:
```
 [Document(StorageType = StorageType.Json, Prefixes = new[] { "Lobby" })]
    public class Lobby : BaseGuidEntity
    {
        [Indexed]
        public GameType GameType { get; set; }

      [Indexed(CascadeDepth = 1)]
        public List<Player> Players { get; set; } = new List<Player>();
    }
```

 ```
public class BaseGuidEntity : IEntity<Guid>
    {
        [RedisIdField]
        [Indexed]
        public Guid Id { get; set; }
        [Indexed]
        public DateTime CreationDate { get; set; }

        public BaseGuidEntity()
        {
            Id = Guid.NewGuid();
            CreationDate = DateTime.Now;
        }
    }
```

 ``` 
public class Player:BaseGuidEntity
    {
        [Indexed]
        public long UserId { get; set; }

        [Indexed]
        public string? UserName { get; set; }

        [Indexed]
        public string? ConnectionId { get; set; }   
        
        [Indexed]
        public int Order { get; set; }
    }
```

Steps to reproduce:
1. Create the model of lobby with 1 player
2. Add 1 more player to the Players List and update model with UpdateAsync
```
public async Task<Lobby> Join(JoinLobbyViewModel model)
        {
            Lobby lobby = (await _lobbyRepository.GetByAsync(x => x.Id.Equals(Guid.Parse(model.GameId)))).FirstOrDefault();
            if (lobby == null)
            {
                throw new Exception("Game is not found");
            }
            Player player = new Player() { ConnectionId = model.ConnectionId, UserId = model.UserId, Order = lobby.Players.Count - 1, UserName = model.UserName };
            
            lobby.Players.Add(player);
            await _lobbyRepository.UpdateAsync(lobby);
            return lobby;
        }
```
Actual result:
3 Players presented in the Players List. After any update Player list duplicating himself with adding entity additional. 
Expected result:
2 Players presented in Players List. After each update Player list not duplicating himself and adding new single entity. 

It works fine with
 _repo = (RedisCollection<T>)provider.RedisCollection<T>(false) 
instead of 
_repo =(RedisCollection<T>)provider.RedisCollection<T>()

**Comment by slorello89** [comment]
Hi @htmlpk - looks like the issue here is that when Redis OM is building the diff, it is not accounting for the fact that the `CreationDate` is converted to a number in Redis (hence it's adding the extra record). Work around for now would be to set `saveState` to false when initializing `_lobbyRepository`, that will prevent it from preforming the diff.
