### ISSUE TITLE
Ambigous custom prefixes

### ISSUE THREAD

**Issue by nerg4l** [redis/redis-om-dotnet#384]
Custom prefixes can be ambiguous without any special character at the end.

```
[Document(StorageType = StorageType.Json, Prefixes = new[] { "customer" })]
public class Customer
{
    [Indexed] public string Data { get; set; }
}


[Document(StorageType = StorageType.Json, Prefixes = new[] { "customerDetail" })]
public class CustomerDetail
{
    [Indexed] public string Data { get; set; }
}
```

In the above case, all `CustomerDetail` will be indexed as `Customer`. A workaround is to add a `:` (colon) at the end. This will result in keys such as `customer::<id>` and `customerDetail::<id>`.

- When default prefixes are used, then a `:` (colon) is added to the full name of the type.
- When a custom prefix is defined, then the value is used as is.

https://github.com/redis/redis-om-dotnet/blob/71c21738a357792fb18ecbcee7b5a002f3576f25/src/Redis.OM/Modeling/RedisIndex.cs#L55-L64

**Comment by slorello89** [comment]
This has been a question we've received a [few times](https://github.com/redis/redis-om-dotnet/issues/329#issuecomment-1531904054). IMO the library is operating correctly and to make this change would be a break. However I think ultimately the correct work-around will be allowing folks to set these properties at run-time as well as in the pre-defined model definition.
