### ISSUE TITLE
Question: Setting the document prefix at run time

### ISSUE THREAD

**Issue by lefig** [redis/redis-om-dotnet#390]
Hi,

Firstly a big thank you for this project and for all the work that has gone in to it.

I have a brief query if I may...

If say we have an event driven store and wish to select a prefix at runtime based on event such as AccountCreated, AccountCredited etc. Is there a way of doing so.

Using the attribute [Document(IndexName = "book-idx", StorageType = StorageType.Json, Prefixes = new[] { "ru204:redis-om-dotnet:Book" })] doesn't look possible.

Thank you

Fig

**Comment by imansafari1991** [comment]
Hi @lefig 
You can change prefixes at runtime by `RedisIdField`. In my scenario, I wanted to have a prefix like this:
`RoomDailySpecification:{RoomId}:{DateTime}` 
 `RoomId` and `DateTime` are variables
I've created an index as follows:
``` 
[Document(IndexName = "roomDailySpecification-idx", StorageType = StorageType.Json, Prefixes = new[] { "RoomDailySpecification"}) ]
 public class RoomDailySpecificationCacheDto
    {

        [RedisIdField] public string Id => $"{RoomId}:{DateTime:yyyy-MM-dd}";
        [Indexed(Aggregatable = true,Sortable = true)]
        public long RoomId { get; set; }
        public DateTimeOffset DateTime { get; set; }
     }
I hope it can help you.

**Comment by lefig** [comment]
Hi @imansafari1991,

That is fabulous and thank you for saving me from struggling with this:)
