### ISSUE TITLE
newline question

### ISSUE THREAD

**Issue by sm1lewc** [redis/redis-om-dotnet#394]
[Document]
class A
{
  public string Note {get;set;}
}
var a=new A(){Note="ABC
DEF"}

Suppose an A is stored in redis with the Note value "ABC
DEF",
There are line feeds in the value
-----------
private readonly RedisCollection<A> _items;
private readonly RedisConnectionProvider _provider;
public PeopleController(RedisConnectionProvider provider)
{
    _provider = provider;
    _people = (RedisCollection<A>)provider.RedisCollection<A>();
}

public ActionResult Fun()
{
   await _items.Where(whereExpression).ToListAsync(); 
   //Error 
   //**System.Text.Json.JsonException: '0x0A' is invalid within a JSON string. The string should be correctly escaped.**
}

Is this a bug, or is there something wrong with my usage?

**Comment by slorello89** [comment]
Hi @sm1lewc  Can you reformat this so it's clearer what's going on here? idk what your expression looks like, and your indexed object doesn't look right (for one thing it's not indexed at all)

**Comment by sm1lewc** [comment]
An attribute is not indexed, and it is not queried, just stored.
The string value of this property has newlines, and then the data is not returned properly.

**Comment by slorello89** [comment]
Really not sure what to make of this without a reproduction.

**Comment by slorello89** [comment]
Hi @sm1lewc Going to close out to tidy up pending a - if you have a concrete reproduction, please feel free to reopen
