### ISSUE TITLE
feature classMap vs Attributes

### ISSUE THREAD

**Issue by auriou** [redis/redis-om-dotnet#396]
Is there a possibility to configure the classes without going through the attributes, but to configure them at the start of the application as the Mongodb driver does with its BsonClassMap or ModelBuilder class on EntityFramework?

````c#
BsonClassMap.RegisterClassMap<Person>(classMap =>
{
    classMap.MapMember(p => p.Name);
    classMap.MapMember(p => p.Age);
    classMap.MapMember(p => p.Hobbies);
});


 protected override void OnModelCreating(ModelBuilder modelBuilder)
{
     modelBuilder.Entity<Blog>()
         .Property(b => b.Url)
         .IsRequired();
}

**Comment by slorello89** [comment]
Duplicate of #242 / #196 - probably something we'll add eventually, but no immediate plans to do so.
