### ISSUE TITLE
When I am filtering with string field I got an error

### ISSUE THREAD

**Issue by AhmadKanaa** [redis/redis-om-dotnet#397]
When I am filtering with the string field may contain value and may not I get an error:

Syntax error at offset 109 near MarketplaceCategoryId
Failed on FT.SEARCH itemIdx ((@TenantId:{a4d874fea55ed10d9ad63a0c011f4e56|3670116537a59349fb9a3a0c5215838a}) (((-@MarketplaceCategoryId:{}) (-@TenantId:{a4d874fea55ed10d9ad63a0c011f4e56})) | ((@MarketplaceCategoryId:{}) (@TenantId:{a4d874fea55ed10d9ad63a0c011f4e56})))) LIMIT 0 0
System.Exception: Syntax error at offset 109 near MarketplaceCategoryId

the query:
query = query.Where(item =>
  tenantsIdsStr.Contains(item.TenantId) && (
  (item.MarketplaceCategoryId != x && item.TenantId != currentTenantIdStr) ||
  (item.MarketplaceCategoryId == x && item.TenantId == currentTenantIdStr)));
  
  
and when I write my query like this:
query = query.Where(item =>
                    tenantsIdsStr.Contains(item.TenantId) &&
                   ((!string.IsNullOrEmpty(item.MarketplaceCategoryId) && item.TenantId != currentTenantIdStr) ||
                    (string.IsNullOrEmpty(item.MarketplaceCategoryId) && item.TenantId == currentTenantIdStr))
                    );
  
 I got this error:
 Unable to parse method IsNullOrEmpty
System.InvalidOperationException: Unable to parse method IsNullOrEmpty

**Comment by VagyokC4** [comment]
Redis doesn't understand NULL in it's query, so you will need to "work around" this limitation.  For example, if you need to query if a property is NullOrEmpty, create a computed property that converts this to a bool.
```
public class Item
{
  public string MarketplaceCategoryId {get; set;}
  [Indexed] public bool HasMarketplaceCategoryId => !string.IsNullOrEmpty(MarketplaceCategoryId)
}
```
Now you can property query for this by checking your bool property.

You will also need to check for nulls on the query side and possibly build the query in stages.
```
query = query.Where(item =>tenantsIdsStr.Contains(item.TenantId));
if (currentTenantIdStr is not null) query = query.Where(item =>item.TenantId == currentTenantIdStr);
```

Hope this helps.

**Comment by zulander1** [comment]
I would suggest to use guide.empty. this would solve your problems

**Comment by AhmadKanaa** [comment]
@VagyokC4 Thanks for your suggestion...but unfortunately when I implemented I got an unexpected list
        query = query.Where(item =>
                tenantsIdsStr.Contains(item.TenantId) &&
                ((item.HasMarketplaceCategoryId == true && item.TenantId != currentTenantIdStr) ||
                (item.HasMarketplaceCategoryId == false && item.TenantId == currentTenantIdStr))
               );

**Comment by VagyokC4** [comment]
> Thanks for your suggestion...but unfortunately when I implemented I got an unexpected list
The only thing I see missing is the execution of the query.
```
var results = await query.ToListAsync();
```

Assuming that query works, everything else should be data.

**Comment by slorello89** [comment]
Unfortunately at this point, nullness is not something we can account for. `String.Empty` or `Guid.Empty` should work in your case. going to close this out.
