### ISSUE TITLE
Replace Moq with NSubsitute

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#404]
Moq 4.20.0 includes spyware.

See the following issues for details:

https://github.com/devlooped/SponsorLink/issues/17
[Will cause packages to be no-go in corporate  devlooped/SponsorLink#16](https://github.com/devlooped/SponsorLink/issues/16)
https://github.com/moq/moq/issues/1372
https://github.com/moq/moq/pull/1373

**Comment by imansafari1991** [comment]
I am ready for this replacement.
