### ISSUE TITLE
Remove dependencies from Newtonsoft.Json, Ulid please

### ISSUE THREAD

**Issue by pairbit** [redis/redis-om-dotnet#408]
1. I'm sure few people need a dependency on Newtonsoft.Json.  It doesn't matter why you use it, but you are wrong. 

2. Although Ulid is great, you are forcing it on me again. Remove Ulid from Redis.OM library and add Redis.OM.Ulid or something else.

**Comment by slorello89** [comment]
Hi @pairbit,

While I appreciate that you may not care for these two dependencies, I assure you they are quite vital to the normal operation of this library. The good news is that this is an open-source library available under an MIT license, so if you need to customize it to your usage, you are free to fork it and do so :).
