### ISSUE TITLE
Using protocol buffers with Redis OM .NET

### ISSUE THREAD

**Issue by goodstas** [redis/redis-om-dotnet#414]
Hello, i have .NET application. I want to use protocol buffers in my application and to save the received data as JSON in Redis and i want to use Redis OM to query this data.
The question is how i can deal with .proto file and the attributes like [Indexed] and [Searchable] which i need to declare on top of the properties of my C# class to query the JSON of my C# class with Redis OM.
How i can add these attributes to the code generated C# class that i receive after compiling .proto file with .NET compiler of proto files?

I hope  there is a solution for the described issue.
Thank you.

**Comment by slorello89** [comment]
Can you describe your workflow a little more to me? I'm assuming you are using some kind of codeanalyzer/autogenarator - the thing to do here would be to create a new analyzer/generator to insert the appropriate attributes in the appropriate spots.

**Comment by goodstas** [comment]
> Can you describe your workflow a little more to me? I'm assuming you are using some kind of codeanalyzer/autogenarator - the thing to do here would be to create a new analyzer/generator to insert the appropriate attributes in the appropriate spots.

@slorello89 , of course.
I have some proto file . 
`message PersonDTO  
{  
   int32 id = 1;  
   string name = 2;  
   repeated AddressDTO addresses = 3;  
}  
  
message AddressDTO  
{  
   int32 id = 1;  
   string fullAddress = 2;  
   string city = 3;  
}  `
I want to implement a server which receives from the client byte[] from RabbitMQ exchange which is serialized by using protocol buffers.
The server deserialize this byte[] to the appropriate C# class PersonDTO which is autogenerated by grpc.tools nuget from my proto file.

I would like to use the same autogenerated class to work with Redis OM.
For using this C# class with Redis OM,  the class's properties must be decorated with attributes like Indexed and Searchable according to [https://redis.io/docs/clients/om-clients/stack-dotnet/](https://redis.io/docs/clients/om-clients/stack-dotnet/)

I wonder how i can use autogenerated C# class from proto file to work with Redis OM.
Thank you.

**Comment by goodstas** [comment]
@slorello89 , do you have any ideas?
Thank you.

**Comment by slorello89** [comment]
Hi @goodstas - you would need to add a [source-generator](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) to do it for you.

**Comment by goodstas** [comment]
Thank u for the  idea @slorello89 .
May you describe the steps that this source generator should do.... 
Sorry but i don't see how this puzzle is solved. I have auto generated C# class from proto file and i need to decorate it's properties and the class definition itself.
Will it work (reading from Redis Stack) for the repeated field property of the class?
Because the repeated field property is generated only with getter by protocol buffers compiler.

**Comment by slorello89** [comment]
You would need to write your own code-analyzer/generator to do the dynamic insertion in the relevant spots.
