### ISSUE TITLE
Order by sortable field inside nested list.

### ISSUE THREAD

**Issue by PioneerOfProgramming** [redis/redis-om-dotnet#419]
Hello
I have this schema:
```

[Document(StorageType = StorageType.Json, Prefixes = new string[] { "product" }, IndexName = "product-idx")]
public class ProductCache
{
      [RedisIdField][Indexed] public required string Id { get; set; }
      [Searchable(Sortable = true)] public required string Name { get; set; }
      
     [Indexed(JsonPath = "$.Id")]
     [Indexed(JsonPath = "$.Sku")]
     [Indexed(JsonPath = "$.Price", Sortable = true)]
     public List<VariantCache> Variants { get; set; } = new List<VariantCache>();
  }
  
public class VariantCache
{
      [Indexed] public required string Id { get; set; }
      [Indexed] public string? Sku { get; set; }
      [Indexed(Sortable = true)] public double Price { get; set; }
}
```

I need to sort products by the price inside list of VariantCache
How we can do this?

I try this:
`query.OrderBy(p => p.Variants.Max(v=> v.Price))`
and this:
`query.OrderBy(p => p.Variants.Min(v=> v.Price))`
and this: 
`query.OrderBy(p => p.Variants.First(v=> v.Price))`
and this: 
`query.OrderBy(p => p.Variants.Select(v=> v.Price))`

**All the previous states didn't work and I got this error:**

Unable to cast object of type 'System.Linq.Expressions.MethodCallExpression2' to type 

> 'System.Linq.Expressions.MemberExpression'.
> ﻿System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.MethodCallExpression2' to type 'System.Linq.Expressions.MemberExpression'.

﻿
﻿Please, can you help me **URGENTLY**?

**Comment by slorello89** [comment]
What you are looking to do(use collection functions on a JSON array in an index) is not supported by Redis, hence Redis OM can't support those semantics. You can work around this limitation with smart properties:

 ```cs
var res = collection.OrderBy(x => x.MaxPrice).ToList();

Console.WriteLine(res.First());

[Document(StorageType = StorageType.Json, Prefixes = new string[] { "product" }, IndexName = "product-idx")]
public class ProductCache
{
    [RedisIdField][Indexed] public required string Id { get; set; }
    [Searchable(Sortable = true)] public required string Name { get; set; }

    [Indexed] public double? MaxPrice => Variants.Max(x => x.Price);
    [Indexed] public double? MinPrice => Variants.Min(x => x.Price);
      
    [Indexed(JsonPath = "$.Id")]
    [Indexed(JsonPath = "$.Sku")]
    [Indexed(JsonPath = "$.Price", Sortable = true)]
    public List<VariantCache> Variants { get; set; } = new List<VariantCache>();
}
  
public class VariantCache
{
    [Indexed] public required string Id { get; set; }
    [Indexed] public string? Sku { get; set; }
    [Indexed(Sortable = true)] public double Price { get; set; }
}
```

The downside of course is that this will lead to some denormilization.

**Comment by PioneerOfProgramming** [comment]
@slorello89 It's worked very well, thank alot.

**Comment by slorello89** [comment]
Great to hear @PioneerOfProgramming, closing.
