### ISSUE TITLE
Allow overriding JsonSerializer settings

### ISSUE THREAD

**Issue by goodstas** [redis/redis-om-dotnet#420]
Hi, @slorello89 .
I'm also looking for a way to define my custom JsonSerializerOptions. I'm working with NetTopologySuite library and the properties of my business objects include types like Point and Polygon of NetTopologySuite.
Currently i got an error while saving them in Redis.
So what can i do?
May be you just can add this line to your default JsonSerializerOptions : 
jsonSerializerOptions.Converters.Add(new NetTopologySuite.IO.Converters.GeoJsonConverterFactory())

I saw that there is an open issue for the same question : #266 and you wrote that you want to know if more people need it...

**Comment by slorello89** [comment]
Hi @goodstas - going to close this as a duplicate - but noted (I do want to add this feature).

**Comment by goodstas** [comment]
@slorello89 which one? the option to define custom JsonSerializerOptions? do you have time estimation to this?
thank you
