### ISSUE TITLE
UpdateAsync() doesnt provide Inputs for the lifetime cache

### ISSUE THREAD

**Issue by y-2-j** [redis/redis-om-dotnet#430]
Are there any plans to have this option available soon so that we can start using this for setting up custom lifetime while calling update async()

**Comment by granit1986** [comment]
I support. Can you fix this?

**Comment by granit1986** [comment]
@slorello89 Working incorrect

ERR value is not an integer or out of range
Failed on PEXPIRE EventData:12261312 7022807438,9542

**Comment by slorello89** [comment]
hmm @granit1986 - that's quite odd - PEXPIRE doesn't support fractional milliseconds (not to mention if we did there would be a cultural invariance issue in how they are being parsed in Redis OM). What TimeSpan are you using here, it looks like it might be to blame (though we should be correctly rounding off milliseconds here).
