### ISSUE TITLE
Redis.OM 0.6.1 has vulnerability warning for System.Drawing.Common 5.0.0

### ISSUE THREAD

**Issue by frostshoxx** [redis/redis-om-dotnet#434]
![image](https://github.com/redis/redis-om-dotnet/assets/567851/1e5d3ce7-b764-4b11-a6db-cf08b9993a55)

Are we using this library for anything? Can we just update to a new version or get rid of it?

**Comment by slorello89** [comment]
There's an old dependency on it through StackExchange.Redis IIRC, probably just need to bump the SE version.

**Comment by frostshoxx** [comment]
@slorello89 

I'm trying to pull the latest version of the forked main branch to my local machine, but it's giving me some error relating to pulling Redis.OM.Vectorizer

```
Git failed with a fatal error.
Git failed with a fatal error.
Downloading src/Redis.OM.Vectorizers.AllMiniLML6V2/Resources/model.onnx (91 MB)
Error downloading object: src/Redis.OM.Vectorizers.AllMiniLML6V2/Resources/model.onnx (4a64cee): Smudge error: Error downloading src/Redis.OM.Vectorizers.AllMiniLML6V2/Resources/model.onnx (4a64cee3d4134bbdc86eed96e1a660efec58975417204ecfcf134140edb6e0e2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'C:\Users\yoloslick\source\repos\redis-om-dotnet\.git\lfs\logs\20240214T163425.0505291.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: src/Redis.OM.Vectorizers.AllMiniLML6V2/Resources/model.onnx: smudge filter lfs failed 
```

Are we supposed to download them from some other ways?

Thank you!

**Comment by slorello89** [comment]
Hmm, the LFS records aren't even on the main branch - I think I'm going to have to clean that up. Check out without LFS and run fetch-models.sh to pull down the models needed for the vectorizers

**Comment by frostshoxx** [comment]
I got those 4 files after running `fetch-models.sh`. Somehow it works fine on gitbash, but if I run on powershell, it took forever to download just `model.onnx`.

Thanks again for tackling the System.Drawing issue!
