### ISSUE TITLE
Badly formatted filter expression on AggreagtionSet

### ISSUE THREAD

**Issue by VitaliiBushylo** [redis/redis-om-dotnet#438]
**The issue.**
Getting error when I specify several operands in Filter for AggreagtionSet.

JSON model used for the test.
```
[Document(StorageType = StorageType.Json, Prefixes = new[] { nameof(UserForTest) })]
public class UserForTest
{
    [Indexed(Sortable = true, Aggregatable = true)]
    public string FirstName { get; set; }

    [Indexed(Sortable = true, Aggregatable = true)]
    public string LastName { get; set; }
}
```
The query.
```
var aggregationSet = provider.AggregationSet<UserForTest>();
var result = aggregationSet.Filter(m => m.RecordShell.FirstName == "John" && m.RecordShell.LastName == "Doe").ToList();
```
Getting Exception.
```
System.Exception: Missing (or badly formatted) value for expr->pred.right
Failed on FT.AGGREGATE userfortest-idx * FILTER @FirstName == 'John' && @LastName == Doe
 ---> StackExchange.Redis.RedisServerException: Missing (or badly formatted) value for expr->pred.right
```

The correctly formatted command is working though.
![image](https://github.com/redis/redis-om-dotnet/assets/27290203/33d78a7e-80fc-49e5-b0be-c44b0ecdc81d)

Please clarify am I doing something wrong here?
Thank you!

**Comment by slorello89** [comment]
The expression parser was losing context that it was in a filter expression when it was building the operand string fro the right side of the expression. Opened #439 to address.

**Comment by VitaliiBushylo** [comment]
> The expression parser was losing context that it was in a filter expression when it was building the operand string fro the right side of the expression. Opened #439 to address.

Thank you @slorello89 for quick feedback. Looking forward for the fix release.
