### ISSUE TITLE
How to use Redis.OM.AspNetCore

### ISSUE THREAD

**Issue by delepster** [redis/redis-om-dotnet#442]
I want to use the `IRedisConnectionProvider` through injection but I do not see how I can use the `Redis.OM.AspNetCore` namespace and `AddRedis`. The only public package I can install is `Redis.OM`. How can I solve this?

**Comment by slorello89** [comment]
You can just add IRedisConnectionProvider as a singleton service.


```cs
builder.Services.AddSingleton<IRedisConnectionProvider>(new RedisConnectionProvider("redis://localhost:6379"));
```

**Comment by delepster** [comment]
Alright, so the `IServiceCollection` extension is not intended to be used publicly?

**Comment by slorello89** [comment]
It's not in the library. So no.

**Comment by delepster** [comment]
Alright, thx for the info!
