### ISSUE TITLE
Casting IRedisCollection as IQueryable causes Chunk info to get dropped

### ISSUE THREAD

**Issue by CormacLennon** [redis/redis-om-dotnet#454]
Casting an IRedisCollection to IQueryable causes chunk info to get dropped

```
    string[] comps = ["1", "2", "3", "4"];
    var users = provider.RedisCollection<User>(500) as IQueryable<User>;
    var res = await users.Where(x => comps.Contains(x.CompanyId));

```

Run a profiler whilst that is executed and it it pages in chunks of 100.

**Comment by CormacLennon** [comment]
I've a fix for this and will try and get a PR opened soon enough

**Comment by shapik1234** [comment]
I think your fix addresses [another issue](https://github.com/redis/redis-om-dotnet/issues/429) as well. Is there any update on whether your PR will be accepted?
