### ISSUE TITLE
Searching by GUID not working

### ISSUE THREAD

**Issue by dshchupak** [redis/redis-om-dotnet#465]
I am unable to search against a property that is marked as a GUID outside of the property that is annotated by RedisIdField, which is set as a nullable GUID (Guid?). Searching against this works just fine. However, if I have a second property that is a GUID, even if I change it to a string, I am unable to retrieve the record.

Below is some sample code using GUID:

```
[Document(StorageType = StorageType.Json, Prefixes = ["Item"])]
public class ItemDocument
{
    public DateTime CreationMomentUtc { get; set; }

    [RedisIdField]
    [Indexed]
    public Guid? ItemId { get; set; }

    [Indexed]
    public Guid OrderId { get; set; }
}
```

I have tried the following:

```
var document = await _items.SingleOrDefaultAsync(x => x.OrderId == orderId);
var document = await _items.FirstOrDefaultAsync(x => x.OrderId == orderId);
var documents = await _items.Where(x => x.OrderId == orderId).ToListAsync();
```

I tried changing the Indexed attribute to Searchable, but that didn't help. 

Below is the same code, but using string instead of GUID:

```
[Document(StorageType = StorageType.Json, Prefixes = ["Item"])]
public class ItemDocument
{
    public DateTime CreationMomentUtc { get; set; }

    [RedisIdField]
    [Indexed]
    public Guid? ItemId { get; set; }

    [Indexed]
    public required string OrderId { get; set; }
}
```

I have tried the following:

```
var document = await _items.SingleOrDefaultAsync(x => x.OrderId == $"{orderId}");
var document = await _items.FirstOrDefaultAsync(x => x.OrderId == $"{orderId}");
var documents = await _items.Where(x => x.OrderId == $"{orderId}").ToListAsync();
```

This did not work either.

Am I missing something?

**Comment by slorello89** [comment]
Hi @dshchupak  - GUID searches seem to work fine on my end.

Can you confirm that you are recreating the index every time you modify your model? e.g. calling `provider.Connection.DropIndex(typeof(ItemDocument));`

**Comment by dshchupak** [comment]
Hey @slorello89 - I do not have the drop, but I did setup a hosted service that runs at startup, per documentation. It appears to be taking in the changes I made when I switched from using Indexed and Searchable because I was getting an error trying to use Searchable.

Here is my hosted service setup:

```
public sealed class RedisIndexCreationService(IRedisConnectionProvider provider) : IHostedService
{
    public async Task StartAsync(CancellationToken cancellationToken)
    {
        await provider.Connection.CreateIndexAsync(typeof(OrderDocument));
        await provider.Connection.CreateIndexAsync(typeof(ItemDocument));
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
```

And I am registering it using DI along with registering IRedisConnectionProvider as a singleton.

Where would I need to add the DropIndex? Should I drop indexes on Stop or before creating the fresh at Start?

**Comment by slorello89** [comment]
@dshchupak - calling `DropIndexAsync` in the `StartAsync` implementation before the `CreateIndexAsync` would work. However, I would guard the call to `DropIndexAsync` with some kind of command-line switch, or configuration options, and only run it when your model has changed.

**Comment by dshchupak** [comment]
@slorello89 That appears to have solved the issue. Thank you!!
