### ISSUE TITLE
DateTimeOffset properties will cause an exception to be thrown upon insertion

### ISSUE THREAD

**Issue by DanJRWalsh** [redis/redis-om-dotnet#50]
When trying to insert a model with a `DateTimeOffset` property, it'll result in an error. I'm assuming this is a similar issue to #26 that was resolved in #30.

I'm currently working around this by converting my offsets to regular `DateTime`'s which is not ideal when dealing with multiple timezones.

The issue doesn't seem to occur when using the JSON storage type ~~, but then the records don't seem to get added to the index properly.~~

**Comment by slorello89** [comment]
Hi @DanJRWalsh - I think I figured out the parsing bit for hash - what do you mean by it's not indexing properly in JSON? The indexed attributes weren't intended for DateTimeOffset (at least not yet) so this may be the expected behavior.

**Comment by DanJRWalsh** [comment]
@slorello89 Sorry I was a bit vague there at the end - I didn't mean that the DateTimeOffset field, in particular, but rather the entire record was not added to my index. 

But please disregard that portion, something weird happened on my end on Friday, it's working as intended during my tests this morning. The only valid portion of this issue is for the DateTimeOffset parsing which you've said you've already resolved, so we're all good :)
