### ISSUE TITLE
Bulk operations using native JSON.MGET or JSON.MSET

### ISSUE THREAD

**Issue by JesusVFR** [redis/redis-om-dotnet#500]
Hello everyone,

I've noticed that Redis OM does not seem to handle bulk operations for inserting and reading, specifically using native Redis commands like JSON.MGET and JSON.MSET.

I'd like to understand if this is due to performance limitations or if there might be other underlying reasons for this. I'm exploring the possibility of creating a process that maximizes I/O to Redis, and using bulk commands seemed like a good approach.

Any insights on potential performance implications or technical challenges would be greatly appreciated. Thank you!

**Comment by slorello89** [comment]
Hi @JesusVFR - can you give a little more clarity on what you mean? what exactly is it you're trying to do?

**Comment by JesusVFR** [comment]
Hello @slorello89 

I'm developing a software application that processes real-time data and uses Redis as a primary data store. Due to the high volume of read and write operations per second, I'm looking for the most optimized way to handle these operations with Redis. I believe that bulk operations, like JSON.MGET and JSON.MSET, could be key in maximizing I/O throughput to Redis.

Currently, I've noticed that Redis OM does not seem to support bulk operations directly for JSON objects, which leads me to wonder if this is due to performance trade-offs or other design considerations. I would love to understand any potential technical challenges around implementing bulk commands within Redis OM and to discuss potential ways to enhance Redis OM for high-frequency real-time applications.

Thank you very much for your insights and support!

**Comment by slorello89** [comment]
Hi @JesusVFR I guess my big question here is what value would Redis OM provide that you can't already get out of the regular JSON.MGET / JSON.MSET operations? E.g. what would the api looks like?

A RedisCollection query with a Select is equivalent to an MGET, and calling Update on a set of documents or calling save is the equivalent of an MSET, so what else would you be looking for?

**Comment by slorello89** [comment]
going to close this out to tidy up - if you have some particular feedback about what you think the API should look like here feel free to reopen!

**Comment by rezaokhovat** [comment]
Thank u
