### ISSUE TITLE
Guid properties are excluded during hash insert

### ISSUE THREAD

**Issue by DanJRWalsh** [redis/redis-om-dotnet#51]
If I insert a model with a `Guid` property, the property is not passed to Redis. 

Currently, I have to change all my Id properties to `string` and use `ToString()` and `Guid.Parse()` anytime I'm mapping between models when dealing with `Guid`'s.

### Model:
```
[Document]
public class MyCacheModel
{
    [RedisIdField] public Guid Id { get; set; }
    [Indexed] public Guid? IdNullable { get; set; }
    [Indexed] public string IdString { get; set; }
}
```
### Inserting:
```
IRedisCollection<MyCacheModel> collection = redis.RedisCollection<MyCacheModel>();

Guid myGuidId = new Guid("9C133AE9-2DC2-496A-AC3B-3562F9B89DB2");
string myGuidIdStr = myGuidId.ToString();

await collection.InsertAsync(new MyCacheModel
{
    Id = myGuidId,
    IdNullable = myGuidId,
    IdString = myGuidIdStr
});
```
### Retrieving:
```
MyCacheModel myModel = await collection.FindByIdAsync("MyCacheModel:" + myGuidIdStr);

Console.WriteLine($"Id As Guid: {myModel.Id}\nId As Nullable Guid: {myModel.IdNullable}\nId As String: {myModel.IdString}");
```
### Console Output:
```
Id As Guid: 00000000-0000-0000-0000-000000000000
Id As Nullable Guid: 
Id As String: 9C133AE9-2DC2-496A-AC3B-3562F9B89DB2
```

If I then view that record in Redsmin, `Id` and `IdNullable` are completely absent with `IdString` being the only field present:
![Screenshot 2022-01-28 131633](https://user-images.githubusercontent.com/1395674/151602148-6e870f15-aab0-4c08-a7c4-728ed77a5a8f.png)

One thing to note (as demonstrated above) is it **does** correctly extract the `Guid`'s value for use as the key, it's just the field values on the record that are missing. 

It's also worth mentioning that when using JSON as the storage type, it correctly serializes the value to a string and can be retrieved with JSON.GET:
```
{
  "Id": "9c133ae9-2dc2-496a-ac3b-3562f9b89db2",
  "IdNullable": "9c133ae9-2dc2-496a-ac3b-3562f9b89db2",
  "IdString": "9c133ae9-2dc2-496a-ac3b-3562f9b89db2"
}
```

**Comment by slorello89** [comment]
Hey @DanJRWalsh - I think I actually tripped over this today—see #53—The problem seems to have been doing null rather than default checking when binding the ids to the model in the [ObjectHandler](https://github.com/redis/redis-om-dotnet/blob/v0.1.4/src/Redis.OM/RedisObjectHandler.cs#L113) PR should fix it, going to sit on it over the weekend and come back to it next week.

**Comment by DanJRWalsh** [comment]
@slorello89 Perfect - I had actually started on changes myself that looked very similar to your PR but since you've got it under control, I'll leave it with you. 

I was also working on #50 since that just needs a check for DateTimeOffset in RedisObjectHandler, similar to what was done in #30 (could probably use the same conditional branch since you're passing the DateTime into a DateTimeOffset anyways). Should I submit a PR for that separately or will that be completed as well?

Thanks!
