### ISSUE TITLE
Select not working, Redis.om generate redis query with wrong column count

### ISSUE THREAD

**Issue by pabnemlig** [redis/redis-om-dotnet#510]
Okay I think I have run into a bug.

I have this class:
[Document(StorageType = StorageType.Json)]
public record ProductTimelineCache
{
    [RedisIdField]
    public Ulid Id { get; set; }
    [Indexed]
    public string? ProductId { get; set; }
    [Indexed]
    public string? DistributionCenter { get; set; }
    [Indexed]
    public required string Hash { get; set; }
    [Indexed(CascadeDepth = 1)]
    public PriceCampaignInterval[] PriceTimeLine { get; set; } = [];
    [Indexed(CascadeDepth = 1)]
    public ProductExposureCampaignInterval[] ExposureCampaigns { get; set; } = [];
}

Where I want to list all { ProductId, Hash }, excluding all other fields so I write:
`await _provider.RedisCollection<ProductTimelineCache>()
                .Select(q => new { q.ProductId, q.DistributionCenter, q.Hash })
                .ToListAsync()
                .WaitAsync(cancellationToken)`

This fails with the REDIS Dragonfly syntax error:
ERR syntax error\r\nFailed on FT.SEARCH producttimelinecache-idx * LIMIT 0 100 RETURN 9 ProductId AS ProductId DistributionCenter AS DistributionCenter Hash AS Hash

It fails because of the number "9" above which I presume is the column count. Fixing it to 3 and manually issuing it on CLI makes REDIS respond.

**Comment by pabnemlig** [comment]
The problem seems to go futher than this, if I remove aliases from the count in redis.om, I only get an empty result because indexed fields are prefixed with $.Name leading to there being no match for the fields in the select part.

Here is my class:
[Document(StorageType = StorageType.Json)]
public record ProductTimelineCache
{
    [RedisIdField]
    public Ulid Id { get; set; }
    [Indexed(IndexEmptyAndMissing = false, JsonPath = "$.ProductId")]
    public string? ProductId { get; set; }
    [Indexed(IndexEmptyAndMissing = false, JsonPath = "$.DistributionCenter")]
    public string? DistributionCenter { get; set; }
    [Indexed(IndexEmptyAndMissing = false, JsonPath = "$.Hash")]
    public string? Hash { get; set; }
}

This query:
await _provider.RedisCollection<ProductTimelineCache>()
                .Select(q => new { q.ProductId, q.DistributionCenter, q.Hash })
                .ToListAsync()
                .WaitAsync(cancellationToken))
                
Generates the wrong query with wrong count and missing paths
FT.SEARCH producttimelinecache-idx * LIMIT 0 1 RETURN 9 ProductId AS ProductId DistributionCenter AS DistributionCenter Hash AS Hash
                
But should have generated FT.SEARCH producttimelinecache-idx * LIMIT 0 1 RETURN 3 $.ProductId $.DistributionCenter $.Hash

**Comment by slorello89** [comment]
Hi @pabnemlig - Redis OM is creating the correct queries. the count after `RETURN` is not the number of fields to return, it is the number of arguments that Redis needs to read forward to finish parsing the query. This is an issue with Dragonfly. 

For some background, FT.SEARCH / FT.CREATE are part of the RediSearch module (a source available module created by Redis). Dragonfly, in an attempt to provide some level of feature parity, attempted to copy the API. I cannot personally attest to its completeness nor its stability. I can however, speak from my own experience when I say that this is not first API compatibility issue I've heard from Dragonfly's users.
