### ISSUE TITLE
How save works?

### ISSUE THREAD

**Issue by kratotheron** [redis/redis-om-dotnet#63]
How works the save method?

**Comment by slorello89** [comment]
Hi @kratotheron, for the moment you can update objects by enumerating them, changing a field, and saving the redis collection, see this [example](https://github.com/redis-developer/redis-om-dotnet-skeleton-app/blob/main/Controllers/PeopleController.cs#L86)

**Comment by kratotheron** [comment]
I have tried with Save and SaveAsync (there's a Console.WriteLine inside) without any success.

Have I to install some module in redis in order to do this?

**Comment by slorello89** [comment]
Nope, RediSearch and RedisJSON are all you should need, are you getting an error?

**Comment by kratotheron** [comment]
I'm not getting an error. If I try to update the object by enumerating them, save, and read again the collection nothing has changed
This is my code:
`foreach(var eventToSend in _events.Where(x => x.Sent == false)
{
    eventToSend.Sent = true;
    _events.Save();
   return JsonSerializer.Serialize(eventToSend);
}`

The return statement is to ignore.

If I run this code 2 times my data are the same

**Comment by slorello89** [comment]
Try saving outside of the foreach, is anything coming across to Redis when you run `MONITOR` from the Redis CLI?

**Comment by kratotheron** [comment]
That's my monitor log
[monitor.log](https://github.com/redis/redis-om-dotnet/files/8003876/monitor.log)

**Comment by slorello89** [comment]
Interesting, it's not sending anything to update, not really sure what's going on, Trying to something similar on my end works just fine, can you share your code and model with me?

thanks!

**Comment by kratotheron** [comment]
Model
`[Document(Prefixes = new[] { "events" }, StorageType = StorageType.Hash)]
public class LoginLogoutEvent
{
    [RedisIdField] [Indexed] public string Id { get; set; }
    [Indexed] public string PacketType { get; set; } = null!;
    [Indexed(Sortable = true)] public DateTime Datetime { get; set; }
    [Indexed] public bool Sent { get; set; }
    [Indexed] public string Username { get; set; } = null!;
    [Indexed] public string SessionId { get; set; } = null!;
}`

EventGetter
`public async Task<string> GetNextEvent()
    {
        await Task.Delay(1);
        var events = (RedisCollection<LoginLogoutEvent>)_prov.RedisCollection<LoginLogoutEvent>();
        Console.WriteLine("Events in db");

        foreach (var eventToSend1 in events)
        {
            Console.WriteLine(JsonSerializer.Serialize(eventToSend1));
        }

        Console.WriteLine("Done");

        var eventToSend = events.First(x => x.Sent == false);
        
        Console.WriteLine($"Changing event with id: {eventToSend.Id}");
        eventToSend.Sent = true;
        Console.WriteLine(JsonSerializer.Serialize(eventToSend));

        events.Save();
        Console.WriteLine("Events after change");
        foreach (var eventToSend2 in events)
        {
            Console.WriteLine(JsonSerializer.Serialize(eventToSend2));
        }

        Console.WriteLine("Done");
        return null!;
    }`

I cannot share more code for security reason.

**Comment by kratotheron** [comment]
Looking at your code I have seen that at this line [https://github.com/redis/redis-om-dotnet/blob/c9f5dc4cf76cb57b3af1ca0ee755fe4309153158/src/Redis.OM/Modeling/RedisCollectionStateManager.cs#L106](RedisCollectionStateManager.cs Line 106) the Data are not changed.

**Comment by slorello89** [comment]
@kratotheron - looks like when you use `First` the item in question is not being inserted into the `RedisCollectionStateManager`. Try using `Where().Take(1)`, which should produce an equivalent query and do what you want.

**Comment by kratotheron** [comment]
Using your solution works! For my use case is ok to use this solution.
