### ISSUE TITLE
String with double quote 

### ISSUE THREAD

**Issue by kratotheron** [redis/redis-om-dotnet#69]
If a string property of the Model contains a double quote (") the deserialization on file RedisObjectHandler.cs at line 66 fail.
I added a replace in the SendToJson function in file RedisObjectHandler.cs at line 307.

Old:
`ret += $"\"{propertyName}\":\"{hash[propertyName]}\","`

New:
`ret += $"\"{propertyName}\":\"{hash[propertyName].Replace("\"","\\\"")}\","`

I have done that because my string contains a json string.

**Comment by kratotheron** [comment]
Ok thank you, but using the StorageType.Json with a DateTime in my model, the data inside the database are saved as seconds from 1970, i think, and when is checking the difference the compare is done with the ISO string of the current DateTime value, that is not changed. So it always think is changed.
The save method throw an exception.

**Comment by shacharPash** [comment]
I investigated the issue and I think that the problem is probably related to the UTC.
For example, my time zone is UTC + 3, when I insert a date to Redis and retrieve it, the date retrieve is the date I entered minus 3 hours.
I will address this bug in the near future.
