### ISSUE TITLE
"Unknown argument `ON` when CreateIndexAsync

### ISSUE THREAD

**Issue by NaveenYamparala** [redis/redis-om-dotnet#72]
I am new to using Redis OM, 

I have RedisJson Module Installed.

I am trying to follow the Redis OM Demo from here https://developer.redis.com/develop/dotnet/redis-om-dotnet/simple-text-queries.

I am getting the error ""Unknown argument `ON`" at the line "await connection.CreateIndexAsync(typeof(Employee));"
I tried using  [Document (StorageType = StorageType.Json)] as well but no luck. Please help me resolve the issue.

Thanks!

**Comment by slorello89** [comment]
Hi @NaveenYamparala, I think most likely what's happening is you are using an older version of RedisJson, can you try installing the latest version, along with RedisSearch, or if you are using docker run:

```bash
docker pull redislabs/rejson
```

**Comment by NaveenYamparala** [comment]
Thanks @slorello89 . Updating RedisJson solved the issue.
