### ISSUE TITLE
Building the query in stages

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#78]
How Is it possible to build my query using multiple statements?  I would like to do something like this:

```
var provider = new RedisConnectionProvider("redis://localhost:6379");
var collection = provider.RedisCollection<Transaction>();
var query = collection.Where(q=>q.Account == "1234");

// Do some logic tests here
if (activeOnly) query = query.Where(q=> q.Active == true);  // originally (q=> q.Active)

var totalCount = query.Count();
var pagedResults = query.Skip(skip).Take(take).ToList();
return {Total = totalCount, Results = pagedResults};
```

Update 1:  It appears the issues is with the Boolean parsing.  When I change to (q.Active == true) I get more milage.

Update 2:  I think maybe it's joining the two expressions as an OR, and not an AND, as I am getting back too many results.

Update 3:  Depending on the dataset, my milage varies, but I could definitely see a need for a way to build a query.  If not this way outlined above, some QueryBuilder object that allows to string together various Func<T,bool> expressions into one logical query that the backend will understand.

Thoughts?

**Comment by slorello89** [comment]
`RedisCollection` only supports a single Where clause at the moment. Interesting point about the `q.Active == true` vs. `q.Active`, realistically it's mostly meant for string matching but there should be something we can do to get it to pick up on boolean expressions like so. Might be an enhancement worth making.

I'd contest that if you've already done `collection.Where(q=>q.Account == "1234");`, and need to apply some intermittent logic before applying the `q.Active == true`, that you've already had a need for materializing the results, and therefore should just be able to build your results off of the materialized results, otherwise, you should just have it all in the same `Where` clause.

**Comment by VagyokC4** [comment]
So, my query is complicated slightly with the paging aspect, in that I need to get a count of all items returned by the query, as well as just the paged result, so I was trying to do that all in the DB and only pull back the page worth of actual results.

But yes, I think in its current form it will be a two-step process, requiring I bring a lot of data down, then perform additional filtering.

Question:  Is it OM library that only supports the single where clause, or is it not supported upstream?  And if the former, how big of a lift is it to get multiple where clauses (or some form of builder that can eventually build the single where clause)?

**Comment by slorello89** [comment]
## Issue with Count

It looks like Count is ignoring the predicate passed into it, however, if you send an empty count after your where clause, it works as expected

```
var muppets = provider.RedisCollection<Muppet>();

await muppets.InsertAsync(kermit);
await muppets.InsertAsync(beaker);
await muppets.InsertAsync(bunsen);

Console.WriteLine(muppets.Where(x=>x.FirstName == "kermit").Count());
Console.WriteLine(muppets.Count(x=>x.FirstName == "Kermit"));
```

results in:

```
1
3
```

The arching assumption is that you'll primarily use the Where clause for filtering, but we do have precedent for other cases, e.g. `[Any](https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM/Searching/RedisCollection.cs#L80)`. So this should be something relatively easy to fix.

## Pagination

> So, my query is complicated slightly with the paging aspect, in that I need to get a count of all items returned by the query, as well as just the paged result, so I was trying to do that all in the DB and only pull back the page worth of actual results.

I think I should probably point out to you, that Redis.OM will automatically paginate for you based on the chunk size you requested when initializing the collection.

## Single where clause

The rationale behind the single where clause has to do with the way queries work in RediSearch. This isn't SQL after all, you can't do any sort of table-joins or any cross-index querying, and the `FT.SEARCH` command that the `RedisCollection` operates off of only takes a single query string. So it's basically a reflection of the way the server operates. If we were going to allow multiple where clauses, it would effectively just be extending the same expressions `.Where(x=>x.FirstName == "kermit").Where(x=>x.LastName == "the frog")` is effectively the same as `.Where(x=>x.FirstName == "Kermit" && x.LastName == "the frog");`,  with the Predicate builder you are using, it looks like it should be producing the binary expressions that Redis.OM expects.

**Comment by VagyokC4** [comment]
> ## Pagination
> > So, my query is complicated slightly with the paging aspect, in that I need to get a count of all items returned by the query, as well as just the paged result, so I was trying to do that all in the DB and only pull back the page worth of actual results.
> 
> I think I should probably point out to you, that Redis.OM will automatically paginate for you based on the chunk size you requested when initializing the collection. It's an async enumerable so you can just await it, Redis.OM will take care of it for you, I would encourage you to lean towards larger chunk sizes if you can.
> 

So, I think with the Count issue resolved, I can move forward.  What I meant about the paging is not all in one call, but from the web UI client, the ability to page through the results back form the DB.  i.e., each page is a single request received and fulfilled by the back-end Api. So, it would not be a case of holding a connection open while we page the results down, so to speak.

Yes, I have been having luck with the Predicate Builder, and your example of multiple .Where() clauses would be what I would expect to be able to do.  Check some logic, add a .Where(), further down, check some logic, continue building the .Where() clause.  Maybe you see the value in adding the functionality natively?

Thank-you again for your detailed response. 👍

**Comment by VagyokC4** [comment]
> Interesting point about the `q.Active == true` vs. `q.Active`, realistically it's mostly meant for string matching but there should be something we can do to get it to pick up on boolean expressions like so. Might be an enhancement worth making.

Yeah, now my tests are showing no valid results with a Boolean in the search.  How big of a lift is it to get boolean checking working?

**Comment by slorello89** [comment]
So yeah, skip/take for pagination is the right route then,

RE folding together Where queries, I think if you have an API with a more complex conglomeration of things you might be combining this probably has a lot of merit as a nice-to-have, but the problem would happen down-stream as you start building anon types on top of whatever the type of the collection is, could probably validate, not certain how difficult this would be, probably would have to do something similar to the expression building library you pointed to.

**Comment by slorello89** [comment]
Going to be working on this one today on stream if anyone's interested: https://www.twitch.tv/redisinc
