### ISSUE TITLE
How to select the database to use

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#80]
Currently all activity takes place on DB0.  How do I use the other DBs?  I feel like the provider should provide this functionality.

**Comment by slorello89** [comment]
`SELECT` is a weird use-case if you are using RediSearch (most users use Redis-cloud or the Cluster API which don't support `SELECT` operations). That said, it's a capability that might be worth adding if there's enough people using the RediSearch module outside of a Redis Cloud instance, or a fair number of people pick up on the hash-based object-mapping stuff.

**Comment by VagyokC4** [comment]
![image](https://user-images.githubusercontent.com/253250/157706221-c1c158bd-a09f-4626-89ec-f0968dfb9e12.png)

We just need to expose the database number to pass into the GetDatabase line.

**Comment by slorello89** [comment]
So @VagyokC4 , I was looking a bit more into this today,

Actually, you CAN set a database by properly formatting the Redis URI:

`redis://localhost:6379/5` will set the multiplexer's default Database to the number in the path (in this instance 5).

However, RediSearch does not support creating indices off of DB 0, it will actually respond with an error when you try to create an index. So for the purposes of Redis.OM this basically makes using a non-0 database pointless.

I'll point out that Salvatore, the author of Redis, considers multiple databases in Redis his [worst design decision](https://groups.google.com/g/redis-db/c/vS5wX8X4Cjg/m/8ounBXitG4sJ), and we do tend to consider using them an [anti-pattern](https://redis.com/blog/7-redis-worst-practices/)

**Comment by VagyokC4** [comment]
Interesting.  Ok, thank-you for the quality response.  I will take this into consideration going forward.
