### ISSUE TITLE
Document the NuGet package

### ISSUE THREAD

**Issue by robrich** [redis/redis-om-dotnet#81]
I spent a great deal of time identifying that the package was called `Redis.OM`.

Please add a reference to this on:

- https://redis.github.io/redis-om-dotnet/articles/intro.html
- https://redis.com/blog/introducing-redis-om-net/

It would've saved me an hour.

... btw https://redis.com/blog/introducing-redis-om-net/ references the "API docs" on https://didactic-potato-b7cc3d29.pages.github.io/api/Redis.OM.html which is a 404.

**Comment by slorello89** [comment]
Had the blog updated. Thanks for pointing this out Rob, closing this out.
