### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#85]
It seems I can only use ToListAsync(), but get an error on FirstOrDefaultAsync(), FirstAsync() etc.

There is an Insert and InsertAsync, but the Delete and Update return tasks, and there doesn't appear to be a sync version.

Any plans to normalize the async access for this library?

**Comment by slorello89** [comment]
FirstOrDefaultAsync/FirstAsync should work, that's a bug if they aren't, I'll make sure to address it, they had worked when I first wrote them, but I see they aren't being hit by my tests so it's possible they've broken.

RE normalizing Delete/Update, maybe, in general less and less convinced daily of having sync operations hitting a database, had considered just having no sync operations. Still pre-1.0 so I can still make BCs without revving the major, will consider.

**Comment by VagyokC4** [comment]
> FirstOrDefaultAsync/FirstAsync should work, that's a bug if they aren't, I'll make sure to address it, they had worked when I first wrote them, but I see they aren't being hit by my tests so it's possible they've broken.
> 
> RE normalizing Delete/Update, maybe, in general less and less convinced daily of having sync operations hitting a database, had considered just having no sync operations. Still pre-1.0 so I can still make BCs without revving the major, will consider.

Interesting.  Yes, I think async all the way is not a bad idea, but then there's that part of me that thinks, maybe it's better to also have the sync version for when you are not in an async environment for whatever reason (even if it's just wrapping the async in a GetAwaiter().GetResult() as a convenience method).  Plus, you already have FindById/Save/Insert already with both.

I look forward to seeing your updated tests on it.  So, [here](http://share.linqpad.net/4ed4ks.linq) is a LINQ pad where I test various methods using logic like this:
![image](https://user-images.githubusercontent.com/253250/160718971-eab922e7-df1d-44f6-8807-01f1255edf03.png)
![image](https://user-images.githubusercontent.com/253250/160719042-d2ed6bee-1f5d-4db7-82b0-4263d98915d5.png)


Here I am targeting the Id field:
![image](https://user-images.githubusercontent.com/253250/160718668-87643cc4-e7f3-4084-9906-5d53d76da044.png)

And here I'm targeting a non id field:
![image](https://user-images.githubusercontent.com/253250/160718730-5fd3a8ae-4a0b-4fd3-8f10-70bf2e8a9584.png)

Interestingly I can't seem to get Count working as we discussed [here.](https://github.com/redis/redis-om-dotnet/issues/78#issuecomment-1065476879) when counting the Id property.  When I try to count another property I get a result back.  This seems a little inconsistent

**Comment by slorello89** [comment]
Come to think of it, I don't think the library actually exposes any of these methods, I'm assuming you are using an extension library to do it? The IQueryable stuff is based off a bunch of extension methods that will probably need to be updated.

**Comment by VagyokC4** [comment]
> Come to think of it, I don't think the library actually exposes any of these methods, I'm assuming you are using an extension library to do it? The IQueryable stuff is based off a bunch of extension methods that will probably need to be updated.

Yeah, I'm using these [Queryable Extensions](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.queryableextensions?view=entity-framework-6.2.0), which is where I found the working ToListAsync().

**Comment by slorello89** [comment]
Ahh, gotcha, yeah this isn't EF, so mileage may vary from the extensions they advertise, some of these would be nice to have so I might be able to add them directly on the interface.

**Comment by VagyokC4** [comment]
> Ahh, gotcha, yeah this isn't EF, so mileage may vary from the extensions they advertise, some of these would be nice to have so I might be able to add them directly on the interface.

That works!  Yeah, I was pleasantly surprised when the ToListAsync worked, made me think if it's just the IQueryable we are dealing with, then maybe a lot of these "extensions" will work, or at least there should be some low hanging fruit there, to get them to work.

Yeah, I understand milage will vary.  Honestly probably added more to my test (out of curiosity) than I actually would even **need**.  Just a basic stack would probably be enough, like First, Single, Any, Last, Count, along with the OrDefault versions.

**Comment by slorello89** [comment]
Yeah for counts, first's, any's single's I think this should be pretty doable. Last might be a bit tricky, it's doable, but you would need a minimum of 2 round-trips to Redis (RT-1 to identify the offset of the last record, RT-2 to grab it) and OM can't guarantee the atomicity of that operation, so probably won't happen lol. The others should be easy-ish to materialize in a single round trip.

**Comment by VagyokC4** [comment]
> Yeah for counts, first's, any's single's I think this should be pretty doable. Last might be a bit tricky, it's doable, but you would need a minimum of 2 round-trips to Redis (RT-1 to identify the offset of the last record, RT-2 to grab it) and OM can't guarantee the atomicity of that operation, so probably won't happen lol. The others should be easy-ish to materialize in a single round trip.

The one thing I missed that would probably be considered core would be .Contains().

    var items = new[] {
      "First",
      "Second",
      "Third"
    };
    var res = collection.Where(c => items.Contains(c.Id)).ToList();

Hopefully you tell me this is doable?
