### ISSUE TITLE
Is a .Contains() query possible?

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#91]
Question:  Could we have the ability to query with .Contains().

    var ids= new[] {
      "ID1",
      "ID2",
      "ID3"
    };
    var res = collection.Where(c => ids.Contains(c.Id)).ToList();

Is a query like this even possible with Redis?

**Comment by slorello89** [comment]
You would need to use the raw query API:

```
var query = new RedisQuery("indexName");
query.QueryText = $"{{{string.Join('|', ids)}}}";
var res = await provider.Connection.SearchAsync<Type>(query);
```

**Comment by VagyokC4** [comment]
> You would need to use the raw query API:
> 
> ```cs
> var query = new RedisQuery("indexName");
> query.QueryText = $"{{{string.Join('|', ids)}}}";
> var res = await provider.Connection.SearchAsync<Type>(query);
> ```

So it is possible.  That's good.  Is it safe to assume that it can be wrapped into the Where clause, or are they incompatible?

**Comment by rpf3** [comment]
I was not able to get this to work either.  Would it be possible to flesh this out a bit more in the extended docs?  When I try to run the raw query API I get a Redis `syntax error at offset 0`.

**Comment by slorello89** [comment]
@rpf3 what query were you producing?

**Comment by giangcoi48k** [comment]
[VagyokC4](https://github.com/VagyokC4) I have the same issue with .Contains query. So I need to use an Expression builder to resolve this problem. For example:

```C#
Expression<Func<SectorBucket, bool>> exp = default!;

foreach (var id in ids)
{
	if (exp == null)
		exp = ExpressionBuilder.Build<SectorBucket>(t => t.Id == id);
	else
		exp = exp.Or(t => t.Id == id);
}

var rs = await _connectionProvider
	.RedisCollection<SectorBucket>()
	.Where(exp)
	.ToListAsync();
```

**Comment by rpf3** [comment]
@slorello89 here's the relevant stack trace

```
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2834
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 53
at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1226
at StackExchange.Redis.RedisDatabase.Execute(String command, Object[] args) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1222
at Redis.OM.RedisConnection.Execute(String command, String[] args)
at Redis.OM.RediSearchCommands.SearchRawResult(IRedisConnection connection, RedisQuery query)
at Redis.OM.Searching.RedisCollectionEnumerator`1.GetNextChunk()
at Redis.OM.Searching.RedisCollectionEnumerator`1.MoveNext()
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
```

Let me know if I can provide more details.

**Comment by zLucPlayZ** [comment]
> @rpf3 what query were you producing?

Having the same issues with redis query, i tried everything so far, but I just cant it to work. I just want to get entries by multiple ids or fields. Also, the new function for FindByIds creates a hundered tasks, thats really bad imo. Should be one database call.

**Comment by VagyokC4** [comment]
@slorello89 Did this functionality get merged in yet?  #174 says it's done, and I remember watching you code it.
Really looking forward to a new version with #174 and #165 baked in.  Any ETA on bumping a new version?

**Comment by VagyokC4** [comment]
> @slorello89 Did this functionality get merged in yet? #174 says it's done, and I remember watching you code it. Really looking forward to a new version with #174 and #165 baked in. Any ETA on bumping a new version?

@slorello89 bumping this

**Comment by slorello89** [comment]
Hey @VagyokC4 - sorry been on the road the last couple weeks so I've had somewhat limited bandwidth to work on this issue :) - finally got to crack it open this morning and get it to a place where I'm happy with it - PR opened.

**Comment by VagyokC4** [comment]
> Hey @VagyokC4 - sorry been on the road the last couple weeks so I've had somewhat limited bandwidth to work on this issue :) - finally got to crack it open this morning and get it to a place where I'm happy with it - PR opened.

@slorello89 Awesome... When do we get a new version drop?
