### ISSUE TITLE
Enum Support

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#95]
Also, can we get some Enum support.

```
public enum SampleType
{
	No,
	Maybe,
	Yes
}

[Flags]
public enum SampleFlagType
{
	None = 0,
	No = 1 << 0,
	Maybe = 1 << 1,
	Yes = 1 << 2
}

public record TmTag : IKeyValuePair, IEnumFlagPair
{
	[RedisIdField]
	[Indexed]
	public string Id {get; init; }

	[Indexed] public SampleType Type { get; init; }
	[Indexed] public SampleFlagType Flag { get; init; }
}


// Enum Support
try { (await collection.Where(c => c.Type == SampleType.Maybe).ToListAsync()).Dump("Enum Type"); }
catch { "Enum Type".Dump("Error"); }

// Enum < Support
try { (await collection.Where(c => c.Type < SampleType.Maybe).ToListAsync()).Dump("Enum < Type"); }
catch { "Enum < Type".Dump("Error"); }

// Enum Flag Support
try { (await collection.Where(c => c.Flag == (SampleFlagType.Yes | SampleFlagType.Maybe)).ToListAsync()).Dump("Enum Flag Type"); }
catch { "Enum Flag Type".Dump("Error"); }
```

Since this all works off of ints, this is all very doable right?

**Comment by slorello89** [comment]
I think this would be a nice-to-have enhancement, see what kind of interest it draws, might be worth adding down the road.

**Comment by VagyokC4** [comment]
> I think this would be a nice-to-have enhancement, see what kind of interest it draws, might be worth adding down the road.

I would almost argue that this is a must have enhancement.  As it stands now I cannot query when an Enum is being used, and I cannot cast my way around it. `.Where(c => c.Type == (int)SampleType.Maybe)`  So even though it's stored in Redis as an int, I cannot query it because .net says my == operator cannot be applied because it's not an enum.

**Comment by slorello89** [comment]
Going to roll this into #128
