### ISSUE TITLE
.FindByIdsAsync()

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#96]
So I was thinking about the .Contains() query, and how I would use it a lot to pull back a collection of documents.
Maybe this is a common use case that justifies adding `Task<List<T>> FindByIdsAsync(params string[] ids)`  or something to that effect.

Thoughts?

**Comment by slorello89** [comment]
This should be easy enough for a user to implement, if there's more demand for it, maybe, not sure it's a huge value-add as is (also you'd probably want to return a `IDictionary<string, T?>` given you don't know ahead of time whether the corresponding Ids exist.

**Comment by zLucPlayZ** [comment]
Sorry but I have a serious concern about this implementation. You just start a task for every id, and wait for all? Thats like 1 call to redis per id?

**Comment by slorello89** [comment]
Async calls to redis are pipelined under the hood, so yes it's 1 command per id, however it's one round trip to redis.

**Comment by slorello89** [comment]
closed with #167
