### ISSUE TITLE
.Where(x=>x.property == null)

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#97]
Given the following results in Redis:
![image](https://user-images.githubusercontent.com/253250/161446472-169d311f-09ce-4c28-83f0-e9ead86f4e02.png)

I'd like to get back the records that have null as the value like so:
```cs
collection.Where( x => x.ERN == null).ToList();
```

I get a `RedisServerException Syntax error at offset 7 near ERN` when I try to search.

**Comment by slorello89** [comment]
Null is not a legal value in RediSearch, it will actually break the index if you try to set it. Hence the failure here, you'd need to use an aggregation and check to see if The field exists to filter on it properly.

**Comment by VagyokC4** [comment]
> Null is not a legal value in RediSearch, it will actually break the index if you try to set it. Hence the failure here, you'd need to use an aggregation and check to see if The field exists to filter on it properly.

Ah good to know.  Do you have an example of what that would look like?

**Comment by slorello89** [comment]
TestExists in ApplyFunctionsTests demonstrates this capability:

https://github.com/redis/redis-om-dotnet/blob/main/test/Redis.OM.Unit.Tests/RediSearchTests/ApplyFunctionTests.cs#L998
