### ISSUE TITLE
DateTime / DateTImeOffset support?

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#99]
Would it be possible to search on a DateTime / DateTimeOffset property?  Specifically to do date rage filters?

```
await collection.Where(c => c.Date > dateTime).ToListAsync();
await collection.Where(c => c.Date < dateTime).ToListAsync();
```

**Comment by giangcoi48k** [comment]
`[Indexed(Sortable = true)] public long Timestamp => ((DateTimeOffset)CreateDate).ToUnixTimeMilliseconds();`
I need to resolve this issue by converting Datetime to timestamp

**Comment by VagyokC4** [comment]
> `[Indexed(Sortable = true)] public long Timestamp => ((DateTimeOffset)CreateDate).ToUnixTimeMilliseconds();` I need to resolve this issue by converting Datetime to timestamp

@slorello89 Is this a good candidate for the JsonConverter type logic you did with enums?  I would like to have the DateTime / DateTimeOffest type and be able to sort on it, without the need for the "extra" data on the model.

**Comment by slorello89** [comment]
#240 Will address the DateTime bit of this at least.

**Comment by slorello89** [comment]
Closing as completed by #240
